// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	allowance "mybilibili/app/coupon/cmd/api/internal/handler/allowance"
	captcha "mybilibili/app/coupon/cmd/api/internal/handler/captcha"
	code "mybilibili/app/coupon/cmd/api/internal/handler/code"
	coupon "mybilibili/app/coupon/cmd/api/internal/handler/coupon"
	"mybilibili/app/coupon/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 取消使用代金券
				Method:  http.MethodPost,
				Path:    "/allowance/cancel",
				Handler: allowance.CancelAllowanceCouponHandler(serverCtx),
			},
			{
				// 代金券列表
				Method:  http.MethodGet,
				Path:    "/allowance/list",
				Handler: allowance.AllowanceListHandler(serverCtx),
			},
			{
				// 领取代金券
				Method:  http.MethodPost,
				Path:    "/allowance/receive",
				Handler: allowance.ReceiveAllowanceHandler(serverCtx),
			},
			{
				// 获取可用代金券V2
				Method:  http.MethodPost,
				Path:    "/allowance/usable",
				Handler: allowance.UsableAllowanceCouponV2Handler(serverCtx),
			},
			{
				// 使用代金券
				Method:  http.MethodPost,
				Path:    "/allowance/use",
				Handler: allowance.UseAllowanceCouponHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/coupon/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取验证码Token
				Method:  http.MethodGet,
				Path:    "/captcha/token",
				Handler: captcha.CaptchaTokenHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/coupon/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 使用兑换码
				Method:  http.MethodPost,
				Path:    "/code/use",
				Handler: code.UseCouponCodeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/coupon/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 观影券分页列表
				Method:  http.MethodGet,
				Path:    "/page",
				Handler: coupon.CouponPageHandler(serverCtx),
			},
			{
				// 用户观影券列表
				Method:  http.MethodGet,
				Path:    "/user/list",
				Handler: coupon.UserCouponHandler(serverCtx),
			},
			{
				// 观影券数量
				Method:  http.MethodGet,
				Path:    "/video/count",
				Handler: coupon.VideoCouponCountHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/coupon/v1"),
	)
}
