// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	search "mybilibili/app/search/cmd/api/internal/handler/search"
	"mybilibili/app/search/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 弹幕搜索
				Method:  http.MethodGet,
				Path:    "/dm",
				Handler: search.DmSearchHandler(serverCtx),
			},
			{
				// 弹幕日期搜索
				Method:  http.MethodGet,
				Path:    "/dm/date",
				Handler: search.DmDateSearchHandler(serverCtx),
			},
			{
				// 弹幕索引更新
				Method:  http.MethodPost,
				Path:    "/dm/update",
				Handler: search.DmUpdateHandler(serverCtx),
			},
			{
				// 弹幕历史搜索
				Method:  http.MethodGet,
				Path:    "/dmhistory",
				Handler: search.DmHistorySearchHandler(serverCtx),
			},
			{
				// PGC番剧搜索
				Method:  http.MethodGet,
				Path:    "/pgc",
				Handler: search.PgcMediaSearchHandler(serverCtx),
			},
			{
				// PGC索引更新
				Method:  http.MethodPost,
				Path:    "/pgc/update",
				Handler: search.PgcUpdateHandler(serverCtx),
			},
			{
				// 评论记录搜索
				Method:  http.MethodGet,
				Path:    "/reply",
				Handler: search.ReplyRecordSearchHandler(serverCtx),
			},
			{
				// 评论索引更新
				Method:  http.MethodPost,
				Path:    "/reply/update",
				Handler: search.ReplyUpdateHandler(serverCtx),
			},
		},
		rest.WithPrefix("/x/internal/search"),
	)
}
