// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: hotrank.proto

package hotrank_client

import (
	"context"

	"mybilibili/app/hotrank/cmd/rpc/hotrank"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetHotByOIDReq           = hotrank.GetHotByOIDReq
	GetHotByOIDResp          = hotrank.GetHotByOIDResp
	GetHotRankListReq        = hotrank.GetHotRankListReq
	GetHotRankListResp       = hotrank.GetHotRankListResp
	GetRegionHotRankListReq  = hotrank.GetRegionHotRankListReq
	GetRegionHotRankListResp = hotrank.GetRegionHotRankListResp
	HotRankItem              = hotrank.HotRankItem

	Hotrank interface {
		// 获取全站热门排行榜
		GetHotRankList(ctx context.Context, in *GetHotRankListReq, opts ...grpc.CallOption) (*GetHotRankListResp, error)
		// 获取分区热门排行榜
		GetRegionHotRankList(ctx context.Context, in *GetRegionHotRankListReq, opts ...grpc.CallOption) (*GetRegionHotRankListResp, error)
		// 获取热度值（根据OID）
		GetHotByOID(ctx context.Context, in *GetHotByOIDReq, opts ...grpc.CallOption) (*GetHotByOIDResp, error)
	}

	defaultHotrank struct {
		cli zrpc.Client
	}
)

func NewHotrank(cli zrpc.Client) Hotrank {
	return &defaultHotrank{
		cli: cli,
	}
}

// 获取全站热门排行榜
func (m *defaultHotrank) GetHotRankList(ctx context.Context, in *GetHotRankListReq, opts ...grpc.CallOption) (*GetHotRankListResp, error) {
	client := hotrank.NewHotrankClient(m.cli.Conn())
	return client.GetHotRankList(ctx, in, opts...)
}

// 获取分区热门排行榜
func (m *defaultHotrank) GetRegionHotRankList(ctx context.Context, in *GetRegionHotRankListReq, opts ...grpc.CallOption) (*GetRegionHotRankListResp, error) {
	client := hotrank.NewHotrankClient(m.cli.Conn())
	return client.GetRegionHotRankList(ctx, in, opts...)
}

// 获取热度值（根据OID）
func (m *defaultHotrank) GetHotByOID(ctx context.Context, in *GetHotByOIDReq, opts ...grpc.CallOption) (*GetHotByOIDResp, error) {
	client := hotrank.NewHotrankClient(m.cli.Conn())
	return client.GetHotByOID(ctx, in, opts...)
}
