// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	hotrank "mybilibili/app/api/creative/internal/handler/hotrank"
	recommend "mybilibili/app/api/creative/internal/handler/recommend"
	video "mybilibili/app/api/creative/internal/handler/video"
	"mybilibili/app/api/creative/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取全站热门排行榜
				Method:  http.MethodGet,
				Path:    "/hotrank/list",
				Handler: hotrank.GetHotRankListHandler(serverCtx),
			},
			{
				// 获取分区热门排行榜
				Method:  http.MethodGet,
				Path:    "/hotrank/region",
				Handler: hotrank.GetRegionHotRankListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/creative/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取推荐列表
				Method:  http.MethodGet,
				Path:    "/recommend/list",
				Handler: recommend.GetRecommendListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/creative/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取视频详情
				Method:  http.MethodGet,
				Path:    "/video/:vid",
				Handler: video.GetVideoDetailHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/creative/v1"),
	)
}
