// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: video.proto

package video_client

import (
	"context"

	"mybilibili/app/video/cmd/rpc/video"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchGetVideoInfoReq  = video.BatchGetVideoInfoReq
	BatchGetVideoInfoResp = video.BatchGetVideoInfoResp
	BatchGetVideoStatReq  = video.BatchGetVideoStatReq
	BatchGetVideoStatResp = video.BatchGetVideoStatResp
	GetVideoInfoReq       = video.GetVideoInfoReq
	GetVideoInfoResp      = video.GetVideoInfoResp
	GetVideoListReq       = video.GetVideoListReq
	GetVideoListResp      = video.GetVideoListResp
	GetVideoStatReq       = video.GetVideoStatReq
	GetVideoStatResp      = video.GetVideoStatResp
	VideoData             = video.VideoData
	VideoInfo             = video.VideoInfo
	VideoStat             = video.VideoStat

	Video interface {
		// 获取视频信息
		GetVideoInfo(ctx context.Context, in *GetVideoInfoReq, opts ...grpc.CallOption) (*GetVideoInfoResp, error)
		// 批量获取视频信息
		BatchGetVideoInfo(ctx context.Context, in *BatchGetVideoInfoReq, opts ...grpc.CallOption) (*BatchGetVideoInfoResp, error)
		// 获取视频列表（游标分页）
		GetVideoList(ctx context.Context, in *GetVideoListReq, opts ...grpc.CallOption) (*GetVideoListResp, error)
		// 获取视频统计数据
		GetVideoStat(ctx context.Context, in *GetVideoStatReq, opts ...grpc.CallOption) (*GetVideoStatResp, error)
		// 批量获取视频统计数据
		BatchGetVideoStat(ctx context.Context, in *BatchGetVideoStatReq, opts ...grpc.CallOption) (*BatchGetVideoStatResp, error)
	}

	defaultVideo struct {
		cli zrpc.Client
	}
)

func NewVideo(cli zrpc.Client) Video {
	return &defaultVideo{
		cli: cli,
	}
}

// 获取视频信息
func (m *defaultVideo) GetVideoInfo(ctx context.Context, in *GetVideoInfoReq, opts ...grpc.CallOption) (*GetVideoInfoResp, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.GetVideoInfo(ctx, in, opts...)
}

// 批量获取视频信息
func (m *defaultVideo) BatchGetVideoInfo(ctx context.Context, in *BatchGetVideoInfoReq, opts ...grpc.CallOption) (*BatchGetVideoInfoResp, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.BatchGetVideoInfo(ctx, in, opts...)
}

// 获取视频列表（游标分页）
func (m *defaultVideo) GetVideoList(ctx context.Context, in *GetVideoListReq, opts ...grpc.CallOption) (*GetVideoListResp, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.GetVideoList(ctx, in, opts...)
}

// 获取视频统计数据
func (m *defaultVideo) GetVideoStat(ctx context.Context, in *GetVideoStatReq, opts ...grpc.CallOption) (*GetVideoStatResp, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.GetVideoStat(ctx, in, opts...)
}

// 批量获取视频统计数据
func (m *defaultVideo) BatchGetVideoStat(ctx context.Context, in *BatchGetVideoStatReq, opts ...grpc.CallOption) (*BatchGetVideoStatResp, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.BatchGetVideoStat(ctx, in, opts...)
}
