// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	academyArchiveFieldNames          = builder.RawFieldNames(&AcademyArchive{})
	academyArchiveRows                = strings.Join(academyArchiveFieldNames, ",")
	academyArchiveRowsExpectAutoSet   = strings.Join(stringx.Remove(academyArchiveFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	academyArchiveRowsWithPlaceHolder = strings.Join(stringx.Remove(academyArchiveFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheAcademyArchiveIdPrefix  = "cache:academyArchive:id:"
	cacheAcademyArchiveOidPrefix = "cache:academyArchive:oid:"
)

type (
	academyArchiveModel interface {
		Insert(ctx context.Context, data *AcademyArchive) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AcademyArchive, error)
		FindOneByOid(ctx context.Context, oid int64) (*AcademyArchive, error)
		Update(ctx context.Context, data *AcademyArchive) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAcademyArchiveModel struct {
		sqlc.CachedConn
		table string
	}

	AcademyArchive struct {
		Id       int64     `db:"id"`        // 自增ID（用于游标分页）
		Oid      int64     `db:"oid"`       // 对象ID（视频ID或专栏ID）
		Hot      int64     `db:"hot"`       // 热度值
		Business int64     `db:"business"`  // 业务类型：1-视频，2-专栏
		RegionId int64     `db:"region_id"` // 分区ID
		PubTime  int64     `db:"pub_time"`  // 发布时间（Unix时间戳）
		State    int64     `db:"state"`     // 状态：0-正常，1-删除
		Comment  string    `db:"comment"`   // 备注
		Ctime    time.Time `db:"ctime"`     // 创建时间
		Mtime    time.Time `db:"mtime"`     // 修改时间
	}
)

func newAcademyArchiveModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAcademyArchiveModel {
	return &defaultAcademyArchiveModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`academy_archive`",
	}
}

func (m *defaultAcademyArchiveModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	academyArchiveIdKey := fmt.Sprintf("%s%v", cacheAcademyArchiveIdPrefix, id)
	academyArchiveOidKey := fmt.Sprintf("%s%v", cacheAcademyArchiveOidPrefix, data.Oid)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, academyArchiveIdKey, academyArchiveOidKey)
	return err
}

func (m *defaultAcademyArchiveModel) FindOne(ctx context.Context, id int64) (*AcademyArchive, error) {
	academyArchiveIdKey := fmt.Sprintf("%s%v", cacheAcademyArchiveIdPrefix, id)
	var resp AcademyArchive
	err := m.QueryRowCtx(ctx, &resp, academyArchiveIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", academyArchiveRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAcademyArchiveModel) FindOneByOid(ctx context.Context, oid int64) (*AcademyArchive, error) {
	academyArchiveOidKey := fmt.Sprintf("%s%v", cacheAcademyArchiveOidPrefix, oid)
	var resp AcademyArchive
	err := m.QueryRowIndexCtx(ctx, &resp, academyArchiveOidKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `oid` = ? limit 1", academyArchiveRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, oid); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAcademyArchiveModel) Insert(ctx context.Context, data *AcademyArchive) (sql.Result, error) {
	academyArchiveIdKey := fmt.Sprintf("%s%v", cacheAcademyArchiveIdPrefix, data.Id)
	academyArchiveOidKey := fmt.Sprintf("%s%v", cacheAcademyArchiveOidPrefix, data.Oid)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, academyArchiveRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Oid, data.Hot, data.Business, data.RegionId, data.PubTime, data.State, data.Comment, data.Ctime, data.Mtime)
	}, academyArchiveIdKey, academyArchiveOidKey)
	return ret, err
}

func (m *defaultAcademyArchiveModel) Update(ctx context.Context, newData *AcademyArchive) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	academyArchiveIdKey := fmt.Sprintf("%s%v", cacheAcademyArchiveIdPrefix, data.Id)
	academyArchiveOidKey := fmt.Sprintf("%s%v", cacheAcademyArchiveOidPrefix, data.Oid)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, academyArchiveRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Oid, newData.Hot, newData.Business, newData.RegionId, newData.PubTime, newData.State, newData.Comment, newData.Ctime, newData.Mtime, newData.Id)
	}, academyArchiveIdKey, academyArchiveOidKey)
	return err
}

func (m *defaultAcademyArchiveModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheAcademyArchiveIdPrefix, primary)
}

func (m *defaultAcademyArchiveModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", academyArchiveRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAcademyArchiveModel) tableName() string {
	return m.table
}
