// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	videoInfoFieldNames          = builder.RawFieldNames(&VideoInfo{})
	videoInfoRows                = strings.Join(videoInfoFieldNames, ",")
	videoInfoRowsExpectAutoSet   = strings.Join(stringx.Remove(videoInfoFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	videoInfoRowsWithPlaceHolder = strings.Join(stringx.Remove(videoInfoFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheVideoInfoIdPrefix  = "cache:videoInfo:id:"
	cacheVideoInfoVidPrefix = "cache:videoInfo:vid:"
)

type (
	videoInfoModel interface {
		Insert(ctx context.Context, data *VideoInfo) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*VideoInfo, error)
		FindOneByVid(ctx context.Context, vid int64) (*VideoInfo, error)
		Update(ctx context.Context, data *VideoInfo) error
		Delete(ctx context.Context, id int64) error
	}

	defaultVideoInfoModel struct {
		sqlc.CachedConn
		table string
	}

	VideoInfo struct {
		Id         int64          `db:"id"`          // 自增ID
		Vid        int64          `db:"vid"`         // 视频ID
		Title      string         `db:"title"`       // 标题
		Cover      string         `db:"cover"`       // 封面URL
		AuthorId   int64          `db:"author_id"`   // 作者ID
		AuthorName string         `db:"author_name"` // 作者名称
		RegionId   int64          `db:"region_id"`   // 分区ID
		Duration   int64          `db:"duration"`    // 时长（秒）
		Desc       sql.NullString `db:"desc"`        // 简介
		PubTime    int64          `db:"pub_time"`    // 发布时间（Unix时间戳）
		State      int64          `db:"state"`       // 状态：0-正常，1-删除
		Ctime      time.Time      `db:"ctime"`       // 创建时间
		Mtime      time.Time      `db:"mtime"`       // 修改时间
	}
)

func newVideoInfoModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultVideoInfoModel {
	return &defaultVideoInfoModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`video_info`",
	}
}

func (m *defaultVideoInfoModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	videoInfoIdKey := fmt.Sprintf("%s%v", cacheVideoInfoIdPrefix, id)
	videoInfoVidKey := fmt.Sprintf("%s%v", cacheVideoInfoVidPrefix, data.Vid)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, videoInfoIdKey, videoInfoVidKey)
	return err
}

func (m *defaultVideoInfoModel) FindOne(ctx context.Context, id int64) (*VideoInfo, error) {
	videoInfoIdKey := fmt.Sprintf("%s%v", cacheVideoInfoIdPrefix, id)
	var resp VideoInfo
	err := m.QueryRowCtx(ctx, &resp, videoInfoIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", videoInfoRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultVideoInfoModel) FindOneByVid(ctx context.Context, vid int64) (*VideoInfo, error) {
	videoInfoVidKey := fmt.Sprintf("%s%v", cacheVideoInfoVidPrefix, vid)
	var resp VideoInfo
	err := m.QueryRowIndexCtx(ctx, &resp, videoInfoVidKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `vid` = ? limit 1", videoInfoRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, vid); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultVideoInfoModel) Insert(ctx context.Context, data *VideoInfo) (sql.Result, error) {
	videoInfoIdKey := fmt.Sprintf("%s%v", cacheVideoInfoIdPrefix, data.Id)
	videoInfoVidKey := fmt.Sprintf("%s%v", cacheVideoInfoVidPrefix, data.Vid)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, videoInfoRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Vid, data.Title, data.Cover, data.AuthorId, data.AuthorName, data.RegionId, data.Duration, data.Desc, data.PubTime, data.State, data.Ctime, data.Mtime)
	}, videoInfoIdKey, videoInfoVidKey)
	return ret, err
}

func (m *defaultVideoInfoModel) Update(ctx context.Context, newData *VideoInfo) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	videoInfoIdKey := fmt.Sprintf("%s%v", cacheVideoInfoIdPrefix, data.Id)
	videoInfoVidKey := fmt.Sprintf("%s%v", cacheVideoInfoVidPrefix, data.Vid)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, videoInfoRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Vid, newData.Title, newData.Cover, newData.AuthorId, newData.AuthorName, newData.RegionId, newData.Duration, newData.Desc, newData.PubTime, newData.State, newData.Ctime, newData.Mtime, newData.Id)
	}, videoInfoIdKey, videoInfoVidKey)
	return err
}

func (m *defaultVideoInfoModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheVideoInfoIdPrefix, primary)
}

func (m *defaultVideoInfoModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", videoInfoRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultVideoInfoModel) tableName() string {
	return m.table
}
