// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	videoStatFieldNames          = builder.RawFieldNames(&VideoStat{})
	videoStatRows                = strings.Join(videoStatFieldNames, ",")
	videoStatRowsExpectAutoSet   = strings.Join(stringx.Remove(videoStatFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	videoStatRowsWithPlaceHolder = strings.Join(stringx.Remove(videoStatFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheVideoStatIdPrefix  = "cache:videoStat:id:"
	cacheVideoStatVidPrefix = "cache:videoStat:vid:"
)

type (
	videoStatModel interface {
		Insert(ctx context.Context, data *VideoStat) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*VideoStat, error)
		FindOneByVid(ctx context.Context, vid int64) (*VideoStat, error)
		Update(ctx context.Context, data *VideoStat) error
		Delete(ctx context.Context, id int64) error
	}

	defaultVideoStatModel struct {
		sqlc.CachedConn
		table string
	}

	VideoStat struct {
		Id        int64     `db:"id"`         // 自增ID
		Vid       int64     `db:"vid"`        // 视频ID
		View      int64     `db:"view"`       // 播放数
		LikeCount int64     `db:"like_count"` // 点赞数
		Coin      int64     `db:"coin"`       // 硬币数
		Fav       int64     `db:"fav"`        // 收藏数
		Share     int64     `db:"share"`      // 分享数
		Reply     int64     `db:"reply"`      // 评论数
		Danmaku   int64     `db:"danmaku"`    // 弹幕数
		Ctime     time.Time `db:"ctime"`      // 创建时间
		Mtime     time.Time `db:"mtime"`      // 修改时间
	}
)

func newVideoStatModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultVideoStatModel {
	return &defaultVideoStatModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`video_stat`",
	}
}

func (m *defaultVideoStatModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	videoStatIdKey := fmt.Sprintf("%s%v", cacheVideoStatIdPrefix, id)
	videoStatVidKey := fmt.Sprintf("%s%v", cacheVideoStatVidPrefix, data.Vid)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, videoStatIdKey, videoStatVidKey)
	return err
}

func (m *defaultVideoStatModel) FindOne(ctx context.Context, id int64) (*VideoStat, error) {
	videoStatIdKey := fmt.Sprintf("%s%v", cacheVideoStatIdPrefix, id)
	var resp VideoStat
	err := m.QueryRowCtx(ctx, &resp, videoStatIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", videoStatRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultVideoStatModel) FindOneByVid(ctx context.Context, vid int64) (*VideoStat, error) {
	videoStatVidKey := fmt.Sprintf("%s%v", cacheVideoStatVidPrefix, vid)
	var resp VideoStat
	err := m.QueryRowIndexCtx(ctx, &resp, videoStatVidKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `vid` = ? limit 1", videoStatRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, vid); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultVideoStatModel) Insert(ctx context.Context, data *VideoStat) (sql.Result, error) {
	videoStatIdKey := fmt.Sprintf("%s%v", cacheVideoStatIdPrefix, data.Id)
	videoStatVidKey := fmt.Sprintf("%s%v", cacheVideoStatVidPrefix, data.Vid)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, videoStatRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Vid, data.View, data.LikeCount, data.Coin, data.Fav, data.Share, data.Reply, data.Danmaku, data.Ctime, data.Mtime)
	}, videoStatIdKey, videoStatVidKey)
	return ret, err
}

func (m *defaultVideoStatModel) Update(ctx context.Context, newData *VideoStat) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	videoStatIdKey := fmt.Sprintf("%s%v", cacheVideoStatIdPrefix, data.Id)
	videoStatVidKey := fmt.Sprintf("%s%v", cacheVideoStatVidPrefix, data.Vid)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, videoStatRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Vid, newData.View, newData.LikeCount, newData.Coin, newData.Fav, newData.Share, newData.Reply, newData.Danmaku, newData.Ctime, newData.Mtime, newData.Id)
	}, videoStatIdKey, videoStatVidKey)
	return err
}

func (m *defaultVideoStatModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheVideoStatIdPrefix, primary)
}

func (m *defaultVideoStatModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", videoStatRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultVideoStatModel) tableName() string {
	return m.table
}
