// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: recommend.proto

package recommend

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 推荐请求
type RecommendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mid           int64                  `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`                       // 用户ID
	Buvid         string                 `protobuf:"bytes,2,opt,name=buvid,proto3" json:"buvid,omitempty"`                    // 设备ID（可选）
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                   // 返回数量，默认20
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`                     // 页码，默认1
	Debug         bool                   `protobuf:"varint,5,opt,name=debug,proto3" json:"debug,omitempty"`                   // 调试模式
	TraceId       string                 `protobuf:"bytes,6,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"` // 追踪ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendRequest) Reset() {
	*x = RecommendRequest{}
	mi := &file_recommend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendRequest) ProtoMessage() {}

func (x *RecommendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recommend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendRequest.ProtoReflect.Descriptor instead.
func (*RecommendRequest) Descriptor() ([]byte, []int) {
	return file_recommend_proto_rawDescGZIP(), []int{0}
}

func (x *RecommendRequest) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *RecommendRequest) GetBuvid() string {
	if x != nil {
		return x.Buvid
	}
	return ""
}

func (x *RecommendRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RecommendRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *RecommendRequest) GetDebug() bool {
	if x != nil {
		return x.Debug
	}
	return false
}

func (x *RecommendRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

// 推荐响应
type RecommendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*RecommendItem       `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`                                                                                                      // 推荐列表
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`                                                                                                   // 总数
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`                                                                                // 是否还有更多
	DebugInfo     map[string]string      `protobuf:"bytes,4,rep,name=debug_info,json=debugInfo,proto3" json:"debug_info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 调试信息
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`                                                                                                // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendResponse) Reset() {
	*x = RecommendResponse{}
	mi := &file_recommend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendResponse) ProtoMessage() {}

func (x *RecommendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recommend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendResponse.ProtoReflect.Descriptor instead.
func (*RecommendResponse) Descriptor() ([]byte, []int) {
	return file_recommend_proto_rawDescGZIP(), []int{1}
}

func (x *RecommendResponse) GetList() []*RecommendItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *RecommendResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *RecommendResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *RecommendResponse) GetDebugInfo() map[string]string {
	if x != nil {
		return x.DebugInfo
	}
	return nil
}

func (x *RecommendResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 推荐项
type RecommendItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Avid          int64                  `protobuf:"varint,1,opt,name=avid,proto3" json:"avid,omitempty"`                                                                             // 视频AV号
	Cid           int64                  `protobuf:"varint,2,opt,name=cid,proto3" json:"cid,omitempty"`                                                                               // 分P的CID
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`                                                                            // 标题
	Cover         string                 `protobuf:"bytes,4,opt,name=cover,proto3" json:"cover,omitempty"`                                                                            // 封面URL
	Duration      int32                  `protobuf:"varint,5,opt,name=duration,proto3" json:"duration,omitempty"`                                                                     // 时长(秒)
	PubTime       int64                  `protobuf:"varint,6,opt,name=pub_time,json=pubTime,proto3" json:"pub_time,omitempty"`                                                        // 发布时间戳
	ZoneId        int32                  `protobuf:"varint,7,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`                                                           // 分区ID
	ZoneName      string                 `protobuf:"bytes,8,opt,name=zone_name,json=zoneName,proto3" json:"zone_name,omitempty"`                                                      // 分区名称
	UpMid         int64                  `protobuf:"varint,9,opt,name=up_mid,json=upMid,proto3" json:"up_mid,omitempty"`                                                              // UP主MID
	UpName        string                 `protobuf:"bytes,10,opt,name=up_name,json=upName,proto3" json:"up_name,omitempty"`                                                           // UP主名称
	Play          int64                  `protobuf:"varint,11,opt,name=play,proto3" json:"play,omitempty"`                                                                            // 播放量
	Like          int64                  `protobuf:"varint,12,opt,name=like,proto3" json:"like,omitempty"`                                                                            // 点赞数
	Coin          int64                  `protobuf:"varint,13,opt,name=coin,proto3" json:"coin,omitempty"`                                                                            // 投币数
	Fav           int64                  `protobuf:"varint,14,opt,name=fav,proto3" json:"fav,omitempty"`                                                                              // 收藏数
	Share         int64                  `protobuf:"varint,15,opt,name=share,proto3" json:"share,omitempty"`                                                                          // 分享数
	Score         float64                `protobuf:"fixed64,16,opt,name=score,proto3" json:"score,omitempty"`                                                                         // 推荐分数
	Reason        string                 `protobuf:"bytes,17,opt,name=reason,proto3" json:"reason,omitempty"`                                                                         // 推荐理由
	Tags          []string               `protobuf:"bytes,18,rep,name=tags,proto3" json:"tags,omitempty"`                                                                             // 标签列表
	Extra         map[string]string      `protobuf:"bytes,19,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 额外信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendItem) Reset() {
	*x = RecommendItem{}
	mi := &file_recommend_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendItem) ProtoMessage() {}

func (x *RecommendItem) ProtoReflect() protoreflect.Message {
	mi := &file_recommend_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendItem.ProtoReflect.Descriptor instead.
func (*RecommendItem) Descriptor() ([]byte, []int) {
	return file_recommend_proto_rawDescGZIP(), []int{2}
}

func (x *RecommendItem) GetAvid() int64 {
	if x != nil {
		return x.Avid
	}
	return 0
}

func (x *RecommendItem) GetCid() int64 {
	if x != nil {
		return x.Cid
	}
	return 0
}

func (x *RecommendItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RecommendItem) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *RecommendItem) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *RecommendItem) GetPubTime() int64 {
	if x != nil {
		return x.PubTime
	}
	return 0
}

func (x *RecommendItem) GetZoneId() int32 {
	if x != nil {
		return x.ZoneId
	}
	return 0
}

func (x *RecommendItem) GetZoneName() string {
	if x != nil {
		return x.ZoneName
	}
	return ""
}

func (x *RecommendItem) GetUpMid() int64 {
	if x != nil {
		return x.UpMid
	}
	return 0
}

func (x *RecommendItem) GetUpName() string {
	if x != nil {
		return x.UpName
	}
	return ""
}

func (x *RecommendItem) GetPlay() int64 {
	if x != nil {
		return x.Play
	}
	return 0
}

func (x *RecommendItem) GetLike() int64 {
	if x != nil {
		return x.Like
	}
	return 0
}

func (x *RecommendItem) GetCoin() int64 {
	if x != nil {
		return x.Coin
	}
	return 0
}

func (x *RecommendItem) GetFav() int64 {
	if x != nil {
		return x.Fav
	}
	return 0
}

func (x *RecommendItem) GetShare() int64 {
	if x != nil {
		return x.Share
	}
	return 0
}

func (x *RecommendItem) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RecommendItem) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RecommendItem) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *RecommendItem) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

var File_recommend_proto protoreflect.FileDescriptor

const file_recommend_proto_rawDesc = "" +
	"\n" +
	"\x0frecommend.proto\x12\trecommend\"\x95\x01\n" +
	"\x10RecommendRequest\x12\x10\n" +
	"\x03mid\x18\x01 \x01(\x03R\x03mid\x12\x14\n" +
	"\x05buvid\x18\x02 \x01(\tR\x05buvid\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x14\n" +
	"\x05debug\x18\x05 \x01(\bR\x05debug\x12\x19\n" +
	"\btrace_id\x18\x06 \x01(\tR\atraceId\"\x96\x02\n" +
	"\x11RecommendResponse\x12,\n" +
	"\x04list\x18\x01 \x03(\v2\x18.recommend.RecommendItemR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\x12J\n" +
	"\n" +
	"debug_info\x18\x04 \x03(\v2+.recommend.RecommendResponse.DebugInfoEntryR\tdebugInfo\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x1a<\n" +
	"\x0eDebugInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x99\x04\n" +
	"\rRecommendItem\x12\x12\n" +
	"\x04avid\x18\x01 \x01(\x03R\x04avid\x12\x10\n" +
	"\x03cid\x18\x02 \x01(\x03R\x03cid\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x14\n" +
	"\x05cover\x18\x04 \x01(\tR\x05cover\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\x05R\bduration\x12\x19\n" +
	"\bpub_time\x18\x06 \x01(\x03R\apubTime\x12\x17\n" +
	"\azone_id\x18\a \x01(\x05R\x06zoneId\x12\x1b\n" +
	"\tzone_name\x18\b \x01(\tR\bzoneName\x12\x15\n" +
	"\x06up_mid\x18\t \x01(\x03R\x05upMid\x12\x17\n" +
	"\aup_name\x18\n" +
	" \x01(\tR\x06upName\x12\x12\n" +
	"\x04play\x18\v \x01(\x03R\x04play\x12\x12\n" +
	"\x04like\x18\f \x01(\x03R\x04like\x12\x12\n" +
	"\x04coin\x18\r \x01(\x03R\x04coin\x12\x10\n" +
	"\x03fav\x18\x0e \x01(\x03R\x03fav\x12\x14\n" +
	"\x05share\x18\x0f \x01(\x03R\x05share\x12\x14\n" +
	"\x05score\x18\x10 \x01(\x01R\x05score\x12\x16\n" +
	"\x06reason\x18\x11 \x01(\tR\x06reason\x12\x12\n" +
	"\x04tags\x18\x12 \x03(\tR\x04tags\x129\n" +
	"\x05extra\x18\x13 \x03(\v2#.recommend.RecommendItem.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012Z\n" +
	"\tRecommend\x12M\n" +
	"\x10GetRecommendList\x12\x1b.recommend.RecommendRequest\x1a\x1c.recommend.RecommendResponseB\rZ\v./recommendb\x06proto3"

var (
	file_recommend_proto_rawDescOnce sync.Once
	file_recommend_proto_rawDescData []byte
)

func file_recommend_proto_rawDescGZIP() []byte {
	file_recommend_proto_rawDescOnce.Do(func() {
		file_recommend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recommend_proto_rawDesc), len(file_recommend_proto_rawDesc)))
	})
	return file_recommend_proto_rawDescData
}

var file_recommend_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_recommend_proto_goTypes = []any{
	(*RecommendRequest)(nil),  // 0: recommend.RecommendRequest
	(*RecommendResponse)(nil), // 1: recommend.RecommendResponse
	(*RecommendItem)(nil),     // 2: recommend.RecommendItem
	nil,                       // 3: recommend.RecommendResponse.DebugInfoEntry
	nil,                       // 4: recommend.RecommendItem.ExtraEntry
}
var file_recommend_proto_depIdxs = []int32{
	2, // 0: recommend.RecommendResponse.list:type_name -> recommend.RecommendItem
	3, // 1: recommend.RecommendResponse.debug_info:type_name -> recommend.RecommendResponse.DebugInfoEntry
	4, // 2: recommend.RecommendItem.extra:type_name -> recommend.RecommendItem.ExtraEntry
	0, // 3: recommend.Recommend.GetRecommendList:input_type -> recommend.RecommendRequest
	1, // 4: recommend.Recommend.GetRecommendList:output_type -> recommend.RecommendResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_recommend_proto_init() }
func file_recommend_proto_init() {
	if File_recommend_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recommend_proto_rawDesc), len(file_recommend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recommend_proto_goTypes,
		DependencyIndexes: file_recommend_proto_depIdxs,
		MessageInfos:      file_recommend_proto_msgTypes,
	}.Build()
	File_recommend_proto = out.File
	file_recommend_proto_goTypes = nil
	file_recommend_proto_depIdxs = nil
}
