// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: hotrank.proto

package hotrank

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取全站热门排行榜请求
type GetHotRankListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int64                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"` // 偏移量
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`   // 返回条数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHotRankListReq) Reset() {
	*x = GetHotRankListReq{}
	mi := &file_hotrank_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHotRankListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotRankListReq) ProtoMessage() {}

func (x *GetHotRankListReq) ProtoReflect() protoreflect.Message {
	mi := &file_hotrank_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotRankListReq.ProtoReflect.Descriptor instead.
func (*GetHotRankListReq) Descriptor() ([]byte, []int) {
	return file_hotrank_proto_rawDescGZIP(), []int{0}
}

func (x *GetHotRankListReq) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetHotRankListReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// 获取全站热门排行榜响应
type GetHotRankListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*HotRankItem         `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`    // 排行榜列表
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // 总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHotRankListResp) Reset() {
	*x = GetHotRankListResp{}
	mi := &file_hotrank_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHotRankListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotRankListResp) ProtoMessage() {}

func (x *GetHotRankListResp) ProtoReflect() protoreflect.Message {
	mi := &file_hotrank_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotRankListResp.ProtoReflect.Descriptor instead.
func (*GetHotRankListResp) Descriptor() ([]byte, []int) {
	return file_hotrank_proto_rawDescGZIP(), []int{1}
}

func (x *GetHotRankListResp) GetList() []*HotRankItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetHotRankListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 获取分区热门排行榜请求
type GetRegionHotRankListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionId      int64                  `protobuf:"varint,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"` // 分区ID
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`                     // 偏移量
	Limit         int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                       // 返回条数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRegionHotRankListReq) Reset() {
	*x = GetRegionHotRankListReq{}
	mi := &file_hotrank_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRegionHotRankListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegionHotRankListReq) ProtoMessage() {}

func (x *GetRegionHotRankListReq) ProtoReflect() protoreflect.Message {
	mi := &file_hotrank_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegionHotRankListReq.ProtoReflect.Descriptor instead.
func (*GetRegionHotRankListReq) Descriptor() ([]byte, []int) {
	return file_hotrank_proto_rawDescGZIP(), []int{2}
}

func (x *GetRegionHotRankListReq) GetRegionId() int64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *GetRegionHotRankListReq) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetRegionHotRankListReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// 获取分区热门排行榜响应
type GetRegionHotRankListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*HotRankItem         `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`    // 排行榜列表
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // 总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRegionHotRankListResp) Reset() {
	*x = GetRegionHotRankListResp{}
	mi := &file_hotrank_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRegionHotRankListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegionHotRankListResp) ProtoMessage() {}

func (x *GetRegionHotRankListResp) ProtoReflect() protoreflect.Message {
	mi := &file_hotrank_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegionHotRankListResp.ProtoReflect.Descriptor instead.
func (*GetRegionHotRankListResp) Descriptor() ([]byte, []int) {
	return file_hotrank_proto_rawDescGZIP(), []int{3}
}

func (x *GetRegionHotRankListResp) GetList() []*HotRankItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetRegionHotRankListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 获取热度值请求
type GetHotByOIDReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Oid           int64                  `protobuf:"varint,1,opt,name=oid,proto3" json:"oid,omitempty"`           // 对象ID
	Business      int32                  `protobuf:"varint,2,opt,name=business,proto3" json:"business,omitempty"` // 业务类型：1-视频，2-专栏
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHotByOIDReq) Reset() {
	*x = GetHotByOIDReq{}
	mi := &file_hotrank_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHotByOIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotByOIDReq) ProtoMessage() {}

func (x *GetHotByOIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_hotrank_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotByOIDReq.ProtoReflect.Descriptor instead.
func (*GetHotByOIDReq) Descriptor() ([]byte, []int) {
	return file_hotrank_proto_rawDescGZIP(), []int{4}
}

func (x *GetHotByOIDReq) GetOid() int64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

func (x *GetHotByOIDReq) GetBusiness() int32 {
	if x != nil {
		return x.Business
	}
	return 0
}

// 获取热度值响应
type GetHotByOIDResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hot           int64                  `protobuf:"varint,1,opt,name=hot,proto3" json:"hot,omitempty"` // 热度值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHotByOIDResp) Reset() {
	*x = GetHotByOIDResp{}
	mi := &file_hotrank_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHotByOIDResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotByOIDResp) ProtoMessage() {}

func (x *GetHotByOIDResp) ProtoReflect() protoreflect.Message {
	mi := &file_hotrank_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotByOIDResp.ProtoReflect.Descriptor instead.
func (*GetHotByOIDResp) Descriptor() ([]byte, []int) {
	return file_hotrank_proto_rawDescGZIP(), []int{5}
}

func (x *GetHotByOIDResp) GetHot() int64 {
	if x != nil {
		return x.Hot
	}
	return 0
}

// 排行榜项
type HotRankItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Oid           int64                  `protobuf:"varint,1,opt,name=oid,proto3" json:"oid,omitempty"`           // 对象ID（视频ID）
	Business      int32                  `protobuf:"varint,2,opt,name=business,proto3" json:"business,omitempty"` // 业务类型：1-视频，2-专栏
	Hot           int64                  `protobuf:"varint,3,opt,name=hot,proto3" json:"hot,omitempty"`           // 热度值
	Rank          int64                  `protobuf:"varint,4,opt,name=rank,proto3" json:"rank,omitempty"`         // 排名（从1开始）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HotRankItem) Reset() {
	*x = HotRankItem{}
	mi := &file_hotrank_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HotRankItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotRankItem) ProtoMessage() {}

func (x *HotRankItem) ProtoReflect() protoreflect.Message {
	mi := &file_hotrank_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotRankItem.ProtoReflect.Descriptor instead.
func (*HotRankItem) Descriptor() ([]byte, []int) {
	return file_hotrank_proto_rawDescGZIP(), []int{6}
}

func (x *HotRankItem) GetOid() int64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

func (x *HotRankItem) GetBusiness() int32 {
	if x != nil {
		return x.Business
	}
	return 0
}

func (x *HotRankItem) GetHot() int64 {
	if x != nil {
		return x.Hot
	}
	return 0
}

func (x *HotRankItem) GetRank() int64 {
	if x != nil {
		return x.Rank
	}
	return 0
}

var File_hotrank_proto protoreflect.FileDescriptor

const file_hotrank_proto_rawDesc = "" +
	"\n" +
	"\rhotrank.proto\x12\ahotrank\"A\n" +
	"\x11GetHotRankListReq\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\"T\n" +
	"\x12GetHotRankListResp\x12(\n" +
	"\x04list\x18\x01 \x03(\v2\x14.hotrank.HotRankItemR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"d\n" +
	"\x17GetRegionHotRankListReq\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\x03R\bregionId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\"Z\n" +
	"\x18GetRegionHotRankListResp\x12(\n" +
	"\x04list\x18\x01 \x03(\v2\x14.hotrank.HotRankItemR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\">\n" +
	"\x0eGetHotByOIDReq\x12\x10\n" +
	"\x03oid\x18\x01 \x01(\x03R\x03oid\x12\x1a\n" +
	"\bbusiness\x18\x02 \x01(\x05R\bbusiness\"#\n" +
	"\x0fGetHotByOIDResp\x12\x10\n" +
	"\x03hot\x18\x01 \x01(\x03R\x03hot\"a\n" +
	"\vHotRankItem\x12\x10\n" +
	"\x03oid\x18\x01 \x01(\x03R\x03oid\x12\x1a\n" +
	"\bbusiness\x18\x02 \x01(\x05R\bbusiness\x12\x10\n" +
	"\x03hot\x18\x03 \x01(\x03R\x03hot\x12\x12\n" +
	"\x04rank\x18\x04 \x01(\x03R\x04rank2\xf3\x01\n" +
	"\aHotrank\x12I\n" +
	"\x0eGetHotRankList\x12\x1a.hotrank.GetHotRankListReq\x1a\x1b.hotrank.GetHotRankListResp\x12[\n" +
	"\x14GetRegionHotRankList\x12 .hotrank.GetRegionHotRankListReq\x1a!.hotrank.GetRegionHotRankListResp\x12@\n" +
	"\vGetHotByOID\x12\x17.hotrank.GetHotByOIDReq\x1a\x18.hotrank.GetHotByOIDRespB\vZ\t./hotrankb\x06proto3"

var (
	file_hotrank_proto_rawDescOnce sync.Once
	file_hotrank_proto_rawDescData []byte
)

func file_hotrank_proto_rawDescGZIP() []byte {
	file_hotrank_proto_rawDescOnce.Do(func() {
		file_hotrank_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hotrank_proto_rawDesc), len(file_hotrank_proto_rawDesc)))
	})
	return file_hotrank_proto_rawDescData
}

var file_hotrank_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_hotrank_proto_goTypes = []any{
	(*GetHotRankListReq)(nil),        // 0: hotrank.GetHotRankListReq
	(*GetHotRankListResp)(nil),       // 1: hotrank.GetHotRankListResp
	(*GetRegionHotRankListReq)(nil),  // 2: hotrank.GetRegionHotRankListReq
	(*GetRegionHotRankListResp)(nil), // 3: hotrank.GetRegionHotRankListResp
	(*GetHotByOIDReq)(nil),           // 4: hotrank.GetHotByOIDReq
	(*GetHotByOIDResp)(nil),          // 5: hotrank.GetHotByOIDResp
	(*HotRankItem)(nil),              // 6: hotrank.HotRankItem
}
var file_hotrank_proto_depIdxs = []int32{
	6, // 0: hotrank.GetHotRankListResp.list:type_name -> hotrank.HotRankItem
	6, // 1: hotrank.GetRegionHotRankListResp.list:type_name -> hotrank.HotRankItem
	0, // 2: hotrank.Hotrank.GetHotRankList:input_type -> hotrank.GetHotRankListReq
	2, // 3: hotrank.Hotrank.GetRegionHotRankList:input_type -> hotrank.GetRegionHotRankListReq
	4, // 4: hotrank.Hotrank.GetHotByOID:input_type -> hotrank.GetHotByOIDReq
	1, // 5: hotrank.Hotrank.GetHotRankList:output_type -> hotrank.GetHotRankListResp
	3, // 6: hotrank.Hotrank.GetRegionHotRankList:output_type -> hotrank.GetRegionHotRankListResp
	5, // 7: hotrank.Hotrank.GetHotByOID:output_type -> hotrank.GetHotByOIDResp
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_hotrank_proto_init() }
func file_hotrank_proto_init() {
	if File_hotrank_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hotrank_proto_rawDesc), len(file_hotrank_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hotrank_proto_goTypes,
		DependencyIndexes: file_hotrank_proto_depIdxs,
		MessageInfos:      file_hotrank_proto_msgTypes,
	}.Build()
	File_hotrank_proto = out.File
	file_hotrank_proto_goTypes = nil
	file_hotrank_proto_depIdxs = nil
}
