// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: hotrank.proto

package hotrank

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Hotrank_GetHotRankList_FullMethodName       = "/hotrank.Hotrank/GetHotRankList"
	Hotrank_GetRegionHotRankList_FullMethodName = "/hotrank.Hotrank/GetRegionHotRankList"
	Hotrank_GetHotByOID_FullMethodName          = "/hotrank.Hotrank/GetHotByOID"
)

// HotrankClient is the client API for Hotrank service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 热门排行榜服务
type HotrankClient interface {
	// 获取全站热门排行榜
	GetHotRankList(ctx context.Context, in *GetHotRankListReq, opts ...grpc.CallOption) (*GetHotRankListResp, error)
	// 获取分区热门排行榜
	GetRegionHotRankList(ctx context.Context, in *GetRegionHotRankListReq, opts ...grpc.CallOption) (*GetRegionHotRankListResp, error)
	// 获取热度值（根据OID）
	GetHotByOID(ctx context.Context, in *GetHotByOIDReq, opts ...grpc.CallOption) (*GetHotByOIDResp, error)
}

type hotrankClient struct {
	cc grpc.ClientConnInterface
}

func NewHotrankClient(cc grpc.ClientConnInterface) HotrankClient {
	return &hotrankClient{cc}
}

func (c *hotrankClient) GetHotRankList(ctx context.Context, in *GetHotRankListReq, opts ...grpc.CallOption) (*GetHotRankListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHotRankListResp)
	err := c.cc.Invoke(ctx, Hotrank_GetHotRankList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hotrankClient) GetRegionHotRankList(ctx context.Context, in *GetRegionHotRankListReq, opts ...grpc.CallOption) (*GetRegionHotRankListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRegionHotRankListResp)
	err := c.cc.Invoke(ctx, Hotrank_GetRegionHotRankList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hotrankClient) GetHotByOID(ctx context.Context, in *GetHotByOIDReq, opts ...grpc.CallOption) (*GetHotByOIDResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHotByOIDResp)
	err := c.cc.Invoke(ctx, Hotrank_GetHotByOID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HotrankServer is the server API for Hotrank service.
// All implementations must embed UnimplementedHotrankServer
// for forward compatibility.
//
// 热门排行榜服务
type HotrankServer interface {
	// 获取全站热门排行榜
	GetHotRankList(context.Context, *GetHotRankListReq) (*GetHotRankListResp, error)
	// 获取分区热门排行榜
	GetRegionHotRankList(context.Context, *GetRegionHotRankListReq) (*GetRegionHotRankListResp, error)
	// 获取热度值（根据OID）
	GetHotByOID(context.Context, *GetHotByOIDReq) (*GetHotByOIDResp, error)
	mustEmbedUnimplementedHotrankServer()
}

// UnimplementedHotrankServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHotrankServer struct{}

func (UnimplementedHotrankServer) GetHotRankList(context.Context, *GetHotRankListReq) (*GetHotRankListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHotRankList not implemented")
}
func (UnimplementedHotrankServer) GetRegionHotRankList(context.Context, *GetRegionHotRankListReq) (*GetRegionHotRankListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRegionHotRankList not implemented")
}
func (UnimplementedHotrankServer) GetHotByOID(context.Context, *GetHotByOIDReq) (*GetHotByOIDResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHotByOID not implemented")
}
func (UnimplementedHotrankServer) mustEmbedUnimplementedHotrankServer() {}
func (UnimplementedHotrankServer) testEmbeddedByValue()                 {}

// UnsafeHotrankServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HotrankServer will
// result in compilation errors.
type UnsafeHotrankServer interface {
	mustEmbedUnimplementedHotrankServer()
}

func RegisterHotrankServer(s grpc.ServiceRegistrar, srv HotrankServer) {
	// If the following call pancis, it indicates UnimplementedHotrankServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Hotrank_ServiceDesc, srv)
}

func _Hotrank_GetHotRankList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHotRankListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HotrankServer).GetHotRankList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hotrank_GetHotRankList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HotrankServer).GetHotRankList(ctx, req.(*GetHotRankListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hotrank_GetRegionHotRankList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRegionHotRankListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HotrankServer).GetRegionHotRankList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hotrank_GetRegionHotRankList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HotrankServer).GetRegionHotRankList(ctx, req.(*GetRegionHotRankListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hotrank_GetHotByOID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHotByOIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HotrankServer).GetHotByOID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hotrank_GetHotByOID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HotrankServer).GetHotByOID(ctx, req.(*GetHotByOIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Hotrank_ServiceDesc is the grpc.ServiceDesc for Hotrank service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Hotrank_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hotrank.Hotrank",
	HandlerType: (*HotrankServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHotRankList",
			Handler:    _Hotrank_GetHotRankList_Handler,
		},
		{
			MethodName: "GetRegionHotRankList",
			Handler:    _Hotrank_GetRegionHotRankList_Handler,
		},
		{
			MethodName: "GetHotByOID",
			Handler:    _Hotrank_GetHotByOID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hotrank.proto",
}
