// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: recommend.proto

package recommend_client

import (
	"context"

	"mybilibili/app/recommend/cmd/rpc/recommend"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	RecommendItem     = recommend.RecommendItem
	RecommendRequest  = recommend.RecommendRequest
	RecommendResponse = recommend.RecommendResponse

	Recommend interface {
		// 获取推荐列表
		GetRecommendList(ctx context.Context, in *RecommendRequest, opts ...grpc.CallOption) (*RecommendResponse, error)
	}

	defaultRecommend struct {
		cli zrpc.Client
	}
)

func NewRecommend(cli zrpc.Client) Recommend {
	return &defaultRecommend{
		cli: cli,
	}
}

// 获取推荐列表
func (m *defaultRecommend) GetRecommendList(ctx context.Context, in *RecommendRequest, opts ...grpc.CallOption) (*RecommendResponse, error) {
	client := recommend.NewRecommendClient(m.cli.Conn())
	return client.GetRecommendList(ctx, in, opts...)
}
