// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: recall.proto

package recall

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 召回请求
type RecallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mid           int64                  `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`                                 // 用户ID
	Buvid         string                 `protobuf:"bytes,2,opt,name=buvid,proto3" json:"buvid,omitempty"`                              // 设备ID
	TotalLimit    int32                  `protobuf:"varint,3,opt,name=total_limit,json=totalLimit,proto3" json:"total_limit,omitempty"` // 总召回数量限制
	Infos         []*RecallInfo          `protobuf:"bytes,4,rep,name=infos,proto3" json:"infos,omitempty"`                              // 召回策略信息列表
	TraceId       string                 `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`           // 追踪ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecallRequest) Reset() {
	*x = RecallRequest{}
	mi := &file_recall_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecallRequest) ProtoMessage() {}

func (x *RecallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recall_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecallRequest.ProtoReflect.Descriptor instead.
func (*RecallRequest) Descriptor() ([]byte, []int) {
	return file_recall_proto_rawDescGZIP(), []int{0}
}

func (x *RecallRequest) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *RecallRequest) GetBuvid() string {
	if x != nil {
		return x.Buvid
	}
	return ""
}

func (x *RecallRequest) GetTotalLimit() int32 {
	if x != nil {
		return x.TotalLimit
	}
	return 0
}

func (x *RecallRequest) GetInfos() []*RecallInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

func (x *RecallRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

// 召回策略信息
type RecallInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`          // 召回策略名称
	Tag           string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`            // Redis key
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`       // 召回数量
	Filter        string                 `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`      // 过滤器类型（如bloomfilter）
	Priority      int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"` // 优先级
	Scorer        string                 `protobuf:"bytes,6,opt,name=scorer,proto3" json:"scorer,omitempty"`      // 打分器类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecallInfo) Reset() {
	*x = RecallInfo{}
	mi := &file_recall_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecallInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecallInfo) ProtoMessage() {}

func (x *RecallInfo) ProtoReflect() protoreflect.Message {
	mi := &file_recall_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecallInfo.ProtoReflect.Descriptor instead.
func (*RecallInfo) Descriptor() ([]byte, []int) {
	return file_recall_proto_rawDescGZIP(), []int{1}
}

func (x *RecallInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RecallInfo) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *RecallInfo) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RecallInfo) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *RecallInfo) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *RecallInfo) GetScorer() string {
	if x != nil {
		return x.Scorer
	}
	return ""
}

// 召回响应
type RecallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*RecallItem          `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`                                                                                                      // 召回结果列表
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`                                                                                                   // 总数
	DebugInfo     map[string]string      `protobuf:"bytes,3,rep,name=debug_info,json=debugInfo,proto3" json:"debug_info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 调试信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecallResponse) Reset() {
	*x = RecallResponse{}
	mi := &file_recall_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecallResponse) ProtoMessage() {}

func (x *RecallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recall_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecallResponse.ProtoReflect.Descriptor instead.
func (*RecallResponse) Descriptor() ([]byte, []int) {
	return file_recall_proto_rawDescGZIP(), []int{2}
}

func (x *RecallResponse) GetList() []*RecallItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *RecallResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *RecallResponse) GetDebugInfo() map[string]string {
	if x != nil {
		return x.DebugInfo
	}
	return nil
}

// 召回项
type RecallItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Avid          int64                  `protobuf:"varint,1,opt,name=avid,proto3" json:"avid,omitempty"`                                                                            // 视频AV号
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`                                                                         // 召回分数
	RecallType    string                 `protobuf:"bytes,3,opt,name=recall_type,json=recallType,proto3" json:"recall_type,omitempty"`                                               // 召回类型
	RecallTag     string                 `protobuf:"bytes,4,opt,name=recall_tag,json=recallTag,proto3" json:"recall_tag,omitempty"`                                                  // 召回标签（Redis key）
	Priority      int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`                                                                    // 优先级
	Extra         map[string]string      `protobuf:"bytes,6,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 额外信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecallItem) Reset() {
	*x = RecallItem{}
	mi := &file_recall_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecallItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecallItem) ProtoMessage() {}

func (x *RecallItem) ProtoReflect() protoreflect.Message {
	mi := &file_recall_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecallItem.ProtoReflect.Descriptor instead.
func (*RecallItem) Descriptor() ([]byte, []int) {
	return file_recall_proto_rawDescGZIP(), []int{3}
}

func (x *RecallItem) GetAvid() int64 {
	if x != nil {
		return x.Avid
	}
	return 0
}

func (x *RecallItem) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RecallItem) GetRecallType() string {
	if x != nil {
		return x.RecallType
	}
	return ""
}

func (x *RecallItem) GetRecallTag() string {
	if x != nil {
		return x.RecallTag
	}
	return ""
}

func (x *RecallItem) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *RecallItem) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

// 视频索引查询请求
type VideoIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Avids         []int64                `protobuf:"varint,1,rep,packed,name=avids,proto3" json:"avids,omitempty"` // 视频AV号列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoIndexRequest) Reset() {
	*x = VideoIndexRequest{}
	mi := &file_recall_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoIndexRequest) ProtoMessage() {}

func (x *VideoIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recall_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoIndexRequest.ProtoReflect.Descriptor instead.
func (*VideoIndexRequest) Descriptor() ([]byte, []int) {
	return file_recall_proto_rawDescGZIP(), []int{4}
}

func (x *VideoIndexRequest) GetAvids() []int64 {
	if x != nil {
		return x.Avids
	}
	return nil
}

// 视频索引查询响应
type VideoIndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*VideoIndex          `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"` // 视频索引列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoIndexResponse) Reset() {
	*x = VideoIndexResponse{}
	mi := &file_recall_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoIndexResponse) ProtoMessage() {}

func (x *VideoIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recall_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoIndexResponse.ProtoReflect.Descriptor instead.
func (*VideoIndexResponse) Descriptor() ([]byte, []int) {
	return file_recall_proto_rawDescGZIP(), []int{5}
}

func (x *VideoIndexResponse) GetList() []*VideoIndex {
	if x != nil {
		return x.List
	}
	return nil
}

// 视频索引
type VideoIndex struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Avid          int64                  `protobuf:"varint,1,opt,name=avid,proto3" json:"avid,omitempty"`                           // 视频AV号
	BasicInfo     *BasicInfo             `protobuf:"bytes,2,opt,name=basic_info,json=basicInfo,proto3" json:"basic_info,omitempty"` // 基本信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoIndex) Reset() {
	*x = VideoIndex{}
	mi := &file_recall_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoIndex) ProtoMessage() {}

func (x *VideoIndex) ProtoReflect() protoreflect.Message {
	mi := &file_recall_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoIndex.ProtoReflect.Descriptor instead.
func (*VideoIndex) Descriptor() ([]byte, []int) {
	return file_recall_proto_rawDescGZIP(), []int{6}
}

func (x *VideoIndex) GetAvid() int64 {
	if x != nil {
		return x.Avid
	}
	return 0
}

func (x *VideoIndex) GetBasicInfo() *BasicInfo {
	if x != nil {
		return x.BasicInfo
	}
	return nil
}

// 视频基本信息
type BasicInfo struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Avid     int64                  `protobuf:"varint,1,opt,name=avid,proto3" json:"avid,omitempty"`                      // 视频AV号
	Mid      int64                  `protobuf:"varint,2,opt,name=mid,proto3" json:"mid,omitempty"`                        // UP主MID
	Title    string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`                     // 标题
	ZoneId   int32                  `protobuf:"varint,4,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`    // 分区ID
	Duration int32                  `protobuf:"varint,5,opt,name=duration,proto3" json:"duration,omitempty"`              // 时长
	PubTime  int64                  `protobuf:"varint,6,opt,name=pub_time,json=pubTime,proto3" json:"pub_time,omitempty"` // 发布时间
	State    int32                  `protobuf:"varint,7,opt,name=state,proto3" json:"state,omitempty"`                    // 状态
	Tags     []*Tag                 `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`                       // 标签列表
	// 全站统计
	PlayHive  int64 `protobuf:"varint,9,opt,name=play_hive,json=playHive,proto3" json:"play_hive,omitempty"`     // 全站播放量
	LikesHive int64 `protobuf:"varint,10,opt,name=likes_hive,json=likesHive,proto3" json:"likes_hive,omitempty"` // 全站点赞数
	FavHive   int64 `protobuf:"varint,11,opt,name=fav_hive,json=favHive,proto3" json:"fav_hive,omitempty"`       // 全站收藏数
	ReplyHive int64 `protobuf:"varint,12,opt,name=reply_hive,json=replyHive,proto3" json:"reply_hive,omitempty"` // 全站评论数
	ShareHive int64 `protobuf:"varint,13,opt,name=share_hive,json=shareHive,proto3" json:"share_hive,omitempty"` // 全站分享数
	CoinHive  int64 `protobuf:"varint,14,opt,name=coin_hive,json=coinHive,proto3" json:"coin_hive,omitempty"`    // 全站投币数
	// 月度统计
	PlayMonth       int64 `protobuf:"varint,15,opt,name=play_month,json=playMonth,proto3" json:"play_month,omitempty"`                     // 近30天播放量
	LikesMonth      int64 `protobuf:"varint,16,opt,name=likes_month,json=likesMonth,proto3" json:"likes_month,omitempty"`                  // 近30天点赞数
	ReplyMonth      int64 `protobuf:"varint,17,opt,name=reply_month,json=replyMonth,proto3" json:"reply_month,omitempty"`                  // 近30天评论数
	ShareMonth      int64 `protobuf:"varint,18,opt,name=share_month,json=shareMonth,proto3" json:"share_month,omitempty"`                  // 近30天分享数
	PlayMonthFinish int64 `protobuf:"varint,19,opt,name=play_month_finish,json=playMonthFinish,proto3" json:"play_month_finish,omitempty"` // 近30天完播量
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BasicInfo) Reset() {
	*x = BasicInfo{}
	mi := &file_recall_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicInfo) ProtoMessage() {}

func (x *BasicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_recall_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicInfo.ProtoReflect.Descriptor instead.
func (*BasicInfo) Descriptor() ([]byte, []int) {
	return file_recall_proto_rawDescGZIP(), []int{7}
}

func (x *BasicInfo) GetAvid() int64 {
	if x != nil {
		return x.Avid
	}
	return 0
}

func (x *BasicInfo) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *BasicInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BasicInfo) GetZoneId() int32 {
	if x != nil {
		return x.ZoneId
	}
	return 0
}

func (x *BasicInfo) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *BasicInfo) GetPubTime() int64 {
	if x != nil {
		return x.PubTime
	}
	return 0
}

func (x *BasicInfo) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *BasicInfo) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *BasicInfo) GetPlayHive() int64 {
	if x != nil {
		return x.PlayHive
	}
	return 0
}

func (x *BasicInfo) GetLikesHive() int64 {
	if x != nil {
		return x.LikesHive
	}
	return 0
}

func (x *BasicInfo) GetFavHive() int64 {
	if x != nil {
		return x.FavHive
	}
	return 0
}

func (x *BasicInfo) GetReplyHive() int64 {
	if x != nil {
		return x.ReplyHive
	}
	return 0
}

func (x *BasicInfo) GetShareHive() int64 {
	if x != nil {
		return x.ShareHive
	}
	return 0
}

func (x *BasicInfo) GetCoinHive() int64 {
	if x != nil {
		return x.CoinHive
	}
	return 0
}

func (x *BasicInfo) GetPlayMonth() int64 {
	if x != nil {
		return x.PlayMonth
	}
	return 0
}

func (x *BasicInfo) GetLikesMonth() int64 {
	if x != nil {
		return x.LikesMonth
	}
	return 0
}

func (x *BasicInfo) GetReplyMonth() int64 {
	if x != nil {
		return x.ReplyMonth
	}
	return 0
}

func (x *BasicInfo) GetShareMonth() int64 {
	if x != nil {
		return x.ShareMonth
	}
	return 0
}

func (x *BasicInfo) GetPlayMonthFinish() int64 {
	if x != nil {
		return x.PlayMonthFinish
	}
	return 0
}

// 标签
type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagId         int64                  `protobuf:"varint,1,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`       // 标签ID
	TagName       string                 `protobuf:"bytes,2,opt,name=tag_name,json=tagName,proto3" json:"tag_name,omitempty"`  // 标签名称
	TagType       int32                  `protobuf:"varint,3,opt,name=tag_type,json=tagType,proto3" json:"tag_type,omitempty"` // 标签类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_recall_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_recall_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_recall_proto_rawDescGZIP(), []int{8}
}

func (x *Tag) GetTagId() int64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *Tag) GetTagName() string {
	if x != nil {
		return x.TagName
	}
	return ""
}

func (x *Tag) GetTagType() int32 {
	if x != nil {
		return x.TagType
	}
	return 0
}

var File_recall_proto protoreflect.FileDescriptor

const file_recall_proto_rawDesc = "" +
	"\n" +
	"\frecall.proto\x12\x06recall\"\x9d\x01\n" +
	"\rRecallRequest\x12\x10\n" +
	"\x03mid\x18\x01 \x01(\x03R\x03mid\x12\x14\n" +
	"\x05buvid\x18\x02 \x01(\tR\x05buvid\x12\x1f\n" +
	"\vtotal_limit\x18\x03 \x01(\x05R\n" +
	"totalLimit\x12(\n" +
	"\x05infos\x18\x04 \x03(\v2\x12.recall.RecallInfoR\x05infos\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\"\x94\x01\n" +
	"\n" +
	"RecallInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06filter\x18\x04 \x01(\tR\x06filter\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12\x16\n" +
	"\x06scorer\x18\x06 \x01(\tR\x06scorer\"\xd2\x01\n" +
	"\x0eRecallResponse\x12&\n" +
	"\x04list\x18\x01 \x03(\v2\x12.recall.RecallItemR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12D\n" +
	"\n" +
	"debug_info\x18\x03 \x03(\v2%.recall.RecallResponse.DebugInfoEntryR\tdebugInfo\x1a<\n" +
	"\x0eDebugInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x81\x02\n" +
	"\n" +
	"RecallItem\x12\x12\n" +
	"\x04avid\x18\x01 \x01(\x03R\x04avid\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12\x1f\n" +
	"\vrecall_type\x18\x03 \x01(\tR\n" +
	"recallType\x12\x1d\n" +
	"\n" +
	"recall_tag\x18\x04 \x01(\tR\trecallTag\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x123\n" +
	"\x05extra\x18\x06 \x03(\v2\x1d.recall.RecallItem.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\")\n" +
	"\x11VideoIndexRequest\x12\x14\n" +
	"\x05avids\x18\x01 \x03(\x03R\x05avids\"<\n" +
	"\x12VideoIndexResponse\x12&\n" +
	"\x04list\x18\x01 \x03(\v2\x12.recall.VideoIndexR\x04list\"R\n" +
	"\n" +
	"VideoIndex\x12\x12\n" +
	"\x04avid\x18\x01 \x01(\x03R\x04avid\x120\n" +
	"\n" +
	"basic_info\x18\x02 \x01(\v2\x11.recall.BasicInfoR\tbasicInfo\"\xae\x04\n" +
	"\tBasicInfo\x12\x12\n" +
	"\x04avid\x18\x01 \x01(\x03R\x04avid\x12\x10\n" +
	"\x03mid\x18\x02 \x01(\x03R\x03mid\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x17\n" +
	"\azone_id\x18\x04 \x01(\x05R\x06zoneId\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\x05R\bduration\x12\x19\n" +
	"\bpub_time\x18\x06 \x01(\x03R\apubTime\x12\x14\n" +
	"\x05state\x18\a \x01(\x05R\x05state\x12\x1f\n" +
	"\x04tags\x18\b \x03(\v2\v.recall.TagR\x04tags\x12\x1b\n" +
	"\tplay_hive\x18\t \x01(\x03R\bplayHive\x12\x1d\n" +
	"\n" +
	"likes_hive\x18\n" +
	" \x01(\x03R\tlikesHive\x12\x19\n" +
	"\bfav_hive\x18\v \x01(\x03R\afavHive\x12\x1d\n" +
	"\n" +
	"reply_hive\x18\f \x01(\x03R\treplyHive\x12\x1d\n" +
	"\n" +
	"share_hive\x18\r \x01(\x03R\tshareHive\x12\x1b\n" +
	"\tcoin_hive\x18\x0e \x01(\x03R\bcoinHive\x12\x1d\n" +
	"\n" +
	"play_month\x18\x0f \x01(\x03R\tplayMonth\x12\x1f\n" +
	"\vlikes_month\x18\x10 \x01(\x03R\n" +
	"likesMonth\x12\x1f\n" +
	"\vreply_month\x18\x11 \x01(\x03R\n" +
	"replyMonth\x12\x1f\n" +
	"\vshare_month\x18\x12 \x01(\x03R\n" +
	"shareMonth\x12*\n" +
	"\x11play_month_finish\x18\x13 \x01(\x03R\x0fplayMonthFinish\"R\n" +
	"\x03Tag\x12\x15\n" +
	"\x06tag_id\x18\x01 \x01(\x03R\x05tagId\x12\x19\n" +
	"\btag_name\x18\x02 \x01(\tR\atagName\x12\x19\n" +
	"\btag_type\x18\x03 \x01(\x05R\atagType2\x86\x01\n" +
	"\x06Recall\x127\n" +
	"\x06Recall\x12\x15.recall.RecallRequest\x1a\x16.recall.RecallResponse\x12C\n" +
	"\n" +
	"VideoIndex\x12\x19.recall.VideoIndexRequest\x1a\x1a.recall.VideoIndexResponseB\n" +
	"Z\b./recallb\x06proto3"

var (
	file_recall_proto_rawDescOnce sync.Once
	file_recall_proto_rawDescData []byte
)

func file_recall_proto_rawDescGZIP() []byte {
	file_recall_proto_rawDescOnce.Do(func() {
		file_recall_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recall_proto_rawDesc), len(file_recall_proto_rawDesc)))
	})
	return file_recall_proto_rawDescData
}

var file_recall_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_recall_proto_goTypes = []any{
	(*RecallRequest)(nil),      // 0: recall.RecallRequest
	(*RecallInfo)(nil),         // 1: recall.RecallInfo
	(*RecallResponse)(nil),     // 2: recall.RecallResponse
	(*RecallItem)(nil),         // 3: recall.RecallItem
	(*VideoIndexRequest)(nil),  // 4: recall.VideoIndexRequest
	(*VideoIndexResponse)(nil), // 5: recall.VideoIndexResponse
	(*VideoIndex)(nil),         // 6: recall.VideoIndex
	(*BasicInfo)(nil),          // 7: recall.BasicInfo
	(*Tag)(nil),                // 8: recall.Tag
	nil,                        // 9: recall.RecallResponse.DebugInfoEntry
	nil,                        // 10: recall.RecallItem.ExtraEntry
}
var file_recall_proto_depIdxs = []int32{
	1,  // 0: recall.RecallRequest.infos:type_name -> recall.RecallInfo
	3,  // 1: recall.RecallResponse.list:type_name -> recall.RecallItem
	9,  // 2: recall.RecallResponse.debug_info:type_name -> recall.RecallResponse.DebugInfoEntry
	10, // 3: recall.RecallItem.extra:type_name -> recall.RecallItem.ExtraEntry
	6,  // 4: recall.VideoIndexResponse.list:type_name -> recall.VideoIndex
	7,  // 5: recall.VideoIndex.basic_info:type_name -> recall.BasicInfo
	8,  // 6: recall.BasicInfo.tags:type_name -> recall.Tag
	0,  // 7: recall.Recall.Recall:input_type -> recall.RecallRequest
	4,  // 8: recall.Recall.VideoIndex:input_type -> recall.VideoIndexRequest
	2,  // 9: recall.Recall.Recall:output_type -> recall.RecallResponse
	5,  // 10: recall.Recall.VideoIndex:output_type -> recall.VideoIndexResponse
	9,  // [9:11] is the sub-list for method output_type
	7,  // [7:9] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_recall_proto_init() }
func file_recall_proto_init() {
	if File_recall_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recall_proto_rawDesc), len(file_recall_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recall_proto_goTypes,
		DependencyIndexes: file_recall_proto_depIdxs,
		MessageInfos:      file_recall_proto_msgTypes,
	}.Build()
	File_recall_proto = out.File
	file_recall_proto_goTypes = nil
	file_recall_proto_depIdxs = nil
}
