// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: recall.proto

package recall

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Recall_Recall_FullMethodName     = "/recall.Recall/Recall"
	Recall_VideoIndex_FullMethodName = "/recall.Recall/VideoIndex"
)

// RecallClient is the client API for Recall service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 召回服务
type RecallClient interface {
	// 召回接口
	Recall(ctx context.Context, in *RecallRequest, opts ...grpc.CallOption) (*RecallResponse, error)
	// 视频索引查询
	VideoIndex(ctx context.Context, in *VideoIndexRequest, opts ...grpc.CallOption) (*VideoIndexResponse, error)
}

type recallClient struct {
	cc grpc.ClientConnInterface
}

func NewRecallClient(cc grpc.ClientConnInterface) RecallClient {
	return &recallClient{cc}
}

func (c *recallClient) Recall(ctx context.Context, in *RecallRequest, opts ...grpc.CallOption) (*RecallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecallResponse)
	err := c.cc.Invoke(ctx, Recall_Recall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recallClient) VideoIndex(ctx context.Context, in *VideoIndexRequest, opts ...grpc.CallOption) (*VideoIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VideoIndexResponse)
	err := c.cc.Invoke(ctx, Recall_VideoIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecallServer is the server API for Recall service.
// All implementations must embed UnimplementedRecallServer
// for forward compatibility.
//
// 召回服务
type RecallServer interface {
	// 召回接口
	Recall(context.Context, *RecallRequest) (*RecallResponse, error)
	// 视频索引查询
	VideoIndex(context.Context, *VideoIndexRequest) (*VideoIndexResponse, error)
	mustEmbedUnimplementedRecallServer()
}

// UnimplementedRecallServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecallServer struct{}

func (UnimplementedRecallServer) Recall(context.Context, *RecallRequest) (*RecallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Recall not implemented")
}
func (UnimplementedRecallServer) VideoIndex(context.Context, *VideoIndexRequest) (*VideoIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VideoIndex not implemented")
}
func (UnimplementedRecallServer) mustEmbedUnimplementedRecallServer() {}
func (UnimplementedRecallServer) testEmbeddedByValue()                {}

// UnsafeRecallServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecallServer will
// result in compilation errors.
type UnsafeRecallServer interface {
	mustEmbedUnimplementedRecallServer()
}

func RegisterRecallServer(s grpc.ServiceRegistrar, srv RecallServer) {
	// If the following call pancis, it indicates UnimplementedRecallServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Recall_ServiceDesc, srv)
}

func _Recall_Recall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecallServer).Recall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Recall_Recall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecallServer).Recall(ctx, req.(*RecallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Recall_VideoIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VideoIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecallServer).VideoIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Recall_VideoIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecallServer).VideoIndex(ctx, req.(*VideoIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Recall_ServiceDesc is the grpc.ServiceDesc for Recall service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Recall_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "recall.Recall",
	HandlerType: (*RecallServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Recall",
			Handler:    _Recall_Recall_Handler,
		},
		{
			MethodName: "VideoIndex",
			Handler:    _Recall_VideoIndex_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recall.proto",
}
