// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: coupon.proto

package coupon_client

import (
	"context"

	"mybilibili/app/coupon/cmd/rpc/coupon"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AllowanceCouponNotifyReq    = coupon.AllowanceCouponNotifyReq
	AllowanceCouponNotifyResp   = coupon.AllowanceCouponNotifyResp
	AllowanceInfoReq            = coupon.AllowanceInfoReq
	AllowanceInfoResp           = coupon.AllowanceInfoResp
	AllowanceListReq            = coupon.AllowanceListReq
	AllowanceListResp           = coupon.AllowanceListResp
	BatchInfoReq                = coupon.BatchInfoReq
	BatchInfoResp               = coupon.BatchInfoResp
	CancelAllowanceCouponReq    = coupon.CancelAllowanceCouponReq
	CancelAllowanceCouponResp   = coupon.CancelAllowanceCouponResp
	CaptchaTokenReq             = coupon.CaptchaTokenReq
	CaptchaTokenResp            = coupon.CaptchaTokenResp
	CouponAllowancePanelInfo    = coupon.CouponAllowancePanelInfo
	CouponInfo                  = coupon.CouponInfo
	CouponInfoReq               = coupon.CouponInfoReq
	CouponInfoResp              = coupon.CouponInfoResp
	CouponPageItem              = coupon.CouponPageItem
	CouponPageReq               = coupon.CouponPageReq
	CouponPageResp              = coupon.CouponPageResp
	PriceInfo                   = coupon.PriceInfo
	ReceiveAllowanceReq         = coupon.ReceiveAllowanceReq
	ReceiveAllowanceResp        = coupon.ReceiveAllowanceResp
	SalaryCouponForThirdReq     = coupon.SalaryCouponForThirdReq
	SalaryCouponForThirdResp    = coupon.SalaryCouponForThirdResp
	SalaryCouponReq             = coupon.SalaryCouponReq
	SalaryCouponResp            = coupon.SalaryCouponResp
	UsableAllowanceCouponV2Req  = coupon.UsableAllowanceCouponV2Req
	UsableAllowanceCouponV2Resp = coupon.UsableAllowanceCouponV2Resp
	UseAllowanceCouponReq       = coupon.UseAllowanceCouponReq
	UseAllowanceCouponResp      = coupon.UseAllowanceCouponResp
	UseCouponCodeReq            = coupon.UseCouponCodeReq
	UseCouponCodeResp           = coupon.UseCouponCodeResp
	UseCouponReq                = coupon.UseCouponReq
	UseCouponResp               = coupon.UseCouponResp
	UseNotifyReq                = coupon.UseNotifyReq
	UseNotifyResp               = coupon.UseNotifyResp
	UserCouponReq               = coupon.UserCouponReq
	UserCouponResp              = coupon.UserCouponResp
	VideoCouponCountReq         = coupon.VideoCouponCountReq
	VideoCouponCountResp        = coupon.VideoCouponCountResp

	Coupon interface {
		// ========== 验证码相关 ==========
		CaptchaToken(ctx context.Context, in *CaptchaTokenReq, opts ...grpc.CallOption) (*CaptchaTokenResp, error)
		// ========== 兑换码相关 ==========
		UseCouponCode(ctx context.Context, in *UseCouponCodeReq, opts ...grpc.CallOption) (*UseCouponCodeResp, error)
		// ========== 代金券相关 ==========
		UsableAllowanceCouponV2(ctx context.Context, in *UsableAllowanceCouponV2Req, opts ...grpc.CallOption) (*UsableAllowanceCouponV2Resp, error)
		// 使用代金券
		UseAllowanceCoupon(ctx context.Context, in *UseAllowanceCouponReq, opts ...grpc.CallOption) (*UseAllowanceCouponResp, error)
		// 取消使用代金券
		CancelAllowanceCoupon(ctx context.Context, in *CancelAllowanceCouponReq, opts ...grpc.CallOption) (*CancelAllowanceCouponResp, error)
		// 代金券使用通知（支付结果回调）
		AllowanceCouponNotify(ctx context.Context, in *AllowanceCouponNotifyReq, opts ...grpc.CallOption) (*AllowanceCouponNotifyResp, error)
		// 代金券列表
		AllowanceList(ctx context.Context, in *AllowanceListReq, opts ...grpc.CallOption) (*AllowanceListResp, error)
		// 代金券详情
		AllowanceInfo(ctx context.Context, in *AllowanceInfoReq, opts ...grpc.CallOption) (*AllowanceInfoResp, error)
		// 领取代金券
		ReceiveAllowance(ctx context.Context, in *ReceiveAllowanceReq, opts ...grpc.CallOption) (*ReceiveAllowanceResp, error)
		// 同步检查代金券是否可用
		UseNotify(ctx context.Context, in *UseNotifyReq, opts ...grpc.CallOption) (*UseNotifyResp, error)
		// ========== 观影券相关 ==========
		UserCoupon(ctx context.Context, in *UserCouponReq, opts ...grpc.CallOption) (*UserCouponResp, error)
		// 使用观影券
		UseCoupon(ctx context.Context, in *UseCouponReq, opts ...grpc.CallOption) (*UseCouponResp, error)
		// 观影券详情
		CouponInfo(ctx context.Context, in *CouponInfoReq, opts ...grpc.CallOption) (*CouponInfoResp, error)
		// 观影券分页列表
		CouponPage(ctx context.Context, in *CouponPageReq, opts ...grpc.CallOption) (*CouponPageResp, error)
		// 观影券数量
		VideoCouponCount(ctx context.Context, in *VideoCouponCountReq, opts ...grpc.CallOption) (*VideoCouponCountResp, error)
		// ========== 发放相关 ==========
		SalaryCoupon(ctx context.Context, in *SalaryCouponReq, opts ...grpc.CallOption) (*SalaryCouponResp, error)
		// 第三方发放优惠券
		SalaryCouponForThird(ctx context.Context, in *SalaryCouponForThirdReq, opts ...grpc.CallOption) (*SalaryCouponForThirdResp, error)
		// ========== 批次相关 ==========
		BatchInfo(ctx context.Context, in *BatchInfoReq, opts ...grpc.CallOption) (*BatchInfoResp, error)
	}

	defaultCoupon struct {
		cli zrpc.Client
	}
)

func NewCoupon(cli zrpc.Client) Coupon {
	return &defaultCoupon{
		cli: cli,
	}
}

// ========== 验证码相关 ==========
func (m *defaultCoupon) CaptchaToken(ctx context.Context, in *CaptchaTokenReq, opts ...grpc.CallOption) (*CaptchaTokenResp, error) {
	client := coupon.NewCouponClient(m.cli.Conn())
	return client.CaptchaToken(ctx, in, opts...)
}

// ========== 兑换码相关 ==========
func (m *defaultCoupon) UseCouponCode(ctx context.Context, in *UseCouponCodeReq, opts ...grpc.CallOption) (*UseCouponCodeResp, error) {
	client := coupon.NewCouponClient(m.cli.Conn())
	return client.UseCouponCode(ctx, in, opts...)
}

// ========== 代金券相关 ==========
func (m *defaultCoupon) UsableAllowanceCouponV2(ctx context.Context, in *UsableAllowanceCouponV2Req, opts ...grpc.CallOption) (*UsableAllowanceCouponV2Resp, error) {
	client := coupon.NewCouponClient(m.cli.Conn())
	return client.UsableAllowanceCouponV2(ctx, in, opts...)
}

// 使用代金券
func (m *defaultCoupon) UseAllowanceCoupon(ctx context.Context, in *UseAllowanceCouponReq, opts ...grpc.CallOption) (*UseAllowanceCouponResp, error) {
	client := coupon.NewCouponClient(m.cli.Conn())
	return client.UseAllowanceCoupon(ctx, in, opts...)
}

// 取消使用代金券
func (m *defaultCoupon) CancelAllowanceCoupon(ctx context.Context, in *CancelAllowanceCouponReq, opts ...grpc.CallOption) (*CancelAllowanceCouponResp, error) {
	client := coupon.NewCouponClient(m.cli.Conn())
	return client.CancelAllowanceCoupon(ctx, in, opts...)
}

// 代金券使用通知（支付结果回调）
func (m *defaultCoupon) AllowanceCouponNotify(ctx context.Context, in *AllowanceCouponNotifyReq, opts ...grpc.CallOption) (*AllowanceCouponNotifyResp, error) {
	client := coupon.NewCouponClient(m.cli.Conn())
	return client.AllowanceCouponNotify(ctx, in, opts...)
}

// 代金券列表
func (m *defaultCoupon) AllowanceList(ctx context.Context, in *AllowanceListReq, opts ...grpc.CallOption) (*AllowanceListResp, error) {
	client := coupon.NewCouponClient(m.cli.Conn())
	return client.AllowanceList(ctx, in, opts...)
}

// 代金券详情
func (m *defaultCoupon) AllowanceInfo(ctx context.Context, in *AllowanceInfoReq, opts ...grpc.CallOption) (*AllowanceInfoResp, error) {
	client := coupon.NewCouponClient(m.cli.Conn())
	return client.AllowanceInfo(ctx, in, opts...)
}

// 领取代金券
func (m *defaultCoupon) ReceiveAllowance(ctx context.Context, in *ReceiveAllowanceReq, opts ...grpc.CallOption) (*ReceiveAllowanceResp, error) {
	client := coupon.NewCouponClient(m.cli.Conn())
	return client.ReceiveAllowance(ctx, in, opts...)
}

// 同步检查代金券是否可用
func (m *defaultCoupon) UseNotify(ctx context.Context, in *UseNotifyReq, opts ...grpc.CallOption) (*UseNotifyResp, error) {
	client := coupon.NewCouponClient(m.cli.Conn())
	return client.UseNotify(ctx, in, opts...)
}

// ========== 观影券相关 ==========
func (m *defaultCoupon) UserCoupon(ctx context.Context, in *UserCouponReq, opts ...grpc.CallOption) (*UserCouponResp, error) {
	client := coupon.NewCouponClient(m.cli.Conn())
	return client.UserCoupon(ctx, in, opts...)
}

// 使用观影券
func (m *defaultCoupon) UseCoupon(ctx context.Context, in *UseCouponReq, opts ...grpc.CallOption) (*UseCouponResp, error) {
	client := coupon.NewCouponClient(m.cli.Conn())
	return client.UseCoupon(ctx, in, opts...)
}

// 观影券详情
func (m *defaultCoupon) CouponInfo(ctx context.Context, in *CouponInfoReq, opts ...grpc.CallOption) (*CouponInfoResp, error) {
	client := coupon.NewCouponClient(m.cli.Conn())
	return client.CouponInfo(ctx, in, opts...)
}

// 观影券分页列表
func (m *defaultCoupon) CouponPage(ctx context.Context, in *CouponPageReq, opts ...grpc.CallOption) (*CouponPageResp, error) {
	client := coupon.NewCouponClient(m.cli.Conn())
	return client.CouponPage(ctx, in, opts...)
}

// 观影券数量
func (m *defaultCoupon) VideoCouponCount(ctx context.Context, in *VideoCouponCountReq, opts ...grpc.CallOption) (*VideoCouponCountResp, error) {
	client := coupon.NewCouponClient(m.cli.Conn())
	return client.VideoCouponCount(ctx, in, opts...)
}

// ========== 发放相关 ==========
func (m *defaultCoupon) SalaryCoupon(ctx context.Context, in *SalaryCouponReq, opts ...grpc.CallOption) (*SalaryCouponResp, error) {
	client := coupon.NewCouponClient(m.cli.Conn())
	return client.SalaryCoupon(ctx, in, opts...)
}

// 第三方发放优惠券
func (m *defaultCoupon) SalaryCouponForThird(ctx context.Context, in *SalaryCouponForThirdReq, opts ...grpc.CallOption) (*SalaryCouponForThirdResp, error) {
	client := coupon.NewCouponClient(m.cli.Conn())
	return client.SalaryCouponForThird(ctx, in, opts...)
}

// ========== 批次相关 ==========
func (m *defaultCoupon) BatchInfo(ctx context.Context, in *BatchInfoReq, opts ...grpc.CallOption) (*BatchInfoResp, error) {
	client := coupon.NewCouponClient(m.cli.Conn())
	return client.BatchInfo(ctx, in, opts...)
}
