// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: video.proto

package server

import (
	"context"

	"mybilibili/app/video/cmd/rpc/internal/logic"
	"mybilibili/app/video/cmd/rpc/internal/svc"
	"mybilibili/app/video/cmd/rpc/video"
)

type VideoServer struct {
	svcCtx *svc.ServiceContext
	video.UnimplementedVideoServer
}

func NewVideoServer(svcCtx *svc.ServiceContext) *VideoServer {
	return &VideoServer{
		svcCtx: svcCtx,
	}
}

// 获取视频信息
func (s *VideoServer) GetVideoInfo(ctx context.Context, in *video.GetVideoInfoReq) (*video.GetVideoInfoResp, error) {
	l := logic.NewGetVideoInfoLogic(ctx, s.svcCtx)
	return l.GetVideoInfo(in)
}

// 批量获取视频信息
func (s *VideoServer) BatchGetVideoInfo(ctx context.Context, in *video.BatchGetVideoInfoReq) (*video.BatchGetVideoInfoResp, error) {
	l := logic.NewBatchGetVideoInfoLogic(ctx, s.svcCtx)
	return l.BatchGetVideoInfo(in)
}

// 获取视频列表（游标分页）
func (s *VideoServer) GetVideoList(ctx context.Context, in *video.GetVideoListReq) (*video.GetVideoListResp, error) {
	l := logic.NewGetVideoListLogic(ctx, s.svcCtx)
	return l.GetVideoList(in)
}

// 获取视频统计数据
func (s *VideoServer) GetVideoStat(ctx context.Context, in *video.GetVideoStatReq) (*video.GetVideoStatResp, error) {
	l := logic.NewGetVideoStatLogic(ctx, s.svcCtx)
	return l.GetVideoStat(in)
}

// 批量获取视频统计数据
func (s *VideoServer) BatchGetVideoStat(ctx context.Context, in *video.BatchGetVideoStatReq) (*video.BatchGetVideoStatResp, error) {
	l := logic.NewBatchGetVideoStatLogic(ctx, s.svcCtx)
	return l.BatchGetVideoStat(in)
}
