// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: recommend.proto

package server

import (
	"context"

	"mybilibili/app/recommend/cmd/rpc/internal/logic"
	"mybilibili/app/recommend/cmd/rpc/internal/svc"
	"mybilibili/app/recommend/cmd/rpc/recommend"
)

type RecommendServer struct {
	svcCtx *svc.ServiceContext
	recommend.UnimplementedRecommendServer
}

func NewRecommendServer(svcCtx *svc.ServiceContext) *RecommendServer {
	return &RecommendServer{
		svcCtx: svcCtx,
	}
}

// 获取推荐列表
func (s *RecommendServer) GetRecommendList(ctx context.Context, in *recommend.RecommendRequest) (*recommend.RecommendResponse, error) {
	l := logic.NewGetRecommendListLogic(ctx, s.svcCtx)
	return l.GetRecommendList(in)
}
