// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: recall.proto

package recall_client

import (
	"context"

	"mybilibili/app/recall/cmd/rpc/recall"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BasicInfo          = recall.BasicInfo
	RecallInfo         = recall.RecallInfo
	RecallItem         = recall.RecallItem
	RecallRequest      = recall.RecallRequest
	RecallResponse     = recall.RecallResponse
	Tag                = recall.Tag
	VideoIndex         = recall.VideoIndex
	VideoIndexRequest  = recall.VideoIndexRequest
	VideoIndexResponse = recall.VideoIndexResponse

	Recall interface {
		// 召回接口
		Recall(ctx context.Context, in *RecallRequest, opts ...grpc.CallOption) (*RecallResponse, error)
		// 视频索引查询
		VideoIndex(ctx context.Context, in *VideoIndexRequest, opts ...grpc.CallOption) (*VideoIndexResponse, error)
	}

	defaultRecall struct {
		cli zrpc.Client
	}
)

func NewRecall(cli zrpc.Client) Recall {
	return &defaultRecall{
		cli: cli,
	}
}

// 召回接口
func (m *defaultRecall) Recall(ctx context.Context, in *RecallRequest, opts ...grpc.CallOption) (*RecallResponse, error) {
	client := recall.NewRecallClient(m.cli.Conn())
	return client.Recall(ctx, in, opts...)
}

// 视频索引查询
func (m *defaultRecall) VideoIndex(ctx context.Context, in *VideoIndexRequest, opts ...grpc.CallOption) (*VideoIndexResponse, error) {
	client := recall.NewRecallClient(m.cli.Conn())
	return client.VideoIndex(ctx, in, opts...)
}
