// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: recall.proto

package server

import (
	"context"

	"mybilibili/app/recall/cmd/rpc/internal/logic"
	"mybilibili/app/recall/cmd/rpc/internal/svc"
	"mybilibili/app/recall/cmd/rpc/recall"
)

type RecallServer struct {
	svcCtx *svc.ServiceContext
	recall.UnimplementedRecallServer
}

func NewRecallServer(svcCtx *svc.ServiceContext) *RecallServer {
	return &RecallServer{
		svcCtx: svcCtx,
	}
}

// 召回接口
func (s *RecallServer) Recall(ctx context.Context, in *recall.RecallRequest) (*recall.RecallResponse, error) {
	l := logic.NewRecallLogic(ctx, s.svcCtx)
	return l.Recall(in)
}

// 视频索引查询
func (s *RecallServer) VideoIndex(ctx context.Context, in *recall.VideoIndexRequest) (*recall.VideoIndexResponse, error) {
	l := logic.NewVideoIndexLogic(ctx, s.svcCtx)
	return l.VideoIndex(in)
}
