// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: hotrank.proto

package server

import (
	"context"

	"mybilibili/app/hotrank/cmd/rpc/hotrank"
	"mybilibili/app/hotrank/cmd/rpc/internal/logic"
	"mybilibili/app/hotrank/cmd/rpc/internal/svc"
)

type HotrankServer struct {
	svcCtx *svc.ServiceContext
	hotrank.UnimplementedHotrankServer
}

func NewHotrankServer(svcCtx *svc.ServiceContext) *HotrankServer {
	return &HotrankServer{
		svcCtx: svcCtx,
	}
}

// 获取全站热门排行榜
func (s *HotrankServer) GetHotRankList(ctx context.Context, in *hotrank.GetHotRankListReq) (*hotrank.GetHotRankListResp, error) {
	l := logic.NewGetHotRankListLogic(ctx, s.svcCtx)
	return l.GetHotRankList(in)
}

// 获取分区热门排行榜
func (s *HotrankServer) GetRegionHotRankList(ctx context.Context, in *hotrank.GetRegionHotRankListReq) (*hotrank.GetRegionHotRankListResp, error) {
	l := logic.NewGetRegionHotRankListLogic(ctx, s.svcCtx)
	return l.GetRegionHotRankList(in)
}

// 获取热度值（根据OID）
func (s *HotrankServer) GetHotByOID(ctx context.Context, in *hotrank.GetHotByOIDReq) (*hotrank.GetHotByOIDResp, error) {
	l := logic.NewGetHotByOIDLogic(ctx, s.svcCtx)
	return l.GetHotByOID(in)
}
