// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: wallet.proto

package server

import (
	"context"

	"mybilibili/app/wallet/cmd/rpc/internal/logic"
	"mybilibili/app/wallet/cmd/rpc/internal/svc"
	"mybilibili/app/wallet/cmd/rpc/wallet"
)

type WalletServer struct {
	svcCtx *svc.ServiceContext
	wallet.UnimplementedWalletServer
}

func NewWalletServer(svcCtx *svc.ServiceContext) *WalletServer {
	return &WalletServer{
		svcCtx: svcCtx,
	}
}

// 充值
func (s *WalletServer) Recharge(ctx context.Context, in *wallet.RechargeReq) (*wallet.RechargeResp, error) {
	l := logic.NewRechargeLogic(ctx, s.svcCtx)
	return l.Recharge(in)
}

// 消费
func (s *WalletServer) Pay(ctx context.Context, in *wallet.PayReq) (*wallet.PayResp, error) {
	l := logic.NewPayLogic(ctx, s.svcCtx)
	return l.Pay(in)
}

// 兑换
func (s *WalletServer) Exchange(ctx context.Context, in *wallet.ExchangeReq) (*wallet.ExchangeResp, error) {
	l := logic.NewExchangeLogic(ctx, s.svcCtx)
	return l.Exchange(in)
}

// 查询余额详情
func (s *WalletServer) GetDetail(ctx context.Context, in *wallet.GetDetailReq) (*wallet.GetDetailResp, error) {
	l := logic.NewGetDetailLogic(ctx, s.svcCtx)
	return l.GetDetail(in)
}

// 查询流水列表
func (s *WalletServer) GetStreamList(ctx context.Context, in *wallet.GetStreamListReq) (*wallet.GetStreamListResp, error) {
	l := logic.NewGetStreamListLogic(ctx, s.svcCtx)
	return l.GetStreamList(in)
}
