// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: search.proto

package search

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Search_DmSearch_FullMethodName          = "/search.Search/DmSearch"
	Search_PgcMediaSearch_FullMethodName    = "/search.Search/PgcMediaSearch"
	Search_ReplyRecordSearch_FullMethodName = "/search.Search/ReplyRecordSearch"
	Search_DmHistorySearch_FullMethodName   = "/search.Search/DmHistorySearch"
	Search_DmDateSearch_FullMethodName      = "/search.Search/DmDateSearch"
	Search_DmUpdate_FullMethodName          = "/search.Search/DmUpdate"
	Search_PgcUpdate_FullMethodName         = "/search.Search/PgcUpdate"
	Search_ReplyUpdate_FullMethodName       = "/search.Search/ReplyUpdate"
)

// SearchClient is the client API for Search service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ==================== 搜索服务 ====================
type SearchClient interface {
	// 弹幕搜索
	DmSearch(ctx context.Context, in *DmSearchReq, opts ...grpc.CallOption) (*SearchResp, error)
	// PGC番剧搜索
	PgcMediaSearch(ctx context.Context, in *PgcMediaSearchReq, opts ...grpc.CallOption) (*SearchResp, error)
	// 评论记录搜索
	ReplyRecordSearch(ctx context.Context, in *ReplyRecordSearchReq, opts ...grpc.CallOption) (*SearchResp, error)
	// 弹幕历史搜索
	DmHistorySearch(ctx context.Context, in *DmHistorySearchReq, opts ...grpc.CallOption) (*SearchResp, error)
	// 弹幕日期搜索
	DmDateSearch(ctx context.Context, in *DmDateSearchReq, opts ...grpc.CallOption) (*SearchResp, error)
	// 弹幕索引更新
	DmUpdate(ctx context.Context, in *DmUpdateReq, opts ...grpc.CallOption) (*UpdateResp, error)
	// PGC索引更新
	PgcUpdate(ctx context.Context, in *PgcUpdateReq, opts ...grpc.CallOption) (*UpdateResp, error)
	// 评论索引更新
	ReplyUpdate(ctx context.Context, in *ReplyUpdateReq, opts ...grpc.CallOption) (*UpdateResp, error)
}

type searchClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchClient(cc grpc.ClientConnInterface) SearchClient {
	return &searchClient{cc}
}

func (c *searchClient) DmSearch(ctx context.Context, in *DmSearchReq, opts ...grpc.CallOption) (*SearchResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResp)
	err := c.cc.Invoke(ctx, Search_DmSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) PgcMediaSearch(ctx context.Context, in *PgcMediaSearchReq, opts ...grpc.CallOption) (*SearchResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResp)
	err := c.cc.Invoke(ctx, Search_PgcMediaSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) ReplyRecordSearch(ctx context.Context, in *ReplyRecordSearchReq, opts ...grpc.CallOption) (*SearchResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResp)
	err := c.cc.Invoke(ctx, Search_ReplyRecordSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) DmHistorySearch(ctx context.Context, in *DmHistorySearchReq, opts ...grpc.CallOption) (*SearchResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResp)
	err := c.cc.Invoke(ctx, Search_DmHistorySearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) DmDateSearch(ctx context.Context, in *DmDateSearchReq, opts ...grpc.CallOption) (*SearchResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResp)
	err := c.cc.Invoke(ctx, Search_DmDateSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) DmUpdate(ctx context.Context, in *DmUpdateReq, opts ...grpc.CallOption) (*UpdateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResp)
	err := c.cc.Invoke(ctx, Search_DmUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) PgcUpdate(ctx context.Context, in *PgcUpdateReq, opts ...grpc.CallOption) (*UpdateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResp)
	err := c.cc.Invoke(ctx, Search_PgcUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) ReplyUpdate(ctx context.Context, in *ReplyUpdateReq, opts ...grpc.CallOption) (*UpdateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResp)
	err := c.cc.Invoke(ctx, Search_ReplyUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchServer is the server API for Search service.
// All implementations must embed UnimplementedSearchServer
// for forward compatibility.
//
// ==================== 搜索服务 ====================
type SearchServer interface {
	// 弹幕搜索
	DmSearch(context.Context, *DmSearchReq) (*SearchResp, error)
	// PGC番剧搜索
	PgcMediaSearch(context.Context, *PgcMediaSearchReq) (*SearchResp, error)
	// 评论记录搜索
	ReplyRecordSearch(context.Context, *ReplyRecordSearchReq) (*SearchResp, error)
	// 弹幕历史搜索
	DmHistorySearch(context.Context, *DmHistorySearchReq) (*SearchResp, error)
	// 弹幕日期搜索
	DmDateSearch(context.Context, *DmDateSearchReq) (*SearchResp, error)
	// 弹幕索引更新
	DmUpdate(context.Context, *DmUpdateReq) (*UpdateResp, error)
	// PGC索引更新
	PgcUpdate(context.Context, *PgcUpdateReq) (*UpdateResp, error)
	// 评论索引更新
	ReplyUpdate(context.Context, *ReplyUpdateReq) (*UpdateResp, error)
	mustEmbedUnimplementedSearchServer()
}

// UnimplementedSearchServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSearchServer struct{}

func (UnimplementedSearchServer) DmSearch(context.Context, *DmSearchReq) (*SearchResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DmSearch not implemented")
}
func (UnimplementedSearchServer) PgcMediaSearch(context.Context, *PgcMediaSearchReq) (*SearchResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PgcMediaSearch not implemented")
}
func (UnimplementedSearchServer) ReplyRecordSearch(context.Context, *ReplyRecordSearchReq) (*SearchResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplyRecordSearch not implemented")
}
func (UnimplementedSearchServer) DmHistorySearch(context.Context, *DmHistorySearchReq) (*SearchResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DmHistorySearch not implemented")
}
func (UnimplementedSearchServer) DmDateSearch(context.Context, *DmDateSearchReq) (*SearchResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DmDateSearch not implemented")
}
func (UnimplementedSearchServer) DmUpdate(context.Context, *DmUpdateReq) (*UpdateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DmUpdate not implemented")
}
func (UnimplementedSearchServer) PgcUpdate(context.Context, *PgcUpdateReq) (*UpdateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PgcUpdate not implemented")
}
func (UnimplementedSearchServer) ReplyUpdate(context.Context, *ReplyUpdateReq) (*UpdateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplyUpdate not implemented")
}
func (UnimplementedSearchServer) mustEmbedUnimplementedSearchServer() {}
func (UnimplementedSearchServer) testEmbeddedByValue()                {}

// UnsafeSearchServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchServer will
// result in compilation errors.
type UnsafeSearchServer interface {
	mustEmbedUnimplementedSearchServer()
}

func RegisterSearchServer(s grpc.ServiceRegistrar, srv SearchServer) {
	// If the following call pancis, it indicates UnimplementedSearchServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Search_ServiceDesc, srv)
}

func _Search_DmSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DmSearchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).DmSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_DmSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).DmSearch(ctx, req.(*DmSearchReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_PgcMediaSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PgcMediaSearchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).PgcMediaSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_PgcMediaSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).PgcMediaSearch(ctx, req.(*PgcMediaSearchReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_ReplyRecordSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplyRecordSearchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).ReplyRecordSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_ReplyRecordSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).ReplyRecordSearch(ctx, req.(*ReplyRecordSearchReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_DmHistorySearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DmHistorySearchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).DmHistorySearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_DmHistorySearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).DmHistorySearch(ctx, req.(*DmHistorySearchReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_DmDateSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DmDateSearchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).DmDateSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_DmDateSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).DmDateSearch(ctx, req.(*DmDateSearchReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_DmUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DmUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).DmUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_DmUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).DmUpdate(ctx, req.(*DmUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_PgcUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PgcUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).PgcUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_PgcUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).PgcUpdate(ctx, req.(*PgcUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_ReplyUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplyUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).ReplyUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_ReplyUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).ReplyUpdate(ctx, req.(*ReplyUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Search_ServiceDesc is the grpc.ServiceDesc for Search service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Search_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "search.Search",
	HandlerType: (*SearchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DmSearch",
			Handler:    _Search_DmSearch_Handler,
		},
		{
			MethodName: "PgcMediaSearch",
			Handler:    _Search_PgcMediaSearch_Handler,
		},
		{
			MethodName: "ReplyRecordSearch",
			Handler:    _Search_ReplyRecordSearch_Handler,
		},
		{
			MethodName: "DmHistorySearch",
			Handler:    _Search_DmHistorySearch_Handler,
		},
		{
			MethodName: "DmDateSearch",
			Handler:    _Search_DmDateSearch_Handler,
		},
		{
			MethodName: "DmUpdate",
			Handler:    _Search_DmUpdate_Handler,
		},
		{
			MethodName: "PgcUpdate",
			Handler:    _Search_PgcUpdate_Handler,
		},
		{
			MethodName: "ReplyUpdate",
			Handler:    _Search_ReplyUpdate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "search.proto",
}
