// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: search.proto

package search

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ==================== 通用搜索参数 ====================
type BasicSearchParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`          // 应用ID
	Kw            string                 `protobuf:"bytes,2,opt,name=kw,proto3" json:"kw,omitempty"`                             // 搜索关键词
	KwFields      []string               `protobuf:"bytes,3,rep,name=kw_fields,json=kwFields,proto3" json:"kw_fields,omitempty"` // 关键词搜索字段
	Order         []string               `protobuf:"bytes,4,rep,name=order,proto3" json:"order,omitempty"`                       // 排序字段
	Sort          []string               `protobuf:"bytes,5,rep,name=sort,proto3" json:"sort,omitempty"`                         // 排序方式 asc/desc
	Pn            int32                  `protobuf:"varint,6,opt,name=pn,proto3" json:"pn,omitempty"`                            // 页码
	Ps            int32                  `protobuf:"varint,7,opt,name=ps,proto3" json:"ps,omitempty"`                            // 每页数量
	Debug         bool                   `protobuf:"varint,8,opt,name=debug,proto3" json:"debug,omitempty"`                      // 调试模式
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasicSearchParams) Reset() {
	*x = BasicSearchParams{}
	mi := &file_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicSearchParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicSearchParams) ProtoMessage() {}

func (x *BasicSearchParams) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicSearchParams.ProtoReflect.Descriptor instead.
func (*BasicSearchParams) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{0}
}

func (x *BasicSearchParams) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *BasicSearchParams) GetKw() string {
	if x != nil {
		return x.Kw
	}
	return ""
}

func (x *BasicSearchParams) GetKwFields() []string {
	if x != nil {
		return x.KwFields
	}
	return nil
}

func (x *BasicSearchParams) GetOrder() []string {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *BasicSearchParams) GetSort() []string {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *BasicSearchParams) GetPn() int32 {
	if x != nil {
		return x.Pn
	}
	return 0
}

func (x *BasicSearchParams) GetPs() int32 {
	if x != nil {
		return x.Ps
	}
	return 0
}

func (x *BasicSearchParams) GetDebug() bool {
	if x != nil {
		return x.Debug
	}
	return false
}

// ==================== 弹幕搜索 ====================
type DmSearchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bsp           *BasicSearchParams     `protobuf:"bytes,1,opt,name=bsp,proto3" json:"bsp,omitempty"`                                         // 基础搜索参数
	Oid           int64                  `protobuf:"varint,2,opt,name=oid,proto3" json:"oid,omitempty"`                                        // 对象ID
	Mid           int64                  `protobuf:"varint,3,opt,name=mid,proto3" json:"mid,omitempty"`                                        // 用户ID
	Mode          int32                  `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"`                                      // 弹幕模式
	Pool          int32                  `protobuf:"varint,5,opt,name=pool,proto3" json:"pool,omitempty"`                                      // 弹幕池
	Progress      int32                  `protobuf:"varint,6,opt,name=progress,proto3" json:"progress,omitempty"`                              // 进度
	States        []int32                `protobuf:"varint,7,rep,packed,name=states,proto3" json:"states,omitempty"`                           // 状态列表
	Type          int32                  `protobuf:"varint,8,opt,name=type,proto3" json:"type,omitempty"`                                      // 类型
	AttrFormat    []int32                `protobuf:"varint,9,rep,packed,name=attr_format,json=attrFormat,proto3" json:"attr_format,omitempty"` // 属性格式
	CtimeFrom     string                 `protobuf:"bytes,10,opt,name=ctime_from,json=ctimeFrom,proto3" json:"ctime_from,omitempty"`           // 创建时间起始
	CtimeTo       string                 `protobuf:"bytes,11,opt,name=ctime_to,json=ctimeTo,proto3" json:"ctime_to,omitempty"`                 // 创建时间结束
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DmSearchReq) Reset() {
	*x = DmSearchReq{}
	mi := &file_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DmSearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DmSearchReq) ProtoMessage() {}

func (x *DmSearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DmSearchReq.ProtoReflect.Descriptor instead.
func (*DmSearchReq) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{1}
}

func (x *DmSearchReq) GetBsp() *BasicSearchParams {
	if x != nil {
		return x.Bsp
	}
	return nil
}

func (x *DmSearchReq) GetOid() int64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

func (x *DmSearchReq) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *DmSearchReq) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *DmSearchReq) GetPool() int32 {
	if x != nil {
		return x.Pool
	}
	return 0
}

func (x *DmSearchReq) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *DmSearchReq) GetStates() []int32 {
	if x != nil {
		return x.States
	}
	return nil
}

func (x *DmSearchReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *DmSearchReq) GetAttrFormat() []int32 {
	if x != nil {
		return x.AttrFormat
	}
	return nil
}

func (x *DmSearchReq) GetCtimeFrom() string {
	if x != nil {
		return x.CtimeFrom
	}
	return ""
}

func (x *DmSearchReq) GetCtimeTo() string {
	if x != nil {
		return x.CtimeTo
	}
	return ""
}

// ==================== PGC番剧搜索 ====================
type PgcMediaSearchReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Bsp             *BasicSearchParams     `protobuf:"bytes,1,opt,name=bsp,proto3" json:"bsp,omitempty"`                                                      // 基础搜索参数
	MediaIds        []int64                `protobuf:"varint,2,rep,packed,name=media_ids,json=mediaIds,proto3" json:"media_ids,omitempty"`                    // 媒体ID列表
	SeasonIds       []int64                `protobuf:"varint,3,rep,packed,name=season_ids,json=seasonIds,proto3" json:"season_ids,omitempty"`                 // 季度ID列表
	SeasonTypes     []int64                `protobuf:"varint,4,rep,packed,name=season_types,json=seasonTypes,proto3" json:"season_types,omitempty"`           // 季度类型列表
	StyleIds        []int64                `protobuf:"varint,5,rep,packed,name=style_ids,json=styleIds,proto3" json:"style_ids,omitempty"`                    // 风格ID列表
	Status          int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`                                               // 状态
	ReleaseDateFrom string                 `protobuf:"bytes,7,opt,name=release_date_from,json=releaseDateFrom,proto3" json:"release_date_from,omitempty"`     // 发布日期起始
	ReleaseDateTo   string                 `protobuf:"bytes,8,opt,name=release_date_to,json=releaseDateTo,proto3" json:"release_date_to,omitempty"`           // 发布日期结束
	SeasonIdFrom    int32                  `protobuf:"varint,9,opt,name=season_id_from,json=seasonIdFrom,proto3" json:"season_id_from,omitempty"`             // 季度ID起始
	SeasonIdTo      int32                  `protobuf:"varint,10,opt,name=season_id_to,json=seasonIdTo,proto3" json:"season_id_to,omitempty"`                  // 季度ID结束
	ProducerIds     []int64                `protobuf:"varint,11,rep,packed,name=producer_ids,json=producerIds,proto3" json:"producer_ids,omitempty"`          // 制作方ID列表
	IsDeleted       int32                  `protobuf:"varint,12,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`                       // 是否删除
	AreaIds         []string               `protobuf:"bytes,13,rep,name=area_ids,json=areaIds,proto3" json:"area_ids,omitempty"`                              // 地区ID列表
	ScoreFrom       int32                  `protobuf:"varint,14,opt,name=score_from,json=scoreFrom,proto3" json:"score_from,omitempty"`                       // 评分起始
	ScoreTo         int32                  `protobuf:"varint,15,opt,name=score_to,json=scoreTo,proto3" json:"score_to,omitempty"`                             // 评分结束
	IsFinish        string                 `protobuf:"bytes,16,opt,name=is_finish,json=isFinish,proto3" json:"is_finish,omitempty"`                           // 是否完结
	SeasonVersions  []int64                `protobuf:"varint,17,rep,packed,name=season_versions,json=seasonVersions,proto3" json:"season_versions,omitempty"` // 季度版本列表
	SeasonStatuses  []int64                `protobuf:"varint,18,rep,packed,name=season_statuses,json=seasonStatuses,proto3" json:"season_statuses,omitempty"` // 季度状态列表
	PubTimeFrom     string                 `protobuf:"bytes,19,opt,name=pub_time_from,json=pubTimeFrom,proto3" json:"pub_time_from,omitempty"`                // 发布时间起始
	PubTimeTo       string                 `protobuf:"bytes,20,opt,name=pub_time_to,json=pubTimeTo,proto3" json:"pub_time_to,omitempty"`                      // 发布时间结束
	SeasonMonths    []int64                `protobuf:"varint,21,rep,packed,name=season_months,json=seasonMonths,proto3" json:"season_months,omitempty"`       // 季度月份列表
	LatestTimeFrom  string                 `protobuf:"bytes,22,opt,name=latest_time_from,json=latestTimeFrom,proto3" json:"latest_time_from,omitempty"`       // 最新时间起始
	LatestTimeTo    string                 `protobuf:"bytes,23,opt,name=latest_time_to,json=latestTimeTo,proto3" json:"latest_time_to,omitempty"`             // 最新时间结束
	CopyrightInfos  []string               `protobuf:"bytes,24,rep,name=copyright_infos,json=copyrightInfos,proto3" json:"copyright_infos,omitempty"`         // 版权信息列表
	CtimeFrom       string                 `protobuf:"bytes,25,opt,name=ctime_from,json=ctimeFrom,proto3" json:"ctime_from,omitempty"`                        // 创建时间起始
	CtimeTo         string                 `protobuf:"bytes,26,opt,name=ctime_to,json=ctimeTo,proto3" json:"ctime_to,omitempty"`                              // 创建时间结束
	MtimeFrom       string                 `protobuf:"bytes,27,opt,name=mtime_from,json=mtimeFrom,proto3" json:"mtime_from,omitempty"`                        // 修改时间起始
	MtimeTo         string                 `protobuf:"bytes,28,opt,name=mtime_to,json=mtimeTo,proto3" json:"mtime_to,omitempty"`                              // 修改时间结束
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PgcMediaSearchReq) Reset() {
	*x = PgcMediaSearchReq{}
	mi := &file_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PgcMediaSearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PgcMediaSearchReq) ProtoMessage() {}

func (x *PgcMediaSearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PgcMediaSearchReq.ProtoReflect.Descriptor instead.
func (*PgcMediaSearchReq) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{2}
}

func (x *PgcMediaSearchReq) GetBsp() *BasicSearchParams {
	if x != nil {
		return x.Bsp
	}
	return nil
}

func (x *PgcMediaSearchReq) GetMediaIds() []int64 {
	if x != nil {
		return x.MediaIds
	}
	return nil
}

func (x *PgcMediaSearchReq) GetSeasonIds() []int64 {
	if x != nil {
		return x.SeasonIds
	}
	return nil
}

func (x *PgcMediaSearchReq) GetSeasonTypes() []int64 {
	if x != nil {
		return x.SeasonTypes
	}
	return nil
}

func (x *PgcMediaSearchReq) GetStyleIds() []int64 {
	if x != nil {
		return x.StyleIds
	}
	return nil
}

func (x *PgcMediaSearchReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PgcMediaSearchReq) GetReleaseDateFrom() string {
	if x != nil {
		return x.ReleaseDateFrom
	}
	return ""
}

func (x *PgcMediaSearchReq) GetReleaseDateTo() string {
	if x != nil {
		return x.ReleaseDateTo
	}
	return ""
}

func (x *PgcMediaSearchReq) GetSeasonIdFrom() int32 {
	if x != nil {
		return x.SeasonIdFrom
	}
	return 0
}

func (x *PgcMediaSearchReq) GetSeasonIdTo() int32 {
	if x != nil {
		return x.SeasonIdTo
	}
	return 0
}

func (x *PgcMediaSearchReq) GetProducerIds() []int64 {
	if x != nil {
		return x.ProducerIds
	}
	return nil
}

func (x *PgcMediaSearchReq) GetIsDeleted() int32 {
	if x != nil {
		return x.IsDeleted
	}
	return 0
}

func (x *PgcMediaSearchReq) GetAreaIds() []string {
	if x != nil {
		return x.AreaIds
	}
	return nil
}

func (x *PgcMediaSearchReq) GetScoreFrom() int32 {
	if x != nil {
		return x.ScoreFrom
	}
	return 0
}

func (x *PgcMediaSearchReq) GetScoreTo() int32 {
	if x != nil {
		return x.ScoreTo
	}
	return 0
}

func (x *PgcMediaSearchReq) GetIsFinish() string {
	if x != nil {
		return x.IsFinish
	}
	return ""
}

func (x *PgcMediaSearchReq) GetSeasonVersions() []int64 {
	if x != nil {
		return x.SeasonVersions
	}
	return nil
}

func (x *PgcMediaSearchReq) GetSeasonStatuses() []int64 {
	if x != nil {
		return x.SeasonStatuses
	}
	return nil
}

func (x *PgcMediaSearchReq) GetPubTimeFrom() string {
	if x != nil {
		return x.PubTimeFrom
	}
	return ""
}

func (x *PgcMediaSearchReq) GetPubTimeTo() string {
	if x != nil {
		return x.PubTimeTo
	}
	return ""
}

func (x *PgcMediaSearchReq) GetSeasonMonths() []int64 {
	if x != nil {
		return x.SeasonMonths
	}
	return nil
}

func (x *PgcMediaSearchReq) GetLatestTimeFrom() string {
	if x != nil {
		return x.LatestTimeFrom
	}
	return ""
}

func (x *PgcMediaSearchReq) GetLatestTimeTo() string {
	if x != nil {
		return x.LatestTimeTo
	}
	return ""
}

func (x *PgcMediaSearchReq) GetCopyrightInfos() []string {
	if x != nil {
		return x.CopyrightInfos
	}
	return nil
}

func (x *PgcMediaSearchReq) GetCtimeFrom() string {
	if x != nil {
		return x.CtimeFrom
	}
	return ""
}

func (x *PgcMediaSearchReq) GetCtimeTo() string {
	if x != nil {
		return x.CtimeTo
	}
	return ""
}

func (x *PgcMediaSearchReq) GetMtimeFrom() string {
	if x != nil {
		return x.MtimeFrom
	}
	return ""
}

func (x *PgcMediaSearchReq) GetMtimeTo() string {
	if x != nil {
		return x.MtimeTo
	}
	return ""
}

// ==================== 评论记录搜索 ====================
type ReplyRecordSearchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bsp           *BasicSearchParams     `protobuf:"bytes,1,opt,name=bsp,proto3" json:"bsp,omitempty"`                              // 基础搜索参数
	Mid           int64                  `protobuf:"varint,2,opt,name=mid,proto3" json:"mid,omitempty"`                             // 用户ID
	Types         []int64                `protobuf:"varint,3,rep,packed,name=types,proto3" json:"types,omitempty"`                  // 类型列表
	States        []int64                `protobuf:"varint,4,rep,packed,name=states,proto3" json:"states,omitempty"`                // 状态列表
	CtimeFrom     string                 `protobuf:"bytes,5,opt,name=ctime_from,json=ctimeFrom,proto3" json:"ctime_from,omitempty"` // 创建时间起始
	CtimeTo       string                 `protobuf:"bytes,6,opt,name=ctime_to,json=ctimeTo,proto3" json:"ctime_to,omitempty"`       // 创建时间结束
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyRecordSearchReq) Reset() {
	*x = ReplyRecordSearchReq{}
	mi := &file_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyRecordSearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyRecordSearchReq) ProtoMessage() {}

func (x *ReplyRecordSearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyRecordSearchReq.ProtoReflect.Descriptor instead.
func (*ReplyRecordSearchReq) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{3}
}

func (x *ReplyRecordSearchReq) GetBsp() *BasicSearchParams {
	if x != nil {
		return x.Bsp
	}
	return nil
}

func (x *ReplyRecordSearchReq) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *ReplyRecordSearchReq) GetTypes() []int64 {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *ReplyRecordSearchReq) GetStates() []int64 {
	if x != nil {
		return x.States
	}
	return nil
}

func (x *ReplyRecordSearchReq) GetCtimeFrom() string {
	if x != nil {
		return x.CtimeFrom
	}
	return ""
}

func (x *ReplyRecordSearchReq) GetCtimeTo() string {
	if x != nil {
		return x.CtimeTo
	}
	return ""
}

// ==================== 弹幕历史搜索 ====================
type DmHistorySearchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bsp           *BasicSearchParams     `protobuf:"bytes,1,opt,name=bsp,proto3" json:"bsp,omitempty"`                              // 基础搜索参数
	Oid           int64                  `protobuf:"varint,2,opt,name=oid,proto3" json:"oid,omitempty"`                             // 对象ID
	States        []int64                `protobuf:"varint,3,rep,packed,name=states,proto3" json:"states,omitempty"`                // 状态列表
	CtimeFrom     string                 `protobuf:"bytes,4,opt,name=ctime_from,json=ctimeFrom,proto3" json:"ctime_from,omitempty"` // 创建时间起始
	CtimeTo       string                 `protobuf:"bytes,5,opt,name=ctime_to,json=ctimeTo,proto3" json:"ctime_to,omitempty"`       // 创建时间结束
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DmHistorySearchReq) Reset() {
	*x = DmHistorySearchReq{}
	mi := &file_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DmHistorySearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DmHistorySearchReq) ProtoMessage() {}

func (x *DmHistorySearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DmHistorySearchReq.ProtoReflect.Descriptor instead.
func (*DmHistorySearchReq) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{4}
}

func (x *DmHistorySearchReq) GetBsp() *BasicSearchParams {
	if x != nil {
		return x.Bsp
	}
	return nil
}

func (x *DmHistorySearchReq) GetOid() int64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

func (x *DmHistorySearchReq) GetStates() []int64 {
	if x != nil {
		return x.States
	}
	return nil
}

func (x *DmHistorySearchReq) GetCtimeFrom() string {
	if x != nil {
		return x.CtimeFrom
	}
	return ""
}

func (x *DmHistorySearchReq) GetCtimeTo() string {
	if x != nil {
		return x.CtimeTo
	}
	return ""
}

// ==================== 弹幕日期搜索 ====================
type DmDateSearchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bsp           *BasicSearchParams     `protobuf:"bytes,1,opt,name=bsp,proto3" json:"bsp,omitempty"`                              // 基础搜索参数
	Oid           int64                  `protobuf:"varint,2,opt,name=oid,proto3" json:"oid,omitempty"`                             // 对象ID
	Month         string                 `protobuf:"bytes,3,opt,name=month,proto3" json:"month,omitempty"`                          // 月份 (格式: 2024-01)
	MonthFrom     string                 `protobuf:"bytes,4,opt,name=month_from,json=monthFrom,proto3" json:"month_from,omitempty"` // 月份起始
	MonthTo       string                 `protobuf:"bytes,5,opt,name=month_to,json=monthTo,proto3" json:"month_to,omitempty"`       // 月份结束
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DmDateSearchReq) Reset() {
	*x = DmDateSearchReq{}
	mi := &file_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DmDateSearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DmDateSearchReq) ProtoMessage() {}

func (x *DmDateSearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DmDateSearchReq.ProtoReflect.Descriptor instead.
func (*DmDateSearchReq) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{5}
}

func (x *DmDateSearchReq) GetBsp() *BasicSearchParams {
	if x != nil {
		return x.Bsp
	}
	return nil
}

func (x *DmDateSearchReq) GetOid() int64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

func (x *DmDateSearchReq) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *DmDateSearchReq) GetMonthFrom() string {
	if x != nil {
		return x.MonthFrom
	}
	return ""
}

func (x *DmDateSearchReq) GetMonthTo() string {
	if x != nil {
		return x.MonthTo
	}
	return ""
}

// ==================== 搜索响应 ====================
type SearchResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         string                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`   // 排序字段
	Sort          string                 `protobuf:"bytes,2,opt,name=sort,proto3" json:"sort,omitempty"`     // 排序方式
	Result        [][]byte               `protobuf:"bytes,3,rep,name=result,proto3" json:"result,omitempty"` // 搜索结果(JSON)
	Page          *Page                  `protobuf:"bytes,4,opt,name=page,proto3" json:"page,omitempty"`     // 分页信息
	Debug         string                 `protobuf:"bytes,5,opt,name=debug,proto3" json:"debug,omitempty"`   // 调试信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResp) Reset() {
	*x = SearchResp{}
	mi := &file_search_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResp) ProtoMessage() {}

func (x *SearchResp) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResp.ProtoReflect.Descriptor instead.
func (*SearchResp) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{6}
}

func (x *SearchResp) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *SearchResp) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *SearchResp) GetResult() [][]byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *SearchResp) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *SearchResp) GetDebug() string {
	if x != nil {
		return x.Debug
	}
	return ""
}

type Page struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pn            int32                  `protobuf:"varint,1,opt,name=pn,proto3" json:"pn,omitempty"`       // 页码
	Ps            int32                  `protobuf:"varint,2,opt,name=ps,proto3" json:"ps,omitempty"`       // 每页数量
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"` // 总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Page) Reset() {
	*x = Page{}
	mi := &file_search_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{7}
}

func (x *Page) GetPn() int32 {
	if x != nil {
		return x.Pn
	}
	return 0
}

func (x *Page) GetPs() int32 {
	if x != nil {
		return x.Ps
	}
	return 0
}

func (x *Page) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// ==================== 索引更新请求 ====================
type DmUpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*DmUpdateItem        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DmUpdateReq) Reset() {
	*x = DmUpdateReq{}
	mi := &file_search_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DmUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DmUpdateReq) ProtoMessage() {}

func (x *DmUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DmUpdateReq.ProtoReflect.Descriptor instead.
func (*DmUpdateReq) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{8}
}

func (x *DmUpdateReq) GetItems() []*DmUpdateItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type DmUpdateItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                // 弹幕ID
	Oid           int64                  `protobuf:"varint,2,opt,name=oid,proto3" json:"oid,omitempty"`                                                                              // 对象ID
	Field         map[string]string      `protobuf:"bytes,3,rep,name=field,proto3" json:"field,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 更新字段
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DmUpdateItem) Reset() {
	*x = DmUpdateItem{}
	mi := &file_search_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DmUpdateItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DmUpdateItem) ProtoMessage() {}

func (x *DmUpdateItem) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DmUpdateItem.ProtoReflect.Descriptor instead.
func (*DmUpdateItem) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{9}
}

func (x *DmUpdateItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DmUpdateItem) GetOid() int64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

func (x *DmUpdateItem) GetField() map[string]string {
	if x != nil {
		return x.Field
	}
	return nil
}

type PgcUpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*PgcUpdateItem       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PgcUpdateReq) Reset() {
	*x = PgcUpdateReq{}
	mi := &file_search_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PgcUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PgcUpdateReq) ProtoMessage() {}

func (x *PgcUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PgcUpdateReq.ProtoReflect.Descriptor instead.
func (*PgcUpdateReq) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{10}
}

func (x *PgcUpdateReq) GetItems() []*PgcUpdateItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type PgcUpdateItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       int64                  `protobuf:"varint,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`                                                       // 媒体ID
	Field         map[string]string      `protobuf:"bytes,2,rep,name=field,proto3" json:"field,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 更新字段
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PgcUpdateItem) Reset() {
	*x = PgcUpdateItem{}
	mi := &file_search_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PgcUpdateItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PgcUpdateItem) ProtoMessage() {}

func (x *PgcUpdateItem) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PgcUpdateItem.ProtoReflect.Descriptor instead.
func (*PgcUpdateItem) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{11}
}

func (x *PgcUpdateItem) GetMediaId() int64 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

func (x *PgcUpdateItem) GetField() map[string]string {
	if x != nil {
		return x.Field
	}
	return nil
}

type ReplyUpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ReplyUpdateItem     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyUpdateReq) Reset() {
	*x = ReplyUpdateReq{}
	mi := &file_search_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyUpdateReq) ProtoMessage() {}

func (x *ReplyUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyUpdateReq.ProtoReflect.Descriptor instead.
func (*ReplyUpdateReq) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{12}
}

func (x *ReplyUpdateReq) GetItems() []*ReplyUpdateItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ReplyUpdateItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`       // 评论ID
	Oid           int64                  `protobuf:"varint,2,opt,name=oid,proto3" json:"oid,omitempty"`     // 对象ID
	Mid           int64                  `protobuf:"varint,3,opt,name=mid,proto3" json:"mid,omitempty"`     // 用户ID
	State         int32                  `protobuf:"varint,4,opt,name=state,proto3" json:"state,omitempty"` // 状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyUpdateItem) Reset() {
	*x = ReplyUpdateItem{}
	mi := &file_search_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyUpdateItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyUpdateItem) ProtoMessage() {}

func (x *ReplyUpdateItem) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyUpdateItem.ProtoReflect.Descriptor instead.
func (*ReplyUpdateItem) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{13}
}

func (x *ReplyUpdateItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReplyUpdateItem) GetOid() int64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

func (x *ReplyUpdateItem) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *ReplyUpdateItem) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

type UpdateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResp) Reset() {
	*x = UpdateResp{}
	mi := &file_search_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResp) ProtoMessage() {}

func (x *UpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResp.ProtoReflect.Descriptor instead.
func (*UpdateResp) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_search_proto protoreflect.FileDescriptor

const file_search_proto_rawDesc = "" +
	"\n" +
	"\fsearch.proto\x12\x06search\"\xb7\x01\n" +
	"\x11BasicSearchParams\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x0e\n" +
	"\x02kw\x18\x02 \x01(\tR\x02kw\x12\x1b\n" +
	"\tkw_fields\x18\x03 \x03(\tR\bkwFields\x12\x14\n" +
	"\x05order\x18\x04 \x03(\tR\x05order\x12\x12\n" +
	"\x04sort\x18\x05 \x03(\tR\x04sort\x12\x0e\n" +
	"\x02pn\x18\x06 \x01(\x05R\x02pn\x12\x0e\n" +
	"\x02ps\x18\a \x01(\x05R\x02ps\x12\x14\n" +
	"\x05debug\x18\b \x01(\bR\x05debug\"\xa9\x02\n" +
	"\vDmSearchReq\x12+\n" +
	"\x03bsp\x18\x01 \x01(\v2\x19.search.BasicSearchParamsR\x03bsp\x12\x10\n" +
	"\x03oid\x18\x02 \x01(\x03R\x03oid\x12\x10\n" +
	"\x03mid\x18\x03 \x01(\x03R\x03mid\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\x05R\x04mode\x12\x12\n" +
	"\x04pool\x18\x05 \x01(\x05R\x04pool\x12\x1a\n" +
	"\bprogress\x18\x06 \x01(\x05R\bprogress\x12\x16\n" +
	"\x06states\x18\a \x03(\x05R\x06states\x12\x12\n" +
	"\x04type\x18\b \x01(\x05R\x04type\x12\x1f\n" +
	"\vattr_format\x18\t \x03(\x05R\n" +
	"attrFormat\x12\x1d\n" +
	"\n" +
	"ctime_from\x18\n" +
	" \x01(\tR\tctimeFrom\x12\x19\n" +
	"\bctime_to\x18\v \x01(\tR\actimeTo\"\xcc\a\n" +
	"\x11PgcMediaSearchReq\x12+\n" +
	"\x03bsp\x18\x01 \x01(\v2\x19.search.BasicSearchParamsR\x03bsp\x12\x1b\n" +
	"\tmedia_ids\x18\x02 \x03(\x03R\bmediaIds\x12\x1d\n" +
	"\n" +
	"season_ids\x18\x03 \x03(\x03R\tseasonIds\x12!\n" +
	"\fseason_types\x18\x04 \x03(\x03R\vseasonTypes\x12\x1b\n" +
	"\tstyle_ids\x18\x05 \x03(\x03R\bstyleIds\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12*\n" +
	"\x11release_date_from\x18\a \x01(\tR\x0freleaseDateFrom\x12&\n" +
	"\x0frelease_date_to\x18\b \x01(\tR\rreleaseDateTo\x12$\n" +
	"\x0eseason_id_from\x18\t \x01(\x05R\fseasonIdFrom\x12 \n" +
	"\fseason_id_to\x18\n" +
	" \x01(\x05R\n" +
	"seasonIdTo\x12!\n" +
	"\fproducer_ids\x18\v \x03(\x03R\vproducerIds\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\f \x01(\x05R\tisDeleted\x12\x19\n" +
	"\barea_ids\x18\r \x03(\tR\aareaIds\x12\x1d\n" +
	"\n" +
	"score_from\x18\x0e \x01(\x05R\tscoreFrom\x12\x19\n" +
	"\bscore_to\x18\x0f \x01(\x05R\ascoreTo\x12\x1b\n" +
	"\tis_finish\x18\x10 \x01(\tR\bisFinish\x12'\n" +
	"\x0fseason_versions\x18\x11 \x03(\x03R\x0eseasonVersions\x12'\n" +
	"\x0fseason_statuses\x18\x12 \x03(\x03R\x0eseasonStatuses\x12\"\n" +
	"\rpub_time_from\x18\x13 \x01(\tR\vpubTimeFrom\x12\x1e\n" +
	"\vpub_time_to\x18\x14 \x01(\tR\tpubTimeTo\x12#\n" +
	"\rseason_months\x18\x15 \x03(\x03R\fseasonMonths\x12(\n" +
	"\x10latest_time_from\x18\x16 \x01(\tR\x0elatestTimeFrom\x12$\n" +
	"\x0elatest_time_to\x18\x17 \x01(\tR\flatestTimeTo\x12'\n" +
	"\x0fcopyright_infos\x18\x18 \x03(\tR\x0ecopyrightInfos\x12\x1d\n" +
	"\n" +
	"ctime_from\x18\x19 \x01(\tR\tctimeFrom\x12\x19\n" +
	"\bctime_to\x18\x1a \x01(\tR\actimeTo\x12\x1d\n" +
	"\n" +
	"mtime_from\x18\x1b \x01(\tR\tmtimeFrom\x12\x19\n" +
	"\bmtime_to\x18\x1c \x01(\tR\amtimeTo\"\xbd\x01\n" +
	"\x14ReplyRecordSearchReq\x12+\n" +
	"\x03bsp\x18\x01 \x01(\v2\x19.search.BasicSearchParamsR\x03bsp\x12\x10\n" +
	"\x03mid\x18\x02 \x01(\x03R\x03mid\x12\x14\n" +
	"\x05types\x18\x03 \x03(\x03R\x05types\x12\x16\n" +
	"\x06states\x18\x04 \x03(\x03R\x06states\x12\x1d\n" +
	"\n" +
	"ctime_from\x18\x05 \x01(\tR\tctimeFrom\x12\x19\n" +
	"\bctime_to\x18\x06 \x01(\tR\actimeTo\"\xa5\x01\n" +
	"\x12DmHistorySearchReq\x12+\n" +
	"\x03bsp\x18\x01 \x01(\v2\x19.search.BasicSearchParamsR\x03bsp\x12\x10\n" +
	"\x03oid\x18\x02 \x01(\x03R\x03oid\x12\x16\n" +
	"\x06states\x18\x03 \x03(\x03R\x06states\x12\x1d\n" +
	"\n" +
	"ctime_from\x18\x04 \x01(\tR\tctimeFrom\x12\x19\n" +
	"\bctime_to\x18\x05 \x01(\tR\actimeTo\"\xa0\x01\n" +
	"\x0fDmDateSearchReq\x12+\n" +
	"\x03bsp\x18\x01 \x01(\v2\x19.search.BasicSearchParamsR\x03bsp\x12\x10\n" +
	"\x03oid\x18\x02 \x01(\x03R\x03oid\x12\x14\n" +
	"\x05month\x18\x03 \x01(\tR\x05month\x12\x1d\n" +
	"\n" +
	"month_from\x18\x04 \x01(\tR\tmonthFrom\x12\x19\n" +
	"\bmonth_to\x18\x05 \x01(\tR\amonthTo\"\x86\x01\n" +
	"\n" +
	"SearchResp\x12\x14\n" +
	"\x05order\x18\x01 \x01(\tR\x05order\x12\x12\n" +
	"\x04sort\x18\x02 \x01(\tR\x04sort\x12\x16\n" +
	"\x06result\x18\x03 \x03(\fR\x06result\x12 \n" +
	"\x04page\x18\x04 \x01(\v2\f.search.PageR\x04page\x12\x14\n" +
	"\x05debug\x18\x05 \x01(\tR\x05debug\"<\n" +
	"\x04Page\x12\x0e\n" +
	"\x02pn\x18\x01 \x01(\x05R\x02pn\x12\x0e\n" +
	"\x02ps\x18\x02 \x01(\x05R\x02ps\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\"9\n" +
	"\vDmUpdateReq\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.search.DmUpdateItemR\x05items\"\xa1\x01\n" +
	"\fDmUpdateItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03oid\x18\x02 \x01(\x03R\x03oid\x125\n" +
	"\x05field\x18\x03 \x03(\v2\x1f.search.DmUpdateItem.FieldEntryR\x05field\x1a8\n" +
	"\n" +
	"FieldEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\";\n" +
	"\fPgcUpdateReq\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.search.PgcUpdateItemR\x05items\"\x9c\x01\n" +
	"\rPgcUpdateItem\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\x03R\amediaId\x126\n" +
	"\x05field\x18\x02 \x03(\v2 .search.PgcUpdateItem.FieldEntryR\x05field\x1a8\n" +
	"\n" +
	"FieldEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"?\n" +
	"\x0eReplyUpdateReq\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.search.ReplyUpdateItemR\x05items\"[\n" +
	"\x0fReplyUpdateItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03oid\x18\x02 \x01(\x03R\x03oid\x12\x10\n" +
	"\x03mid\x18\x03 \x01(\x03R\x03mid\x12\x14\n" +
	"\x05state\x18\x04 \x01(\x05R\x05state\"@\n" +
	"\n" +
	"UpdateResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xec\x03\n" +
	"\x06Search\x123\n" +
	"\bDmSearch\x12\x13.search.DmSearchReq\x1a\x12.search.SearchResp\x12?\n" +
	"\x0ePgcMediaSearch\x12\x19.search.PgcMediaSearchReq\x1a\x12.search.SearchResp\x12E\n" +
	"\x11ReplyRecordSearch\x12\x1c.search.ReplyRecordSearchReq\x1a\x12.search.SearchResp\x12A\n" +
	"\x0fDmHistorySearch\x12\x1a.search.DmHistorySearchReq\x1a\x12.search.SearchResp\x12;\n" +
	"\fDmDateSearch\x12\x17.search.DmDateSearchReq\x1a\x12.search.SearchResp\x123\n" +
	"\bDmUpdate\x12\x13.search.DmUpdateReq\x1a\x12.search.UpdateResp\x125\n" +
	"\tPgcUpdate\x12\x14.search.PgcUpdateReq\x1a\x12.search.UpdateResp\x129\n" +
	"\vReplyUpdate\x12\x16.search.ReplyUpdateReq\x1a\x12.search.UpdateRespB\n" +
	"Z\b./searchb\x06proto3"

var (
	file_search_proto_rawDescOnce sync.Once
	file_search_proto_rawDescData []byte
)

func file_search_proto_rawDescGZIP() []byte {
	file_search_proto_rawDescOnce.Do(func() {
		file_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_search_proto_rawDesc), len(file_search_proto_rawDesc)))
	})
	return file_search_proto_rawDescData
}

var file_search_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_search_proto_goTypes = []any{
	(*BasicSearchParams)(nil),    // 0: search.BasicSearchParams
	(*DmSearchReq)(nil),          // 1: search.DmSearchReq
	(*PgcMediaSearchReq)(nil),    // 2: search.PgcMediaSearchReq
	(*ReplyRecordSearchReq)(nil), // 3: search.ReplyRecordSearchReq
	(*DmHistorySearchReq)(nil),   // 4: search.DmHistorySearchReq
	(*DmDateSearchReq)(nil),      // 5: search.DmDateSearchReq
	(*SearchResp)(nil),           // 6: search.SearchResp
	(*Page)(nil),                 // 7: search.Page
	(*DmUpdateReq)(nil),          // 8: search.DmUpdateReq
	(*DmUpdateItem)(nil),         // 9: search.DmUpdateItem
	(*PgcUpdateReq)(nil),         // 10: search.PgcUpdateReq
	(*PgcUpdateItem)(nil),        // 11: search.PgcUpdateItem
	(*ReplyUpdateReq)(nil),       // 12: search.ReplyUpdateReq
	(*ReplyUpdateItem)(nil),      // 13: search.ReplyUpdateItem
	(*UpdateResp)(nil),           // 14: search.UpdateResp
	nil,                          // 15: search.DmUpdateItem.FieldEntry
	nil,                          // 16: search.PgcUpdateItem.FieldEntry
}
var file_search_proto_depIdxs = []int32{
	0,  // 0: search.DmSearchReq.bsp:type_name -> search.BasicSearchParams
	0,  // 1: search.PgcMediaSearchReq.bsp:type_name -> search.BasicSearchParams
	0,  // 2: search.ReplyRecordSearchReq.bsp:type_name -> search.BasicSearchParams
	0,  // 3: search.DmHistorySearchReq.bsp:type_name -> search.BasicSearchParams
	0,  // 4: search.DmDateSearchReq.bsp:type_name -> search.BasicSearchParams
	7,  // 5: search.SearchResp.page:type_name -> search.Page
	9,  // 6: search.DmUpdateReq.items:type_name -> search.DmUpdateItem
	15, // 7: search.DmUpdateItem.field:type_name -> search.DmUpdateItem.FieldEntry
	11, // 8: search.PgcUpdateReq.items:type_name -> search.PgcUpdateItem
	16, // 9: search.PgcUpdateItem.field:type_name -> search.PgcUpdateItem.FieldEntry
	13, // 10: search.ReplyUpdateReq.items:type_name -> search.ReplyUpdateItem
	1,  // 11: search.Search.DmSearch:input_type -> search.DmSearchReq
	2,  // 12: search.Search.PgcMediaSearch:input_type -> search.PgcMediaSearchReq
	3,  // 13: search.Search.ReplyRecordSearch:input_type -> search.ReplyRecordSearchReq
	4,  // 14: search.Search.DmHistorySearch:input_type -> search.DmHistorySearchReq
	5,  // 15: search.Search.DmDateSearch:input_type -> search.DmDateSearchReq
	8,  // 16: search.Search.DmUpdate:input_type -> search.DmUpdateReq
	10, // 17: search.Search.PgcUpdate:input_type -> search.PgcUpdateReq
	12, // 18: search.Search.ReplyUpdate:input_type -> search.ReplyUpdateReq
	6,  // 19: search.Search.DmSearch:output_type -> search.SearchResp
	6,  // 20: search.Search.PgcMediaSearch:output_type -> search.SearchResp
	6,  // 21: search.Search.ReplyRecordSearch:output_type -> search.SearchResp
	6,  // 22: search.Search.DmHistorySearch:output_type -> search.SearchResp
	6,  // 23: search.Search.DmDateSearch:output_type -> search.SearchResp
	14, // 24: search.Search.DmUpdate:output_type -> search.UpdateResp
	14, // 25: search.Search.PgcUpdate:output_type -> search.UpdateResp
	14, // 26: search.Search.ReplyUpdate:output_type -> search.UpdateResp
	19, // [19:27] is the sub-list for method output_type
	11, // [11:19] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_search_proto_init() }
func file_search_proto_init() {
	if File_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_search_proto_rawDesc), len(file_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_search_proto_goTypes,
		DependencyIndexes: file_search_proto_depIdxs,
		MessageInfos:      file_search_proto_msgTypes,
	}.Build()
	File_search_proto = out.File
	file_search_proto_goTypes = nil
	file_search_proto_depIdxs = nil
}
