// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: coupon.proto

package server

import (
	"context"

	"mybilibili/app/coupon/cmd/rpc/coupon"
	"mybilibili/app/coupon/cmd/rpc/internal/logic"
	"mybilibili/app/coupon/cmd/rpc/internal/svc"
)

type CouponServer struct {
	svcCtx *svc.ServiceContext
	coupon.UnimplementedCouponServer
}

func NewCouponServer(svcCtx *svc.ServiceContext) *CouponServer {
	return &CouponServer{
		svcCtx: svcCtx,
	}
}

// ========== 验证码相关 ==========
func (s *CouponServer) CaptchaToken(ctx context.Context, in *coupon.CaptchaTokenReq) (*coupon.CaptchaTokenResp, error) {
	l := logic.NewCaptchaTokenLogic(ctx, s.svcCtx)
	return l.CaptchaToken(in)
}

// ========== 兑换码相关 ==========
func (s *CouponServer) UseCouponCode(ctx context.Context, in *coupon.UseCouponCodeReq) (*coupon.UseCouponCodeResp, error) {
	l := logic.NewUseCouponCodeLogic(ctx, s.svcCtx)
	return l.UseCouponCode(in)
}

// ========== 代金券相关 ==========
func (s *CouponServer) UsableAllowanceCouponV2(ctx context.Context, in *coupon.UsableAllowanceCouponV2Req) (*coupon.UsableAllowanceCouponV2Resp, error) {
	l := logic.NewUsableAllowanceCouponV2Logic(ctx, s.svcCtx)
	return l.UsableAllowanceCouponV2(in)
}

// 使用代金券
func (s *CouponServer) UseAllowanceCoupon(ctx context.Context, in *coupon.UseAllowanceCouponReq) (*coupon.UseAllowanceCouponResp, error) {
	l := logic.NewUseAllowanceCouponLogic(ctx, s.svcCtx)
	return l.UseAllowanceCoupon(in)
}

// 取消使用代金券
func (s *CouponServer) CancelAllowanceCoupon(ctx context.Context, in *coupon.CancelAllowanceCouponReq) (*coupon.CancelAllowanceCouponResp, error) {
	l := logic.NewCancelAllowanceCouponLogic(ctx, s.svcCtx)
	return l.CancelAllowanceCoupon(in)
}

// 代金券使用通知（支付结果回调）
func (s *CouponServer) AllowanceCouponNotify(ctx context.Context, in *coupon.AllowanceCouponNotifyReq) (*coupon.AllowanceCouponNotifyResp, error) {
	l := logic.NewAllowanceCouponNotifyLogic(ctx, s.svcCtx)
	return l.AllowanceCouponNotify(in)
}

// 代金券列表
func (s *CouponServer) AllowanceList(ctx context.Context, in *coupon.AllowanceListReq) (*coupon.AllowanceListResp, error) {
	l := logic.NewAllowanceListLogic(ctx, s.svcCtx)
	return l.AllowanceList(in)
}

// 代金券详情
func (s *CouponServer) AllowanceInfo(ctx context.Context, in *coupon.AllowanceInfoReq) (*coupon.AllowanceInfoResp, error) {
	l := logic.NewAllowanceInfoLogic(ctx, s.svcCtx)
	return l.AllowanceInfo(in)
}

// 领取代金券
func (s *CouponServer) ReceiveAllowance(ctx context.Context, in *coupon.ReceiveAllowanceReq) (*coupon.ReceiveAllowanceResp, error) {
	l := logic.NewReceiveAllowanceLogic(ctx, s.svcCtx)
	return l.ReceiveAllowance(in)
}

// 同步检查代金券是否可用
func (s *CouponServer) UseNotify(ctx context.Context, in *coupon.UseNotifyReq) (*coupon.UseNotifyResp, error) {
	l := logic.NewUseNotifyLogic(ctx, s.svcCtx)
	return l.UseNotify(in)
}

// ========== 观影券相关 ==========
func (s *CouponServer) UserCoupon(ctx context.Context, in *coupon.UserCouponReq) (*coupon.UserCouponResp, error) {
	l := logic.NewUserCouponLogic(ctx, s.svcCtx)
	return l.UserCoupon(in)
}

// 使用观影券
func (s *CouponServer) UseCoupon(ctx context.Context, in *coupon.UseCouponReq) (*coupon.UseCouponResp, error) {
	l := logic.NewUseCouponLogic(ctx, s.svcCtx)
	return l.UseCoupon(in)
}

// 观影券详情
func (s *CouponServer) CouponInfo(ctx context.Context, in *coupon.CouponInfoReq) (*coupon.CouponInfoResp, error) {
	l := logic.NewCouponInfoLogic(ctx, s.svcCtx)
	return l.CouponInfo(in)
}

// 观影券分页列表
func (s *CouponServer) CouponPage(ctx context.Context, in *coupon.CouponPageReq) (*coupon.CouponPageResp, error) {
	l := logic.NewCouponPageLogic(ctx, s.svcCtx)
	return l.CouponPage(in)
}

// 观影券数量
func (s *CouponServer) VideoCouponCount(ctx context.Context, in *coupon.VideoCouponCountReq) (*coupon.VideoCouponCountResp, error) {
	l := logic.NewVideoCouponCountLogic(ctx, s.svcCtx)
	return l.VideoCouponCount(in)
}

// ========== 发放相关 ==========
func (s *CouponServer) SalaryCoupon(ctx context.Context, in *coupon.SalaryCouponReq) (*coupon.SalaryCouponResp, error) {
	l := logic.NewSalaryCouponLogic(ctx, s.svcCtx)
	return l.SalaryCoupon(in)
}

// 第三方发放优惠券
func (s *CouponServer) SalaryCouponForThird(ctx context.Context, in *coupon.SalaryCouponForThirdReq) (*coupon.SalaryCouponForThirdResp, error) {
	l := logic.NewSalaryCouponForThirdLogic(ctx, s.svcCtx)
	return l.SalaryCouponForThird(in)
}

// ========== 批次相关 ==========
func (s *CouponServer) BatchInfo(ctx context.Context, in *coupon.BatchInfoReq) (*coupon.BatchInfoResp, error) {
	l := logic.NewBatchInfoLogic(ctx, s.svcCtx)
	return l.BatchInfo(in)
}
