// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AllowanceListReq struct {
	Mid   int64 `form:"mid"`
	State int32 `form:"state"`
}

type AllowanceListResp struct {
	List []*CouponAllowancePanelInfo `json:"list"`
}

type CancelAllowanceCouponReq struct {
	Mid         int64  `json:"mid"`
	CouponToken string `json:"coupon_token"`
}

type CaptchaTokenReq struct {
}

type CaptchaTokenResp struct {
	Token string `json:"token"`
	Url   string `json:"url"`
}

type CouponAllowancePanelInfo struct {
	CouponToken         string  `json:"coupon_token"`
	CouponAmount        float64 `json:"coupon_amount"`
	State               int32   `json:"state"`
	FullLimitExplain    string  `json:"full_limit_explain"`
	ScopeExplain        string  `json:"scope_explain"`
	FullAmount          float64 `json:"full_amount"`
	CouponDiscountPrice float64 `json:"coupon_discount_price"`
	StartTime           int64   `json:"start_time"`
	ExpireTime          int64   `json:"expire_time"`
	Selected            int32   `json:"selected"`
	DisablesExplains    string  `json:"disables_explains"`
	OrderNo             string  `json:"order_no"`
	Name                string  `json:"name"`
	Usable              int32   `json:"usable"`
}

type CouponInfoItem struct {
	Id          int64  `json:"id"`
	CouponToken string `json:"coupon_token"`
	State       int32  `json:"state"`
	StartTime   int64  `json:"start_time"`
	ExpireTime  int64  `json:"expire_time"`
}

type CouponPageItem struct {
	Id    int64  `json:"id"`
	Title string `json:"title"`
	Time  int64  `json:"time"`
	RefId int64  `json:"ref_id"`
}

type CouponPageReq struct {
	Mid   int64 `form:"mid"`
	State int32 `form:"state"`
	Pn    int32 `form:"pn,default=1"`
	Ps    int32 `form:"ps,default=20"`
}

type CouponPageResp struct {
	Count int64             `json:"count"`
	List  []*CouponPageItem `json:"list"`
}

type PriceInfo struct {
	Price          float64 `json:"price"`
	Plat           int64   `json:"plat"`
	ProdLimMonth   int32   `json:"prod_lim_month"`
	ProdLimRenewal int32   `json:"prod_lim_renewal"`
}

type ReceiveAllowanceReq struct {
	Mid        int64  `json:"mid"`
	BatchToken string `json:"batch_token"`
	OrderNo    string `json:"order_no"`
	Appkey     string `json:"appkey"`
}

type ReceiveAllowanceResp struct {
	CouponToken string `json:"coupon_token"`
}

type UsableAllowanceCouponV2Req struct {
	Mid       int64       `json:"mid"`
	PriceInfo []PriceInfo `json:"price_info"`
}

type UsableAllowanceCouponV2Resp struct {
	CouponTip  string                    `json:"coupon_tip"`
	CouponInfo *CouponAllowancePanelInfo `json:"coupon_info"`
}

type UseAllowanceCouponReq struct {
	Mid            int64   `json:"mid"`
	CouponToken    string  `json:"coupon_token"`
	Remark         string  `json:"remark"`
	OrderNo        string  `json:"order_no"`
	Price          float64 `json:"price"`
	Platform       string  `json:"platform,default=pc"`
	ProdLimMonth   int32   `json:"prod_lim_month,optional"`
	ProdLimRenewal int32   `json:"prod_lim_renewal,optional"`
}

type UseCouponCodeReq struct {
	Mid    int64  `json:"mid"`
	Token  string `json:"token"`
	Code   string `json:"code"`
	Verify string `json:"verify"`
}

type UseCouponCodeResp struct {
	CouponToken          string  `json:"coupon_token"`
	CouponAmount         float64 `json:"coupon_amount"`
	FullAmount           float64 `json:"full_amount"`
	PlatformLimitExplain string  `json:"platform_limit_explain"`
	ProductLimitMonth    int32   `json:"product_limit_month"`
	ProductLimitRenewal  int32   `json:"product_limit_renewal"`
}

type UserCouponReq struct {
	Mid        int64 `form:"mid"`
	CouponType int32 `form:"coupon_type"`
}

type UserCouponResp struct {
	List []*CouponInfoItem `json:"list"`
}

type VideoCouponCountReq struct {
	Mid        int64 `form:"mid"`
	CouponType int32 `form:"coupon_type"`
}

type VideoCouponCountResp struct {
	Count int32 `json:"count"`
}
