// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: search.proto

package server

import (
	"context"

	"mybilibili/app/search/cmd/rpc/internal/logic"
	"mybilibili/app/search/cmd/rpc/internal/svc"
	"mybilibili/app/search/cmd/rpc/search"
)

type SearchServer struct {
	svcCtx *svc.ServiceContext
	search.UnimplementedSearchServer
}

func NewSearchServer(svcCtx *svc.ServiceContext) *SearchServer {
	return &SearchServer{
		svcCtx: svcCtx,
	}
}

// 弹幕搜索
func (s *SearchServer) DmSearch(ctx context.Context, in *search.DmSearchReq) (*search.SearchResp, error) {
	l := logic.NewDmSearchLogic(ctx, s.svcCtx)
	return l.DmSearch(in)
}

// PGC番剧搜索
func (s *SearchServer) PgcMediaSearch(ctx context.Context, in *search.PgcMediaSearchReq) (*search.SearchResp, error) {
	l := logic.NewPgcMediaSearchLogic(ctx, s.svcCtx)
	return l.PgcMediaSearch(in)
}

// 评论记录搜索
func (s *SearchServer) ReplyRecordSearch(ctx context.Context, in *search.ReplyRecordSearchReq) (*search.SearchResp, error) {
	l := logic.NewReplyRecordSearchLogic(ctx, s.svcCtx)
	return l.ReplyRecordSearch(in)
}

// 弹幕历史搜索
func (s *SearchServer) DmHistorySearch(ctx context.Context, in *search.DmHistorySearchReq) (*search.SearchResp, error) {
	l := logic.NewDmHistorySearchLogic(ctx, s.svcCtx)
	return l.DmHistorySearch(in)
}

// 弹幕日期搜索
func (s *SearchServer) DmDateSearch(ctx context.Context, in *search.DmDateSearchReq) (*search.SearchResp, error) {
	l := logic.NewDmDateSearchLogic(ctx, s.svcCtx)
	return l.DmDateSearch(in)
}

// 弹幕索引更新
func (s *SearchServer) DmUpdate(ctx context.Context, in *search.DmUpdateReq) (*search.UpdateResp, error) {
	l := logic.NewDmUpdateLogic(ctx, s.svcCtx)
	return l.DmUpdate(in)
}

// PGC索引更新
func (s *SearchServer) PgcUpdate(ctx context.Context, in *search.PgcUpdateReq) (*search.UpdateResp, error) {
	l := logic.NewPgcUpdateLogic(ctx, s.svcCtx)
	return l.PgcUpdate(in)
}

// 评论索引更新
func (s *SearchServer) ReplyUpdate(ctx context.Context, in *search.ReplyUpdateReq) (*search.UpdateResp, error) {
	l := logic.NewReplyUpdateLogic(ctx, s.svcCtx)
	return l.ReplyUpdate(in)
}
