// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: search.proto

package search_client

import (
	"context"

	"mybilibili/app/search/cmd/rpc/search"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BasicSearchParams    = search.BasicSearchParams
	DmDateSearchReq      = search.DmDateSearchReq
	DmHistorySearchReq   = search.DmHistorySearchReq
	DmSearchReq          = search.DmSearchReq
	DmUpdateItem         = search.DmUpdateItem
	DmUpdateReq          = search.DmUpdateReq
	Page                 = search.Page
	PgcMediaSearchReq    = search.PgcMediaSearchReq
	PgcUpdateItem        = search.PgcUpdateItem
	PgcUpdateReq         = search.PgcUpdateReq
	ReplyRecordSearchReq = search.ReplyRecordSearchReq
	ReplyUpdateItem      = search.ReplyUpdateItem
	ReplyUpdateReq       = search.ReplyUpdateReq
	SearchResp           = search.SearchResp
	UpdateResp           = search.UpdateResp

	Search interface {
		// 弹幕搜索
		DmSearch(ctx context.Context, in *DmSearchReq, opts ...grpc.CallOption) (*SearchResp, error)
		// PGC番剧搜索
		PgcMediaSearch(ctx context.Context, in *PgcMediaSearchReq, opts ...grpc.CallOption) (*SearchResp, error)
		// 评论记录搜索
		ReplyRecordSearch(ctx context.Context, in *ReplyRecordSearchReq, opts ...grpc.CallOption) (*SearchResp, error)
		// 弹幕历史搜索
		DmHistorySearch(ctx context.Context, in *DmHistorySearchReq, opts ...grpc.CallOption) (*SearchResp, error)
		// 弹幕日期搜索
		DmDateSearch(ctx context.Context, in *DmDateSearchReq, opts ...grpc.CallOption) (*SearchResp, error)
		// 弹幕索引更新
		DmUpdate(ctx context.Context, in *DmUpdateReq, opts ...grpc.CallOption) (*UpdateResp, error)
		// PGC索引更新
		PgcUpdate(ctx context.Context, in *PgcUpdateReq, opts ...grpc.CallOption) (*UpdateResp, error)
		// 评论索引更新
		ReplyUpdate(ctx context.Context, in *ReplyUpdateReq, opts ...grpc.CallOption) (*UpdateResp, error)
	}

	defaultSearch struct {
		cli zrpc.Client
	}
)

func NewSearch(cli zrpc.Client) Search {
	return &defaultSearch{
		cli: cli,
	}
}

// 弹幕搜索
func (m *defaultSearch) DmSearch(ctx context.Context, in *DmSearchReq, opts ...grpc.CallOption) (*SearchResp, error) {
	client := search.NewSearchClient(m.cli.Conn())
	return client.DmSearch(ctx, in, opts...)
}

// PGC番剧搜索
func (m *defaultSearch) PgcMediaSearch(ctx context.Context, in *PgcMediaSearchReq, opts ...grpc.CallOption) (*SearchResp, error) {
	client := search.NewSearchClient(m.cli.Conn())
	return client.PgcMediaSearch(ctx, in, opts...)
}

// 评论记录搜索
func (m *defaultSearch) ReplyRecordSearch(ctx context.Context, in *ReplyRecordSearchReq, opts ...grpc.CallOption) (*SearchResp, error) {
	client := search.NewSearchClient(m.cli.Conn())
	return client.ReplyRecordSearch(ctx, in, opts...)
}

// 弹幕历史搜索
func (m *defaultSearch) DmHistorySearch(ctx context.Context, in *DmHistorySearchReq, opts ...grpc.CallOption) (*SearchResp, error) {
	client := search.NewSearchClient(m.cli.Conn())
	return client.DmHistorySearch(ctx, in, opts...)
}

// 弹幕日期搜索
func (m *defaultSearch) DmDateSearch(ctx context.Context, in *DmDateSearchReq, opts ...grpc.CallOption) (*SearchResp, error) {
	client := search.NewSearchClient(m.cli.Conn())
	return client.DmDateSearch(ctx, in, opts...)
}

// 弹幕索引更新
func (m *defaultSearch) DmUpdate(ctx context.Context, in *DmUpdateReq, opts ...grpc.CallOption) (*UpdateResp, error) {
	client := search.NewSearchClient(m.cli.Conn())
	return client.DmUpdate(ctx, in, opts...)
}

// PGC索引更新
func (m *defaultSearch) PgcUpdate(ctx context.Context, in *PgcUpdateReq, opts ...grpc.CallOption) (*UpdateResp, error) {
	client := search.NewSearchClient(m.cli.Conn())
	return client.PgcUpdate(ctx, in, opts...)
}

// 评论索引更新
func (m *defaultSearch) ReplyUpdate(ctx context.Context, in *ReplyUpdateReq, opts ...grpc.CallOption) (*UpdateResp, error) {
	client := search.NewSearchClient(m.cli.Conn())
	return client.ReplyUpdate(ctx, in, opts...)
}
