// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CoinStreamRecord struct {
	Id            int64  `json:"id"`
	Uid           int64  `json:"uid"`
	TransactionId string `json:"transaction_id"`
	CoinType      int32  `json:"coin_type"`
	DeltaCoinNum  int64  `json:"delta_coin_num"`
	OrgCoinNum    int64  `json:"org_coin_num"`
	OpResult      int32  `json:"op_result"`
	OpReason      int32  `json:"op_reason"`
	OpType        int32  `json:"op_type"`
	OpTime        string `json:"op_time"`
	BizCode       string `json:"biz_code"`
	Platform      int32  `json:"platform"`
}

type ExchangeReq struct {
	Uid           int64  `json:"uid"`
	SrcCoinType   string `json:"src_coin_type"`
	SrcCoinNum    int64  `json:"src_coin_num"`
	DestCoinType  string `json:"dest_coin_type"`
	DestCoinNum   int64  `json:"dest_coin_num"`
	TransactionId string `json:"transaction_id"`
	Platform      string `json:"platform"`
}

type GetDetailReq struct {
	Uid      int64  `form:"uid"`
	Platform string `form:"platform,optional,default=android"`
}

type GetDetailResp struct {
	Detail WalletDetail `json:"detail"`
}

type GetStreamListReq struct {
	Uid    int64 `form:"uid"`
	Offset int64 `form:"offset,optional,default=0"`
	Limit  int64 `form:"limit,optional,default=20"`
}

type GetStreamListResp struct {
	List  []CoinStreamRecord `json:"list"`
	Total int64              `json:"total"`
}

type PayReq struct {
	Uid           int64  `json:"uid"`
	CoinType      string `json:"coin_type"`
	CoinNum       int64  `json:"coin_num"`
	TransactionId string `json:"transaction_id"`
	ExtendTid     string `json:"extend_tid,optional"`
	Platform      string `json:"platform"`
	Timestamp     int64  `json:"timestamp,optional"`
	BizCode       string `json:"biz_code,optional"`
}

type RechargeReq struct {
	Uid           int64  `json:"uid"`
	CoinType      string `json:"coin_type"` // gold/iap_gold
	CoinNum       int64  `json:"coin_num"`
	TransactionId string `json:"transaction_id"`
	ExtendTid     string `json:"extend_tid,optional"`
	Platform      string `json:"platform"` // ios/android/pc/h5
	Timestamp     int64  `json:"timestamp,optional"`
	BizCode       string `json:"biz_code,optional"`
}

type WalletDetail struct {
	Uid             int64 `json:"uid"`
	Gold            int64 `json:"gold"`
	IapGold         int64 `json:"iap_gold"`
	Silver          int64 `json:"silver"`
	GoldRechargeCnt int64 `json:"gold_recharge_cnt"`
	GoldPayCnt      int64 `json:"gold_pay_cnt"`
	SilverPayCnt    int64 `json:"silver_pay_cnt"`
	CostBase        int64 `json:"cost_base"`
}

type WalletResp struct {
	Gold    int64 `json:"gold"`
	IapGold int64 `json:"iap_gold"`
	Silver  int64 `json:"silver"`
}
