// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: coupon.proto

package coupon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ==================== 通用消息 ====================
type PriceInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Price          float64                `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	Plat           int64                  `protobuf:"varint,2,opt,name=plat,proto3" json:"plat,omitempty"`
	ProdLimMonth   int32                  `protobuf:"varint,3,opt,name=prod_lim_month,json=prodLimMonth,proto3" json:"prod_lim_month,omitempty"`
	ProdLimRenewal int32                  `protobuf:"varint,4,opt,name=prod_lim_renewal,json=prodLimRenewal,proto3" json:"prod_lim_renewal,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PriceInfo) Reset() {
	*x = PriceInfo{}
	mi := &file_coupon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceInfo) ProtoMessage() {}

func (x *PriceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceInfo.ProtoReflect.Descriptor instead.
func (*PriceInfo) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{0}
}

func (x *PriceInfo) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PriceInfo) GetPlat() int64 {
	if x != nil {
		return x.Plat
	}
	return 0
}

func (x *PriceInfo) GetProdLimMonth() int32 {
	if x != nil {
		return x.ProdLimMonth
	}
	return 0
}

func (x *PriceInfo) GetProdLimRenewal() int32 {
	if x != nil {
		return x.ProdLimRenewal
	}
	return 0
}

type CouponAllowancePanelInfo struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CouponToken         string                 `protobuf:"bytes,1,opt,name=coupon_token,json=couponToken,proto3" json:"coupon_token,omitempty"`
	CouponAmount        float64                `protobuf:"fixed64,2,opt,name=coupon_amount,json=couponAmount,proto3" json:"coupon_amount,omitempty"`
	State               int32                  `protobuf:"varint,3,opt,name=state,proto3" json:"state,omitempty"`
	FullLimitExplain    string                 `protobuf:"bytes,4,opt,name=full_limit_explain,json=fullLimitExplain,proto3" json:"full_limit_explain,omitempty"`
	ScopeExplain        string                 `protobuf:"bytes,5,opt,name=scope_explain,json=scopeExplain,proto3" json:"scope_explain,omitempty"`
	FullAmount          float64                `protobuf:"fixed64,6,opt,name=full_amount,json=fullAmount,proto3" json:"full_amount,omitempty"`
	CouponDiscountPrice float64                `protobuf:"fixed64,7,opt,name=coupon_discount_price,json=couponDiscountPrice,proto3" json:"coupon_discount_price,omitempty"`
	StartTime           int64                  `protobuf:"varint,8,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	ExpireTime          int64                  `protobuf:"varint,9,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	Selected            int32                  `protobuf:"varint,10,opt,name=selected,proto3" json:"selected,omitempty"`
	DisablesExplains    string                 `protobuf:"bytes,11,opt,name=disables_explains,json=disablesExplains,proto3" json:"disables_explains,omitempty"`
	OrderNo             string                 `protobuf:"bytes,12,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	Name                string                 `protobuf:"bytes,13,opt,name=name,proto3" json:"name,omitempty"`
	Usable              int32                  `protobuf:"varint,14,opt,name=usable,proto3" json:"usable,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CouponAllowancePanelInfo) Reset() {
	*x = CouponAllowancePanelInfo{}
	mi := &file_coupon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouponAllowancePanelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponAllowancePanelInfo) ProtoMessage() {}

func (x *CouponAllowancePanelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponAllowancePanelInfo.ProtoReflect.Descriptor instead.
func (*CouponAllowancePanelInfo) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{1}
}

func (x *CouponAllowancePanelInfo) GetCouponToken() string {
	if x != nil {
		return x.CouponToken
	}
	return ""
}

func (x *CouponAllowancePanelInfo) GetCouponAmount() float64 {
	if x != nil {
		return x.CouponAmount
	}
	return 0
}

func (x *CouponAllowancePanelInfo) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *CouponAllowancePanelInfo) GetFullLimitExplain() string {
	if x != nil {
		return x.FullLimitExplain
	}
	return ""
}

func (x *CouponAllowancePanelInfo) GetScopeExplain() string {
	if x != nil {
		return x.ScopeExplain
	}
	return ""
}

func (x *CouponAllowancePanelInfo) GetFullAmount() float64 {
	if x != nil {
		return x.FullAmount
	}
	return 0
}

func (x *CouponAllowancePanelInfo) GetCouponDiscountPrice() float64 {
	if x != nil {
		return x.CouponDiscountPrice
	}
	return 0
}

func (x *CouponAllowancePanelInfo) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *CouponAllowancePanelInfo) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *CouponAllowancePanelInfo) GetSelected() int32 {
	if x != nil {
		return x.Selected
	}
	return 0
}

func (x *CouponAllowancePanelInfo) GetDisablesExplains() string {
	if x != nil {
		return x.DisablesExplains
	}
	return ""
}

func (x *CouponAllowancePanelInfo) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *CouponAllowancePanelInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CouponAllowancePanelInfo) GetUsable() int32 {
	if x != nil {
		return x.Usable
	}
	return 0
}

type CouponInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CouponToken   string                 `protobuf:"bytes,2,opt,name=coupon_token,json=couponToken,proto3" json:"coupon_token,omitempty"`
	Mid           int64                  `protobuf:"varint,3,opt,name=mid,proto3" json:"mid,omitempty"`
	State         int32                  `protobuf:"varint,4,opt,name=state,proto3" json:"state,omitempty"`
	StartTime     int64                  `protobuf:"varint,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	ExpireTime    int64                  `protobuf:"varint,6,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	Origin        int64                  `protobuf:"varint,7,opt,name=origin,proto3" json:"origin,omitempty"`
	CouponType    int64                  `protobuf:"varint,8,opt,name=coupon_type,json=couponType,proto3" json:"coupon_type,omitempty"`
	OrderNo       string                 `protobuf:"bytes,9,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	Oid           int64                  `protobuf:"varint,10,opt,name=oid,proto3" json:"oid,omitempty"`
	Remark        string                 `protobuf:"bytes,11,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CouponInfo) Reset() {
	*x = CouponInfo{}
	mi := &file_coupon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouponInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponInfo) ProtoMessage() {}

func (x *CouponInfo) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponInfo.ProtoReflect.Descriptor instead.
func (*CouponInfo) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{2}
}

func (x *CouponInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CouponInfo) GetCouponToken() string {
	if x != nil {
		return x.CouponToken
	}
	return ""
}

func (x *CouponInfo) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *CouponInfo) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *CouponInfo) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *CouponInfo) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *CouponInfo) GetOrigin() int64 {
	if x != nil {
		return x.Origin
	}
	return 0
}

func (x *CouponInfo) GetCouponType() int64 {
	if x != nil {
		return x.CouponType
	}
	return 0
}

func (x *CouponInfo) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *CouponInfo) GetOid() int64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

func (x *CouponInfo) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

// ==================== 验证码 ====================
type CaptchaTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptchaTokenReq) Reset() {
	*x = CaptchaTokenReq{}
	mi := &file_coupon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptchaTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptchaTokenReq) ProtoMessage() {}

func (x *CaptchaTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptchaTokenReq.ProtoReflect.Descriptor instead.
func (*CaptchaTokenReq) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{3}
}

func (x *CaptchaTokenReq) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type CaptchaTokenResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptchaTokenResp) Reset() {
	*x = CaptchaTokenResp{}
	mi := &file_coupon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptchaTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptchaTokenResp) ProtoMessage() {}

func (x *CaptchaTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptchaTokenResp.ProtoReflect.Descriptor instead.
func (*CaptchaTokenResp) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{4}
}

func (x *CaptchaTokenResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CaptchaTokenResp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// ==================== 兑换码 ====================
type UseCouponCodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Verify        string                 `protobuf:"bytes,3,opt,name=verify,proto3" json:"verify,omitempty"`
	Ip            string                 `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	Mid           int64                  `protobuf:"varint,5,opt,name=mid,proto3" json:"mid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseCouponCodeReq) Reset() {
	*x = UseCouponCodeReq{}
	mi := &file_coupon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseCouponCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseCouponCodeReq) ProtoMessage() {}

func (x *UseCouponCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseCouponCodeReq.ProtoReflect.Descriptor instead.
func (*UseCouponCodeReq) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{5}
}

func (x *UseCouponCodeReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UseCouponCodeReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UseCouponCodeReq) GetVerify() string {
	if x != nil {
		return x.Verify
	}
	return ""
}

func (x *UseCouponCodeReq) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *UseCouponCodeReq) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

type UseCouponCodeResp struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CouponToken          string                 `protobuf:"bytes,1,opt,name=coupon_token,json=couponToken,proto3" json:"coupon_token,omitempty"`
	CouponAmount         float64                `protobuf:"fixed64,2,opt,name=coupon_amount,json=couponAmount,proto3" json:"coupon_amount,omitempty"`
	FullAmount           float64                `protobuf:"fixed64,3,opt,name=full_amount,json=fullAmount,proto3" json:"full_amount,omitempty"`
	PlatformLimitExplain string                 `protobuf:"bytes,4,opt,name=platform_limit_explain,json=platformLimitExplain,proto3" json:"platform_limit_explain,omitempty"`
	ProductLimitMonth    int32                  `protobuf:"varint,5,opt,name=product_limit_month,json=productLimitMonth,proto3" json:"product_limit_month,omitempty"`
	ProductLimitRenewal  int32                  `protobuf:"varint,6,opt,name=product_limit_renewal,json=productLimitRenewal,proto3" json:"product_limit_renewal,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UseCouponCodeResp) Reset() {
	*x = UseCouponCodeResp{}
	mi := &file_coupon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseCouponCodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseCouponCodeResp) ProtoMessage() {}

func (x *UseCouponCodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseCouponCodeResp.ProtoReflect.Descriptor instead.
func (*UseCouponCodeResp) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{6}
}

func (x *UseCouponCodeResp) GetCouponToken() string {
	if x != nil {
		return x.CouponToken
	}
	return ""
}

func (x *UseCouponCodeResp) GetCouponAmount() float64 {
	if x != nil {
		return x.CouponAmount
	}
	return 0
}

func (x *UseCouponCodeResp) GetFullAmount() float64 {
	if x != nil {
		return x.FullAmount
	}
	return 0
}

func (x *UseCouponCodeResp) GetPlatformLimitExplain() string {
	if x != nil {
		return x.PlatformLimitExplain
	}
	return ""
}

func (x *UseCouponCodeResp) GetProductLimitMonth() int32 {
	if x != nil {
		return x.ProductLimitMonth
	}
	return 0
}

func (x *UseCouponCodeResp) GetProductLimitRenewal() int32 {
	if x != nil {
		return x.ProductLimitRenewal
	}
	return 0
}

// ==================== 代金券 ====================
type UsableAllowanceCouponV2Req struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mid           int64                  `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`
	PriceInfo     []*PriceInfo           `protobuf:"bytes,2,rep,name=price_info,json=priceInfo,proto3" json:"price_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsableAllowanceCouponV2Req) Reset() {
	*x = UsableAllowanceCouponV2Req{}
	mi := &file_coupon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsableAllowanceCouponV2Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsableAllowanceCouponV2Req) ProtoMessage() {}

func (x *UsableAllowanceCouponV2Req) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsableAllowanceCouponV2Req.ProtoReflect.Descriptor instead.
func (*UsableAllowanceCouponV2Req) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{7}
}

func (x *UsableAllowanceCouponV2Req) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *UsableAllowanceCouponV2Req) GetPriceInfo() []*PriceInfo {
	if x != nil {
		return x.PriceInfo
	}
	return nil
}

type UsableAllowanceCouponV2Resp struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	CouponTip     string                    `protobuf:"bytes,1,opt,name=coupon_tip,json=couponTip,proto3" json:"coupon_tip,omitempty"`
	CouponInfo    *CouponAllowancePanelInfo `protobuf:"bytes,2,opt,name=coupon_info,json=couponInfo,proto3" json:"coupon_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsableAllowanceCouponV2Resp) Reset() {
	*x = UsableAllowanceCouponV2Resp{}
	mi := &file_coupon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsableAllowanceCouponV2Resp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsableAllowanceCouponV2Resp) ProtoMessage() {}

func (x *UsableAllowanceCouponV2Resp) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsableAllowanceCouponV2Resp.ProtoReflect.Descriptor instead.
func (*UsableAllowanceCouponV2Resp) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{8}
}

func (x *UsableAllowanceCouponV2Resp) GetCouponTip() string {
	if x != nil {
		return x.CouponTip
	}
	return ""
}

func (x *UsableAllowanceCouponV2Resp) GetCouponInfo() *CouponAllowancePanelInfo {
	if x != nil {
		return x.CouponInfo
	}
	return nil
}

type UseAllowanceCouponReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Mid            int64                  `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`
	CouponToken    string                 `protobuf:"bytes,2,opt,name=coupon_token,json=couponToken,proto3" json:"coupon_token,omitempty"`
	Remark         string                 `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	OrderNo        string                 `protobuf:"bytes,4,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	Price          float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Platform       string                 `protobuf:"bytes,6,opt,name=platform,proto3" json:"platform,omitempty"`
	ProdLimMonth   int32                  `protobuf:"varint,7,opt,name=prod_lim_month,json=prodLimMonth,proto3" json:"prod_lim_month,omitempty"`
	ProdLimRenewal int32                  `protobuf:"varint,8,opt,name=prod_lim_renewal,json=prodLimRenewal,proto3" json:"prod_lim_renewal,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UseAllowanceCouponReq) Reset() {
	*x = UseAllowanceCouponReq{}
	mi := &file_coupon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseAllowanceCouponReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseAllowanceCouponReq) ProtoMessage() {}

func (x *UseAllowanceCouponReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseAllowanceCouponReq.ProtoReflect.Descriptor instead.
func (*UseAllowanceCouponReq) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{9}
}

func (x *UseAllowanceCouponReq) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *UseAllowanceCouponReq) GetCouponToken() string {
	if x != nil {
		return x.CouponToken
	}
	return ""
}

func (x *UseAllowanceCouponReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *UseAllowanceCouponReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *UseAllowanceCouponReq) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UseAllowanceCouponReq) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *UseAllowanceCouponReq) GetProdLimMonth() int32 {
	if x != nil {
		return x.ProdLimMonth
	}
	return 0
}

func (x *UseAllowanceCouponReq) GetProdLimRenewal() int32 {
	if x != nil {
		return x.ProdLimRenewal
	}
	return 0
}

type UseAllowanceCouponResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseAllowanceCouponResp) Reset() {
	*x = UseAllowanceCouponResp{}
	mi := &file_coupon_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseAllowanceCouponResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseAllowanceCouponResp) ProtoMessage() {}

func (x *UseAllowanceCouponResp) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseAllowanceCouponResp.ProtoReflect.Descriptor instead.
func (*UseAllowanceCouponResp) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{10}
}

type CancelAllowanceCouponReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mid           int64                  `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`
	CouponToken   string                 `protobuf:"bytes,2,opt,name=coupon_token,json=couponToken,proto3" json:"coupon_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelAllowanceCouponReq) Reset() {
	*x = CancelAllowanceCouponReq{}
	mi := &file_coupon_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelAllowanceCouponReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelAllowanceCouponReq) ProtoMessage() {}

func (x *CancelAllowanceCouponReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelAllowanceCouponReq.ProtoReflect.Descriptor instead.
func (*CancelAllowanceCouponReq) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{11}
}

func (x *CancelAllowanceCouponReq) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *CancelAllowanceCouponReq) GetCouponToken() string {
	if x != nil {
		return x.CouponToken
	}
	return ""
}

type CancelAllowanceCouponResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelAllowanceCouponResp) Reset() {
	*x = CancelAllowanceCouponResp{}
	mi := &file_coupon_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelAllowanceCouponResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelAllowanceCouponResp) ProtoMessage() {}

func (x *CancelAllowanceCouponResp) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelAllowanceCouponResp.ProtoReflect.Descriptor instead.
func (*CancelAllowanceCouponResp) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{12}
}

type AllowanceCouponNotifyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mid           int64                  `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	PayState      int32                  `protobuf:"varint,3,opt,name=pay_state,json=payState,proto3" json:"pay_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllowanceCouponNotifyReq) Reset() {
	*x = AllowanceCouponNotifyReq{}
	mi := &file_coupon_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllowanceCouponNotifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowanceCouponNotifyReq) ProtoMessage() {}

func (x *AllowanceCouponNotifyReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowanceCouponNotifyReq.ProtoReflect.Descriptor instead.
func (*AllowanceCouponNotifyReq) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{13}
}

func (x *AllowanceCouponNotifyReq) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *AllowanceCouponNotifyReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *AllowanceCouponNotifyReq) GetPayState() int32 {
	if x != nil {
		return x.PayState
	}
	return 0
}

type AllowanceCouponNotifyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllowanceCouponNotifyResp) Reset() {
	*x = AllowanceCouponNotifyResp{}
	mi := &file_coupon_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllowanceCouponNotifyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowanceCouponNotifyResp) ProtoMessage() {}

func (x *AllowanceCouponNotifyResp) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowanceCouponNotifyResp.ProtoReflect.Descriptor instead.
func (*AllowanceCouponNotifyResp) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{14}
}

type AllowanceListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mid           int64                  `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`
	State         int32                  `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllowanceListReq) Reset() {
	*x = AllowanceListReq{}
	mi := &file_coupon_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllowanceListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowanceListReq) ProtoMessage() {}

func (x *AllowanceListReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowanceListReq.ProtoReflect.Descriptor instead.
func (*AllowanceListReq) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{15}
}

func (x *AllowanceListReq) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *AllowanceListReq) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

type AllowanceListResp struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	List          []*CouponAllowancePanelInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllowanceListResp) Reset() {
	*x = AllowanceListResp{}
	mi := &file_coupon_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllowanceListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowanceListResp) ProtoMessage() {}

func (x *AllowanceListResp) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowanceListResp.ProtoReflect.Descriptor instead.
func (*AllowanceListResp) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{16}
}

func (x *AllowanceListResp) GetList() []*CouponAllowancePanelInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type AllowanceInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mid           int64                  `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`
	CouponToken   string                 `protobuf:"bytes,2,opt,name=coupon_token,json=couponToken,proto3" json:"coupon_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllowanceInfoReq) Reset() {
	*x = AllowanceInfoReq{}
	mi := &file_coupon_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllowanceInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowanceInfoReq) ProtoMessage() {}

func (x *AllowanceInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowanceInfoReq.ProtoReflect.Descriptor instead.
func (*AllowanceInfoReq) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{17}
}

func (x *AllowanceInfoReq) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *AllowanceInfoReq) GetCouponToken() string {
	if x != nil {
		return x.CouponToken
	}
	return ""
}

type AllowanceInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CouponToken   string                 `protobuf:"bytes,2,opt,name=coupon_token,json=couponToken,proto3" json:"coupon_token,omitempty"`
	Mid           int64                  `protobuf:"varint,3,opt,name=mid,proto3" json:"mid,omitempty"`
	State         int32                  `protobuf:"varint,4,opt,name=state,proto3" json:"state,omitempty"`
	StartTime     int64                  `protobuf:"varint,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	ExpireTime    int64                  `protobuf:"varint,6,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	Amount        float64                `protobuf:"fixed64,7,opt,name=amount,proto3" json:"amount,omitempty"`
	FullAmount    float64                `protobuf:"fixed64,8,opt,name=full_amount,json=fullAmount,proto3" json:"full_amount,omitempty"`
	BatchToken    string                 `protobuf:"bytes,9,opt,name=batch_token,json=batchToken,proto3" json:"batch_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllowanceInfoResp) Reset() {
	*x = AllowanceInfoResp{}
	mi := &file_coupon_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllowanceInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowanceInfoResp) ProtoMessage() {}

func (x *AllowanceInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowanceInfoResp.ProtoReflect.Descriptor instead.
func (*AllowanceInfoResp) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{18}
}

func (x *AllowanceInfoResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AllowanceInfoResp) GetCouponToken() string {
	if x != nil {
		return x.CouponToken
	}
	return ""
}

func (x *AllowanceInfoResp) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *AllowanceInfoResp) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *AllowanceInfoResp) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *AllowanceInfoResp) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *AllowanceInfoResp) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *AllowanceInfoResp) GetFullAmount() float64 {
	if x != nil {
		return x.FullAmount
	}
	return 0
}

func (x *AllowanceInfoResp) GetBatchToken() string {
	if x != nil {
		return x.BatchToken
	}
	return ""
}

type ReceiveAllowanceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mid           int64                  `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`
	BatchToken    string                 `protobuf:"bytes,2,opt,name=batch_token,json=batchToken,proto3" json:"batch_token,omitempty"`
	OrderNo       string                 `protobuf:"bytes,3,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	Appkey        string                 `protobuf:"bytes,4,opt,name=appkey,proto3" json:"appkey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveAllowanceReq) Reset() {
	*x = ReceiveAllowanceReq{}
	mi := &file_coupon_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveAllowanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveAllowanceReq) ProtoMessage() {}

func (x *ReceiveAllowanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveAllowanceReq.ProtoReflect.Descriptor instead.
func (*ReceiveAllowanceReq) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{19}
}

func (x *ReceiveAllowanceReq) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *ReceiveAllowanceReq) GetBatchToken() string {
	if x != nil {
		return x.BatchToken
	}
	return ""
}

func (x *ReceiveAllowanceReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *ReceiveAllowanceReq) GetAppkey() string {
	if x != nil {
		return x.Appkey
	}
	return ""
}

type ReceiveAllowanceResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CouponToken   string                 `protobuf:"bytes,1,opt,name=coupon_token,json=couponToken,proto3" json:"coupon_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveAllowanceResp) Reset() {
	*x = ReceiveAllowanceResp{}
	mi := &file_coupon_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveAllowanceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveAllowanceResp) ProtoMessage() {}

func (x *ReceiveAllowanceResp) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveAllowanceResp.ProtoReflect.Descriptor instead.
func (*ReceiveAllowanceResp) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{20}
}

func (x *ReceiveAllowanceResp) GetCouponToken() string {
	if x != nil {
		return x.CouponToken
	}
	return ""
}

type UseNotifyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mid           int64                  `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseNotifyReq) Reset() {
	*x = UseNotifyReq{}
	mi := &file_coupon_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseNotifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseNotifyReq) ProtoMessage() {}

func (x *UseNotifyReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseNotifyReq.ProtoReflect.Descriptor instead.
func (*UseNotifyReq) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{21}
}

func (x *UseNotifyReq) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *UseNotifyReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type UseNotifyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CouponToken   string                 `protobuf:"bytes,1,opt,name=coupon_token,json=couponToken,proto3" json:"coupon_token,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	FullAmount    float64                `protobuf:"fixed64,3,opt,name=full_amount,json=fullAmount,proto3" json:"full_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseNotifyResp) Reset() {
	*x = UseNotifyResp{}
	mi := &file_coupon_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseNotifyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseNotifyResp) ProtoMessage() {}

func (x *UseNotifyResp) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseNotifyResp.ProtoReflect.Descriptor instead.
func (*UseNotifyResp) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{22}
}

func (x *UseNotifyResp) GetCouponToken() string {
	if x != nil {
		return x.CouponToken
	}
	return ""
}

func (x *UseNotifyResp) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UseNotifyResp) GetFullAmount() float64 {
	if x != nil {
		return x.FullAmount
	}
	return 0
}

// ==================== 观影券 ====================
type UserCouponReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mid           int64                  `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`
	CouponType    int32                  `protobuf:"varint,2,opt,name=coupon_type,json=couponType,proto3" json:"coupon_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCouponReq) Reset() {
	*x = UserCouponReq{}
	mi := &file_coupon_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCouponReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCouponReq) ProtoMessage() {}

func (x *UserCouponReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCouponReq.ProtoReflect.Descriptor instead.
func (*UserCouponReq) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{23}
}

func (x *UserCouponReq) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *UserCouponReq) GetCouponType() int32 {
	if x != nil {
		return x.CouponType
	}
	return 0
}

type UserCouponResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*CouponInfo          `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCouponResp) Reset() {
	*x = UserCouponResp{}
	mi := &file_coupon_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCouponResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCouponResp) ProtoMessage() {}

func (x *UserCouponResp) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCouponResp.ProtoReflect.Descriptor instead.
func (*UserCouponResp) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{24}
}

func (x *UserCouponResp) GetList() []*CouponInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type UseCouponReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mid           int64                  `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`
	Oid           int64                  `protobuf:"varint,2,opt,name=oid,proto3" json:"oid,omitempty"`
	Remark        string                 `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	OrderNo       string                 `protobuf:"bytes,4,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	CouponType    int32                  `protobuf:"varint,5,opt,name=coupon_type,json=couponType,proto3" json:"coupon_type,omitempty"`
	UseVer        int64                  `protobuf:"varint,6,opt,name=use_ver,json=useVer,proto3" json:"use_ver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseCouponReq) Reset() {
	*x = UseCouponReq{}
	mi := &file_coupon_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseCouponReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseCouponReq) ProtoMessage() {}

func (x *UseCouponReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseCouponReq.ProtoReflect.Descriptor instead.
func (*UseCouponReq) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{25}
}

func (x *UseCouponReq) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *UseCouponReq) GetOid() int64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

func (x *UseCouponReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *UseCouponReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *UseCouponReq) GetCouponType() int32 {
	if x != nil {
		return x.CouponType
	}
	return 0
}

func (x *UseCouponReq) GetUseVer() int64 {
	if x != nil {
		return x.UseVer
	}
	return 0
}

type UseCouponResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ret           int32                  `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	CouponToken   string                 `protobuf:"bytes,2,opt,name=coupon_token,json=couponToken,proto3" json:"coupon_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseCouponResp) Reset() {
	*x = UseCouponResp{}
	mi := &file_coupon_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseCouponResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseCouponResp) ProtoMessage() {}

func (x *UseCouponResp) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseCouponResp.ProtoReflect.Descriptor instead.
func (*UseCouponResp) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{26}
}

func (x *UseCouponResp) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *UseCouponResp) GetCouponToken() string {
	if x != nil {
		return x.CouponToken
	}
	return ""
}

type CouponInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mid           int64                  `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`
	CouponToken   string                 `protobuf:"bytes,2,opt,name=coupon_token,json=couponToken,proto3" json:"coupon_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CouponInfoReq) Reset() {
	*x = CouponInfoReq{}
	mi := &file_coupon_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouponInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponInfoReq) ProtoMessage() {}

func (x *CouponInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponInfoReq.ProtoReflect.Descriptor instead.
func (*CouponInfoReq) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{27}
}

func (x *CouponInfoReq) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *CouponInfoReq) GetCouponToken() string {
	if x != nil {
		return x.CouponToken
	}
	return ""
}

type CouponInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *CouponInfo            `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CouponInfoResp) Reset() {
	*x = CouponInfoResp{}
	mi := &file_coupon_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouponInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponInfoResp) ProtoMessage() {}

func (x *CouponInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponInfoResp.ProtoReflect.Descriptor instead.
func (*CouponInfoResp) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{28}
}

func (x *CouponInfoResp) GetInfo() *CouponInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type CouponPageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mid           int64                  `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`
	State         int32                  `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
	Pn            int32                  `protobuf:"varint,3,opt,name=pn,proto3" json:"pn,omitempty"`
	Ps            int32                  `protobuf:"varint,4,opt,name=ps,proto3" json:"ps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CouponPageReq) Reset() {
	*x = CouponPageReq{}
	mi := &file_coupon_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouponPageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponPageReq) ProtoMessage() {}

func (x *CouponPageReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponPageReq.ProtoReflect.Descriptor instead.
func (*CouponPageReq) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{29}
}

func (x *CouponPageReq) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *CouponPageReq) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *CouponPageReq) GetPn() int32 {
	if x != nil {
		return x.Pn
	}
	return 0
}

func (x *CouponPageReq) GetPs() int32 {
	if x != nil {
		return x.Ps
	}
	return 0
}

type CouponPageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	List          []*CouponPageItem      `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CouponPageResp) Reset() {
	*x = CouponPageResp{}
	mi := &file_coupon_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouponPageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponPageResp) ProtoMessage() {}

func (x *CouponPageResp) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponPageResp.ProtoReflect.Descriptor instead.
func (*CouponPageResp) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{30}
}

func (x *CouponPageResp) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *CouponPageResp) GetList() []*CouponPageItem {
	if x != nil {
		return x.List
	}
	return nil
}

type CouponPageItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Time          int64                  `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	RefId         int64                  `protobuf:"varint,4,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`
	Tips          string                 `protobuf:"bytes,5,opt,name=tips,proto3" json:"tips,omitempty"`
	Count         int64                  `protobuf:"varint,6,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CouponPageItem) Reset() {
	*x = CouponPageItem{}
	mi := &file_coupon_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouponPageItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponPageItem) ProtoMessage() {}

func (x *CouponPageItem) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponPageItem.ProtoReflect.Descriptor instead.
func (*CouponPageItem) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{31}
}

func (x *CouponPageItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CouponPageItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CouponPageItem) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *CouponPageItem) GetRefId() int64 {
	if x != nil {
		return x.RefId
	}
	return 0
}

func (x *CouponPageItem) GetTips() string {
	if x != nil {
		return x.Tips
	}
	return ""
}

func (x *CouponPageItem) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type VideoCouponCountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mid           int64                  `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`
	CouponType    int32                  `protobuf:"varint,2,opt,name=coupon_type,json=couponType,proto3" json:"coupon_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoCouponCountReq) Reset() {
	*x = VideoCouponCountReq{}
	mi := &file_coupon_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoCouponCountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoCouponCountReq) ProtoMessage() {}

func (x *VideoCouponCountReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoCouponCountReq.ProtoReflect.Descriptor instead.
func (*VideoCouponCountReq) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{32}
}

func (x *VideoCouponCountReq) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *VideoCouponCountReq) GetCouponType() int32 {
	if x != nil {
		return x.CouponType
	}
	return 0
}

type VideoCouponCountResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoCouponCountResp) Reset() {
	*x = VideoCouponCountResp{}
	mi := &file_coupon_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoCouponCountResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoCouponCountResp) ProtoMessage() {}

func (x *VideoCouponCountResp) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoCouponCountResp.ProtoReflect.Descriptor instead.
func (*VideoCouponCountResp) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{33}
}

func (x *VideoCouponCountResp) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// ==================== 发放 ====================
type SalaryCouponReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mid           int64                  `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`
	CouponType    int64                  `protobuf:"varint,2,opt,name=coupon_type,json=couponType,proto3" json:"coupon_type,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	BatchToken    string                 `protobuf:"bytes,4,opt,name=batch_token,json=batchToken,proto3" json:"batch_token,omitempty"`
	AppId         int64                  `protobuf:"varint,5,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Origin        int64                  `protobuf:"varint,6,opt,name=origin,proto3" json:"origin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SalaryCouponReq) Reset() {
	*x = SalaryCouponReq{}
	mi := &file_coupon_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SalaryCouponReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SalaryCouponReq) ProtoMessage() {}

func (x *SalaryCouponReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SalaryCouponReq.ProtoReflect.Descriptor instead.
func (*SalaryCouponReq) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{34}
}

func (x *SalaryCouponReq) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *SalaryCouponReq) GetCouponType() int64 {
	if x != nil {
		return x.CouponType
	}
	return 0
}

func (x *SalaryCouponReq) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *SalaryCouponReq) GetBatchToken() string {
	if x != nil {
		return x.BatchToken
	}
	return ""
}

func (x *SalaryCouponReq) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *SalaryCouponReq) GetOrigin() int64 {
	if x != nil {
		return x.Origin
	}
	return 0
}

type SalaryCouponResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SalaryCouponResp) Reset() {
	*x = SalaryCouponResp{}
	mi := &file_coupon_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SalaryCouponResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SalaryCouponResp) ProtoMessage() {}

func (x *SalaryCouponResp) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SalaryCouponResp.ProtoReflect.Descriptor instead.
func (*SalaryCouponResp) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{35}
}

type SalaryCouponForThirdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mid           int64                  `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`
	CouponType    int64                  `protobuf:"varint,2,opt,name=coupon_type,json=couponType,proto3" json:"coupon_type,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	BatchToken    string                 `protobuf:"bytes,4,opt,name=batch_token,json=batchToken,proto3" json:"batch_token,omitempty"`
	AppId         int64                  `protobuf:"varint,5,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	UniqueNo      string                 `protobuf:"bytes,6,opt,name=unique_no,json=uniqueNo,proto3" json:"unique_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SalaryCouponForThirdReq) Reset() {
	*x = SalaryCouponForThirdReq{}
	mi := &file_coupon_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SalaryCouponForThirdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SalaryCouponForThirdReq) ProtoMessage() {}

func (x *SalaryCouponForThirdReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SalaryCouponForThirdReq.ProtoReflect.Descriptor instead.
func (*SalaryCouponForThirdReq) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{36}
}

func (x *SalaryCouponForThirdReq) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *SalaryCouponForThirdReq) GetCouponType() int64 {
	if x != nil {
		return x.CouponType
	}
	return 0
}

func (x *SalaryCouponForThirdReq) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *SalaryCouponForThirdReq) GetBatchToken() string {
	if x != nil {
		return x.BatchToken
	}
	return ""
}

func (x *SalaryCouponForThirdReq) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *SalaryCouponForThirdReq) GetUniqueNo() string {
	if x != nil {
		return x.UniqueNo
	}
	return ""
}

type SalaryCouponForThirdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float64                `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	FullAmount    float64                `protobuf:"fixed64,2,opt,name=full_amount,json=fullAmount,proto3" json:"full_amount,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SalaryCouponForThirdResp) Reset() {
	*x = SalaryCouponForThirdResp{}
	mi := &file_coupon_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SalaryCouponForThirdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SalaryCouponForThirdResp) ProtoMessage() {}

func (x *SalaryCouponForThirdResp) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SalaryCouponForThirdResp.ProtoReflect.Descriptor instead.
func (*SalaryCouponForThirdResp) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{37}
}

func (x *SalaryCouponForThirdResp) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *SalaryCouponForThirdResp) GetFullAmount() float64 {
	if x != nil {
		return x.FullAmount
	}
	return 0
}

func (x *SalaryCouponForThirdResp) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// ==================== 批次 ====================
type BatchInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchToken    string                 `protobuf:"bytes,1,opt,name=batch_token,json=batchToken,proto3" json:"batch_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchInfoReq) Reset() {
	*x = BatchInfoReq{}
	mi := &file_coupon_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchInfoReq) ProtoMessage() {}

func (x *BatchInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchInfoReq.ProtoReflect.Descriptor instead.
func (*BatchInfoReq) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{38}
}

func (x *BatchInfoReq) GetBatchToken() string {
	if x != nil {
		return x.BatchToken
	}
	return ""
}

type BatchInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AppId         int64                  `protobuf:"varint,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	BatchToken    string                 `protobuf:"bytes,4,opt,name=batch_token,json=batchToken,proto3" json:"batch_token,omitempty"`
	MaxCount      int64                  `protobuf:"varint,5,opt,name=max_count,json=maxCount,proto3" json:"max_count,omitempty"`
	CurrentCount  int64                  `protobuf:"varint,6,opt,name=current_count,json=currentCount,proto3" json:"current_count,omitempty"`
	StartTime     int64                  `protobuf:"varint,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	ExpireTime    int64                  `protobuf:"varint,8,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	ExpireDay     int64                  `protobuf:"varint,9,opt,name=expire_day,json=expireDay,proto3" json:"expire_day,omitempty"`
	LimitCount    int64                  `protobuf:"varint,10,opt,name=limit_count,json=limitCount,proto3" json:"limit_count,omitempty"`
	FullAmount    float64                `protobuf:"fixed64,11,opt,name=full_amount,json=fullAmount,proto3" json:"full_amount,omitempty"`
	Amount        float64                `protobuf:"fixed64,12,opt,name=amount,proto3" json:"amount,omitempty"`
	State         int32                  `protobuf:"varint,13,opt,name=state,proto3" json:"state,omitempty"`
	CouponType    int32                  `protobuf:"varint,14,opt,name=coupon_type,json=couponType,proto3" json:"coupon_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchInfoResp) Reset() {
	*x = BatchInfoResp{}
	mi := &file_coupon_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchInfoResp) ProtoMessage() {}

func (x *BatchInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchInfoResp.ProtoReflect.Descriptor instead.
func (*BatchInfoResp) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{39}
}

func (x *BatchInfoResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BatchInfoResp) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *BatchInfoResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BatchInfoResp) GetBatchToken() string {
	if x != nil {
		return x.BatchToken
	}
	return ""
}

func (x *BatchInfoResp) GetMaxCount() int64 {
	if x != nil {
		return x.MaxCount
	}
	return 0
}

func (x *BatchInfoResp) GetCurrentCount() int64 {
	if x != nil {
		return x.CurrentCount
	}
	return 0
}

func (x *BatchInfoResp) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *BatchInfoResp) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *BatchInfoResp) GetExpireDay() int64 {
	if x != nil {
		return x.ExpireDay
	}
	return 0
}

func (x *BatchInfoResp) GetLimitCount() int64 {
	if x != nil {
		return x.LimitCount
	}
	return 0
}

func (x *BatchInfoResp) GetFullAmount() float64 {
	if x != nil {
		return x.FullAmount
	}
	return 0
}

func (x *BatchInfoResp) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BatchInfoResp) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *BatchInfoResp) GetCouponType() int32 {
	if x != nil {
		return x.CouponType
	}
	return 0
}

var File_coupon_proto protoreflect.FileDescriptor

const file_coupon_proto_rawDesc = "" +
	"\n" +
	"\fcoupon.proto\x12\x06coupon\"\x85\x01\n" +
	"\tPriceInfo\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x01R\x05price\x12\x12\n" +
	"\x04plat\x18\x02 \x01(\x03R\x04plat\x12$\n" +
	"\x0eprod_lim_month\x18\x03 \x01(\x05R\fprodLimMonth\x12(\n" +
	"\x10prod_lim_renewal\x18\x04 \x01(\x05R\x0eprodLimRenewal\"\xf0\x03\n" +
	"\x18CouponAllowancePanelInfo\x12!\n" +
	"\fcoupon_token\x18\x01 \x01(\tR\vcouponToken\x12#\n" +
	"\rcoupon_amount\x18\x02 \x01(\x01R\fcouponAmount\x12\x14\n" +
	"\x05state\x18\x03 \x01(\x05R\x05state\x12,\n" +
	"\x12full_limit_explain\x18\x04 \x01(\tR\x10fullLimitExplain\x12#\n" +
	"\rscope_explain\x18\x05 \x01(\tR\fscopeExplain\x12\x1f\n" +
	"\vfull_amount\x18\x06 \x01(\x01R\n" +
	"fullAmount\x122\n" +
	"\x15coupon_discount_price\x18\a \x01(\x01R\x13couponDiscountPrice\x12\x1d\n" +
	"\n" +
	"start_time\x18\b \x01(\x03R\tstartTime\x12\x1f\n" +
	"\vexpire_time\x18\t \x01(\x03R\n" +
	"expireTime\x12\x1a\n" +
	"\bselected\x18\n" +
	" \x01(\x05R\bselected\x12+\n" +
	"\x11disables_explains\x18\v \x01(\tR\x10disablesExplains\x12\x19\n" +
	"\border_no\x18\f \x01(\tR\aorderNo\x12\x12\n" +
	"\x04name\x18\r \x01(\tR\x04name\x12\x16\n" +
	"\x06usable\x18\x0e \x01(\x05R\x06usable\"\xa5\x02\n" +
	"\n" +
	"CouponInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\fcoupon_token\x18\x02 \x01(\tR\vcouponToken\x12\x10\n" +
	"\x03mid\x18\x03 \x01(\x03R\x03mid\x12\x14\n" +
	"\x05state\x18\x04 \x01(\x05R\x05state\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\x03R\tstartTime\x12\x1f\n" +
	"\vexpire_time\x18\x06 \x01(\x03R\n" +
	"expireTime\x12\x16\n" +
	"\x06origin\x18\a \x01(\x03R\x06origin\x12\x1f\n" +
	"\vcoupon_type\x18\b \x01(\x03R\n" +
	"couponType\x12\x19\n" +
	"\border_no\x18\t \x01(\tR\aorderNo\x12\x10\n" +
	"\x03oid\x18\n" +
	" \x01(\x03R\x03oid\x12\x16\n" +
	"\x06remark\x18\v \x01(\tR\x06remark\"!\n" +
	"\x0fCaptchaTokenReq\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\":\n" +
	"\x10CaptchaTokenResp\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"v\n" +
	"\x10UseCouponCodeReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x16\n" +
	"\x06verify\x18\x03 \x01(\tR\x06verify\x12\x0e\n" +
	"\x02ip\x18\x04 \x01(\tR\x02ip\x12\x10\n" +
	"\x03mid\x18\x05 \x01(\x03R\x03mid\"\x96\x02\n" +
	"\x11UseCouponCodeResp\x12!\n" +
	"\fcoupon_token\x18\x01 \x01(\tR\vcouponToken\x12#\n" +
	"\rcoupon_amount\x18\x02 \x01(\x01R\fcouponAmount\x12\x1f\n" +
	"\vfull_amount\x18\x03 \x01(\x01R\n" +
	"fullAmount\x124\n" +
	"\x16platform_limit_explain\x18\x04 \x01(\tR\x14platformLimitExplain\x12.\n" +
	"\x13product_limit_month\x18\x05 \x01(\x05R\x11productLimitMonth\x122\n" +
	"\x15product_limit_renewal\x18\x06 \x01(\x05R\x13productLimitRenewal\"`\n" +
	"\x1aUsableAllowanceCouponV2Req\x12\x10\n" +
	"\x03mid\x18\x01 \x01(\x03R\x03mid\x120\n" +
	"\n" +
	"price_info\x18\x02 \x03(\v2\x11.coupon.PriceInfoR\tpriceInfo\"\x7f\n" +
	"\x1bUsableAllowanceCouponV2Resp\x12\x1d\n" +
	"\n" +
	"coupon_tip\x18\x01 \x01(\tR\tcouponTip\x12A\n" +
	"\vcoupon_info\x18\x02 \x01(\v2 .coupon.CouponAllowancePanelInfoR\n" +
	"couponInfo\"\x81\x02\n" +
	"\x15UseAllowanceCouponReq\x12\x10\n" +
	"\x03mid\x18\x01 \x01(\x03R\x03mid\x12!\n" +
	"\fcoupon_token\x18\x02 \x01(\tR\vcouponToken\x12\x16\n" +
	"\x06remark\x18\x03 \x01(\tR\x06remark\x12\x19\n" +
	"\border_no\x18\x04 \x01(\tR\aorderNo\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x1a\n" +
	"\bplatform\x18\x06 \x01(\tR\bplatform\x12$\n" +
	"\x0eprod_lim_month\x18\a \x01(\x05R\fprodLimMonth\x12(\n" +
	"\x10prod_lim_renewal\x18\b \x01(\x05R\x0eprodLimRenewal\"\x18\n" +
	"\x16UseAllowanceCouponResp\"O\n" +
	"\x18CancelAllowanceCouponReq\x12\x10\n" +
	"\x03mid\x18\x01 \x01(\x03R\x03mid\x12!\n" +
	"\fcoupon_token\x18\x02 \x01(\tR\vcouponToken\"\x1b\n" +
	"\x19CancelAllowanceCouponResp\"d\n" +
	"\x18AllowanceCouponNotifyReq\x12\x10\n" +
	"\x03mid\x18\x01 \x01(\x03R\x03mid\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12\x1b\n" +
	"\tpay_state\x18\x03 \x01(\x05R\bpayState\"\x1b\n" +
	"\x19AllowanceCouponNotifyResp\":\n" +
	"\x10AllowanceListReq\x12\x10\n" +
	"\x03mid\x18\x01 \x01(\x03R\x03mid\x12\x14\n" +
	"\x05state\x18\x02 \x01(\x05R\x05state\"I\n" +
	"\x11AllowanceListResp\x124\n" +
	"\x04list\x18\x01 \x03(\v2 .coupon.CouponAllowancePanelInfoR\x04list\"G\n" +
	"\x10AllowanceInfoReq\x12\x10\n" +
	"\x03mid\x18\x01 \x01(\x03R\x03mid\x12!\n" +
	"\fcoupon_token\x18\x02 \x01(\tR\vcouponToken\"\x88\x02\n" +
	"\x11AllowanceInfoResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\fcoupon_token\x18\x02 \x01(\tR\vcouponToken\x12\x10\n" +
	"\x03mid\x18\x03 \x01(\x03R\x03mid\x12\x14\n" +
	"\x05state\x18\x04 \x01(\x05R\x05state\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\x03R\tstartTime\x12\x1f\n" +
	"\vexpire_time\x18\x06 \x01(\x03R\n" +
	"expireTime\x12\x16\n" +
	"\x06amount\x18\a \x01(\x01R\x06amount\x12\x1f\n" +
	"\vfull_amount\x18\b \x01(\x01R\n" +
	"fullAmount\x12\x1f\n" +
	"\vbatch_token\x18\t \x01(\tR\n" +
	"batchToken\"{\n" +
	"\x13ReceiveAllowanceReq\x12\x10\n" +
	"\x03mid\x18\x01 \x01(\x03R\x03mid\x12\x1f\n" +
	"\vbatch_token\x18\x02 \x01(\tR\n" +
	"batchToken\x12\x19\n" +
	"\border_no\x18\x03 \x01(\tR\aorderNo\x12\x16\n" +
	"\x06appkey\x18\x04 \x01(\tR\x06appkey\"9\n" +
	"\x14ReceiveAllowanceResp\x12!\n" +
	"\fcoupon_token\x18\x01 \x01(\tR\vcouponToken\";\n" +
	"\fUseNotifyReq\x12\x10\n" +
	"\x03mid\x18\x01 \x01(\x03R\x03mid\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\"k\n" +
	"\rUseNotifyResp\x12!\n" +
	"\fcoupon_token\x18\x01 \x01(\tR\vcouponToken\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x1f\n" +
	"\vfull_amount\x18\x03 \x01(\x01R\n" +
	"fullAmount\"B\n" +
	"\rUserCouponReq\x12\x10\n" +
	"\x03mid\x18\x01 \x01(\x03R\x03mid\x12\x1f\n" +
	"\vcoupon_type\x18\x02 \x01(\x05R\n" +
	"couponType\"8\n" +
	"\x0eUserCouponResp\x12&\n" +
	"\x04list\x18\x01 \x03(\v2\x12.coupon.CouponInfoR\x04list\"\x9f\x01\n" +
	"\fUseCouponReq\x12\x10\n" +
	"\x03mid\x18\x01 \x01(\x03R\x03mid\x12\x10\n" +
	"\x03oid\x18\x02 \x01(\x03R\x03oid\x12\x16\n" +
	"\x06remark\x18\x03 \x01(\tR\x06remark\x12\x19\n" +
	"\border_no\x18\x04 \x01(\tR\aorderNo\x12\x1f\n" +
	"\vcoupon_type\x18\x05 \x01(\x05R\n" +
	"couponType\x12\x17\n" +
	"\ause_ver\x18\x06 \x01(\x03R\x06useVer\"D\n" +
	"\rUseCouponResp\x12\x10\n" +
	"\x03ret\x18\x01 \x01(\x05R\x03ret\x12!\n" +
	"\fcoupon_token\x18\x02 \x01(\tR\vcouponToken\"D\n" +
	"\rCouponInfoReq\x12\x10\n" +
	"\x03mid\x18\x01 \x01(\x03R\x03mid\x12!\n" +
	"\fcoupon_token\x18\x02 \x01(\tR\vcouponToken\"8\n" +
	"\x0eCouponInfoResp\x12&\n" +
	"\x04info\x18\x01 \x01(\v2\x12.coupon.CouponInfoR\x04info\"W\n" +
	"\rCouponPageReq\x12\x10\n" +
	"\x03mid\x18\x01 \x01(\x03R\x03mid\x12\x14\n" +
	"\x05state\x18\x02 \x01(\x05R\x05state\x12\x0e\n" +
	"\x02pn\x18\x03 \x01(\x05R\x02pn\x12\x0e\n" +
	"\x02ps\x18\x04 \x01(\x05R\x02ps\"R\n" +
	"\x0eCouponPageResp\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\x12*\n" +
	"\x04list\x18\x02 \x03(\v2\x16.coupon.CouponPageItemR\x04list\"\x8b\x01\n" +
	"\x0eCouponPageItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04time\x18\x03 \x01(\x03R\x04time\x12\x15\n" +
	"\x06ref_id\x18\x04 \x01(\x03R\x05refId\x12\x12\n" +
	"\x04tips\x18\x05 \x01(\tR\x04tips\x12\x14\n" +
	"\x05count\x18\x06 \x01(\x03R\x05count\"H\n" +
	"\x13VideoCouponCountReq\x12\x10\n" +
	"\x03mid\x18\x01 \x01(\x03R\x03mid\x12\x1f\n" +
	"\vcoupon_type\x18\x02 \x01(\x05R\n" +
	"couponType\",\n" +
	"\x14VideoCouponCountResp\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"\xaa\x01\n" +
	"\x0fSalaryCouponReq\x12\x10\n" +
	"\x03mid\x18\x01 \x01(\x03R\x03mid\x12\x1f\n" +
	"\vcoupon_type\x18\x02 \x01(\x03R\n" +
	"couponType\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\x12\x1f\n" +
	"\vbatch_token\x18\x04 \x01(\tR\n" +
	"batchToken\x12\x15\n" +
	"\x06app_id\x18\x05 \x01(\x03R\x05appId\x12\x16\n" +
	"\x06origin\x18\x06 \x01(\x03R\x06origin\"\x12\n" +
	"\x10SalaryCouponResp\"\xb7\x01\n" +
	"\x17SalaryCouponForThirdReq\x12\x10\n" +
	"\x03mid\x18\x01 \x01(\x03R\x03mid\x12\x1f\n" +
	"\vcoupon_type\x18\x02 \x01(\x03R\n" +
	"couponType\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\x12\x1f\n" +
	"\vbatch_token\x18\x04 \x01(\tR\n" +
	"batchToken\x12\x15\n" +
	"\x06app_id\x18\x05 \x01(\x03R\x05appId\x12\x1b\n" +
	"\tunique_no\x18\x06 \x01(\tR\buniqueNo\"u\n" +
	"\x18SalaryCouponForThirdResp\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x01R\x06amount\x12\x1f\n" +
	"\vfull_amount\x18\x02 \x01(\x01R\n" +
	"fullAmount\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"/\n" +
	"\fBatchInfoReq\x12\x1f\n" +
	"\vbatch_token\x18\x01 \x01(\tR\n" +
	"batchToken\"\x9d\x03\n" +
	"\rBatchInfoResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\x03R\x05appId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1f\n" +
	"\vbatch_token\x18\x04 \x01(\tR\n" +
	"batchToken\x12\x1b\n" +
	"\tmax_count\x18\x05 \x01(\x03R\bmaxCount\x12#\n" +
	"\rcurrent_count\x18\x06 \x01(\x03R\fcurrentCount\x12\x1d\n" +
	"\n" +
	"start_time\x18\a \x01(\x03R\tstartTime\x12\x1f\n" +
	"\vexpire_time\x18\b \x01(\x03R\n" +
	"expireTime\x12\x1d\n" +
	"\n" +
	"expire_day\x18\t \x01(\x03R\texpireDay\x12\x1f\n" +
	"\vlimit_count\x18\n" +
	" \x01(\x03R\n" +
	"limitCount\x12\x1f\n" +
	"\vfull_amount\x18\v \x01(\x01R\n" +
	"fullAmount\x12\x16\n" +
	"\x06amount\x18\f \x01(\x01R\x06amount\x12\x14\n" +
	"\x05state\x18\r \x01(\x05R\x05state\x12\x1f\n" +
	"\vcoupon_type\x18\x0e \x01(\x05R\n" +
	"couponType2\xb3\n" +
	"\n" +
	"\x06Coupon\x12A\n" +
	"\fCaptchaToken\x12\x17.coupon.CaptchaTokenReq\x1a\x18.coupon.CaptchaTokenResp\x12D\n" +
	"\rUseCouponCode\x12\x18.coupon.UseCouponCodeReq\x1a\x19.coupon.UseCouponCodeResp\x12b\n" +
	"\x17UsableAllowanceCouponV2\x12\".coupon.UsableAllowanceCouponV2Req\x1a#.coupon.UsableAllowanceCouponV2Resp\x12S\n" +
	"\x12UseAllowanceCoupon\x12\x1d.coupon.UseAllowanceCouponReq\x1a\x1e.coupon.UseAllowanceCouponResp\x12\\\n" +
	"\x15CancelAllowanceCoupon\x12 .coupon.CancelAllowanceCouponReq\x1a!.coupon.CancelAllowanceCouponResp\x12\\\n" +
	"\x15AllowanceCouponNotify\x12 .coupon.AllowanceCouponNotifyReq\x1a!.coupon.AllowanceCouponNotifyResp\x12D\n" +
	"\rAllowanceList\x12\x18.coupon.AllowanceListReq\x1a\x19.coupon.AllowanceListResp\x12D\n" +
	"\rAllowanceInfo\x12\x18.coupon.AllowanceInfoReq\x1a\x19.coupon.AllowanceInfoResp\x12M\n" +
	"\x10ReceiveAllowance\x12\x1b.coupon.ReceiveAllowanceReq\x1a\x1c.coupon.ReceiveAllowanceResp\x128\n" +
	"\tUseNotify\x12\x14.coupon.UseNotifyReq\x1a\x15.coupon.UseNotifyResp\x12;\n" +
	"\n" +
	"UserCoupon\x12\x15.coupon.UserCouponReq\x1a\x16.coupon.UserCouponResp\x128\n" +
	"\tUseCoupon\x12\x14.coupon.UseCouponReq\x1a\x15.coupon.UseCouponResp\x12;\n" +
	"\n" +
	"CouponInfo\x12\x15.coupon.CouponInfoReq\x1a\x16.coupon.CouponInfoResp\x12;\n" +
	"\n" +
	"CouponPage\x12\x15.coupon.CouponPageReq\x1a\x16.coupon.CouponPageResp\x12M\n" +
	"\x10VideoCouponCount\x12\x1b.coupon.VideoCouponCountReq\x1a\x1c.coupon.VideoCouponCountResp\x12A\n" +
	"\fSalaryCoupon\x12\x17.coupon.SalaryCouponReq\x1a\x18.coupon.SalaryCouponResp\x12Y\n" +
	"\x14SalaryCouponForThird\x12\x1f.coupon.SalaryCouponForThirdReq\x1a .coupon.SalaryCouponForThirdResp\x128\n" +
	"\tBatchInfo\x12\x14.coupon.BatchInfoReq\x1a\x15.coupon.BatchInfoRespB\n" +
	"Z\b./couponb\x06proto3"

var (
	file_coupon_proto_rawDescOnce sync.Once
	file_coupon_proto_rawDescData []byte
)

func file_coupon_proto_rawDescGZIP() []byte {
	file_coupon_proto_rawDescOnce.Do(func() {
		file_coupon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coupon_proto_rawDesc), len(file_coupon_proto_rawDesc)))
	})
	return file_coupon_proto_rawDescData
}

var file_coupon_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_coupon_proto_goTypes = []any{
	(*PriceInfo)(nil),                   // 0: coupon.PriceInfo
	(*CouponAllowancePanelInfo)(nil),    // 1: coupon.CouponAllowancePanelInfo
	(*CouponInfo)(nil),                  // 2: coupon.CouponInfo
	(*CaptchaTokenReq)(nil),             // 3: coupon.CaptchaTokenReq
	(*CaptchaTokenResp)(nil),            // 4: coupon.CaptchaTokenResp
	(*UseCouponCodeReq)(nil),            // 5: coupon.UseCouponCodeReq
	(*UseCouponCodeResp)(nil),           // 6: coupon.UseCouponCodeResp
	(*UsableAllowanceCouponV2Req)(nil),  // 7: coupon.UsableAllowanceCouponV2Req
	(*UsableAllowanceCouponV2Resp)(nil), // 8: coupon.UsableAllowanceCouponV2Resp
	(*UseAllowanceCouponReq)(nil),       // 9: coupon.UseAllowanceCouponReq
	(*UseAllowanceCouponResp)(nil),      // 10: coupon.UseAllowanceCouponResp
	(*CancelAllowanceCouponReq)(nil),    // 11: coupon.CancelAllowanceCouponReq
	(*CancelAllowanceCouponResp)(nil),   // 12: coupon.CancelAllowanceCouponResp
	(*AllowanceCouponNotifyReq)(nil),    // 13: coupon.AllowanceCouponNotifyReq
	(*AllowanceCouponNotifyResp)(nil),   // 14: coupon.AllowanceCouponNotifyResp
	(*AllowanceListReq)(nil),            // 15: coupon.AllowanceListReq
	(*AllowanceListResp)(nil),           // 16: coupon.AllowanceListResp
	(*AllowanceInfoReq)(nil),            // 17: coupon.AllowanceInfoReq
	(*AllowanceInfoResp)(nil),           // 18: coupon.AllowanceInfoResp
	(*ReceiveAllowanceReq)(nil),         // 19: coupon.ReceiveAllowanceReq
	(*ReceiveAllowanceResp)(nil),        // 20: coupon.ReceiveAllowanceResp
	(*UseNotifyReq)(nil),                // 21: coupon.UseNotifyReq
	(*UseNotifyResp)(nil),               // 22: coupon.UseNotifyResp
	(*UserCouponReq)(nil),               // 23: coupon.UserCouponReq
	(*UserCouponResp)(nil),              // 24: coupon.UserCouponResp
	(*UseCouponReq)(nil),                // 25: coupon.UseCouponReq
	(*UseCouponResp)(nil),               // 26: coupon.UseCouponResp
	(*CouponInfoReq)(nil),               // 27: coupon.CouponInfoReq
	(*CouponInfoResp)(nil),              // 28: coupon.CouponInfoResp
	(*CouponPageReq)(nil),               // 29: coupon.CouponPageReq
	(*CouponPageResp)(nil),              // 30: coupon.CouponPageResp
	(*CouponPageItem)(nil),              // 31: coupon.CouponPageItem
	(*VideoCouponCountReq)(nil),         // 32: coupon.VideoCouponCountReq
	(*VideoCouponCountResp)(nil),        // 33: coupon.VideoCouponCountResp
	(*SalaryCouponReq)(nil),             // 34: coupon.SalaryCouponReq
	(*SalaryCouponResp)(nil),            // 35: coupon.SalaryCouponResp
	(*SalaryCouponForThirdReq)(nil),     // 36: coupon.SalaryCouponForThirdReq
	(*SalaryCouponForThirdResp)(nil),    // 37: coupon.SalaryCouponForThirdResp
	(*BatchInfoReq)(nil),                // 38: coupon.BatchInfoReq
	(*BatchInfoResp)(nil),               // 39: coupon.BatchInfoResp
}
var file_coupon_proto_depIdxs = []int32{
	0,  // 0: coupon.UsableAllowanceCouponV2Req.price_info:type_name -> coupon.PriceInfo
	1,  // 1: coupon.UsableAllowanceCouponV2Resp.coupon_info:type_name -> coupon.CouponAllowancePanelInfo
	1,  // 2: coupon.AllowanceListResp.list:type_name -> coupon.CouponAllowancePanelInfo
	2,  // 3: coupon.UserCouponResp.list:type_name -> coupon.CouponInfo
	2,  // 4: coupon.CouponInfoResp.info:type_name -> coupon.CouponInfo
	31, // 5: coupon.CouponPageResp.list:type_name -> coupon.CouponPageItem
	3,  // 6: coupon.Coupon.CaptchaToken:input_type -> coupon.CaptchaTokenReq
	5,  // 7: coupon.Coupon.UseCouponCode:input_type -> coupon.UseCouponCodeReq
	7,  // 8: coupon.Coupon.UsableAllowanceCouponV2:input_type -> coupon.UsableAllowanceCouponV2Req
	9,  // 9: coupon.Coupon.UseAllowanceCoupon:input_type -> coupon.UseAllowanceCouponReq
	11, // 10: coupon.Coupon.CancelAllowanceCoupon:input_type -> coupon.CancelAllowanceCouponReq
	13, // 11: coupon.Coupon.AllowanceCouponNotify:input_type -> coupon.AllowanceCouponNotifyReq
	15, // 12: coupon.Coupon.AllowanceList:input_type -> coupon.AllowanceListReq
	17, // 13: coupon.Coupon.AllowanceInfo:input_type -> coupon.AllowanceInfoReq
	19, // 14: coupon.Coupon.ReceiveAllowance:input_type -> coupon.ReceiveAllowanceReq
	21, // 15: coupon.Coupon.UseNotify:input_type -> coupon.UseNotifyReq
	23, // 16: coupon.Coupon.UserCoupon:input_type -> coupon.UserCouponReq
	25, // 17: coupon.Coupon.UseCoupon:input_type -> coupon.UseCouponReq
	27, // 18: coupon.Coupon.CouponInfo:input_type -> coupon.CouponInfoReq
	29, // 19: coupon.Coupon.CouponPage:input_type -> coupon.CouponPageReq
	32, // 20: coupon.Coupon.VideoCouponCount:input_type -> coupon.VideoCouponCountReq
	34, // 21: coupon.Coupon.SalaryCoupon:input_type -> coupon.SalaryCouponReq
	36, // 22: coupon.Coupon.SalaryCouponForThird:input_type -> coupon.SalaryCouponForThirdReq
	38, // 23: coupon.Coupon.BatchInfo:input_type -> coupon.BatchInfoReq
	4,  // 24: coupon.Coupon.CaptchaToken:output_type -> coupon.CaptchaTokenResp
	6,  // 25: coupon.Coupon.UseCouponCode:output_type -> coupon.UseCouponCodeResp
	8,  // 26: coupon.Coupon.UsableAllowanceCouponV2:output_type -> coupon.UsableAllowanceCouponV2Resp
	10, // 27: coupon.Coupon.UseAllowanceCoupon:output_type -> coupon.UseAllowanceCouponResp
	12, // 28: coupon.Coupon.CancelAllowanceCoupon:output_type -> coupon.CancelAllowanceCouponResp
	14, // 29: coupon.Coupon.AllowanceCouponNotify:output_type -> coupon.AllowanceCouponNotifyResp
	16, // 30: coupon.Coupon.AllowanceList:output_type -> coupon.AllowanceListResp
	18, // 31: coupon.Coupon.AllowanceInfo:output_type -> coupon.AllowanceInfoResp
	20, // 32: coupon.Coupon.ReceiveAllowance:output_type -> coupon.ReceiveAllowanceResp
	22, // 33: coupon.Coupon.UseNotify:output_type -> coupon.UseNotifyResp
	24, // 34: coupon.Coupon.UserCoupon:output_type -> coupon.UserCouponResp
	26, // 35: coupon.Coupon.UseCoupon:output_type -> coupon.UseCouponResp
	28, // 36: coupon.Coupon.CouponInfo:output_type -> coupon.CouponInfoResp
	30, // 37: coupon.Coupon.CouponPage:output_type -> coupon.CouponPageResp
	33, // 38: coupon.Coupon.VideoCouponCount:output_type -> coupon.VideoCouponCountResp
	35, // 39: coupon.Coupon.SalaryCoupon:output_type -> coupon.SalaryCouponResp
	37, // 40: coupon.Coupon.SalaryCouponForThird:output_type -> coupon.SalaryCouponForThirdResp
	39, // 41: coupon.Coupon.BatchInfo:output_type -> coupon.BatchInfoResp
	24, // [24:42] is the sub-list for method output_type
	6,  // [6:24] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_coupon_proto_init() }
func file_coupon_proto_init() {
	if File_coupon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coupon_proto_rawDesc), len(file_coupon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coupon_proto_goTypes,
		DependencyIndexes: file_coupon_proto_depIdxs,
		MessageInfos:      file_coupon_proto_msgTypes,
	}.Build()
	File_coupon_proto = out.File
	file_coupon_proto_goTypes = nil
	file_coupon_proto_depIdxs = nil
}
