// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: coupon.proto

package coupon

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Coupon_CaptchaToken_FullMethodName            = "/coupon.Coupon/CaptchaToken"
	Coupon_UseCouponCode_FullMethodName           = "/coupon.Coupon/UseCouponCode"
	Coupon_UsableAllowanceCouponV2_FullMethodName = "/coupon.Coupon/UsableAllowanceCouponV2"
	Coupon_UseAllowanceCoupon_FullMethodName      = "/coupon.Coupon/UseAllowanceCoupon"
	Coupon_CancelAllowanceCoupon_FullMethodName   = "/coupon.Coupon/CancelAllowanceCoupon"
	Coupon_AllowanceCouponNotify_FullMethodName   = "/coupon.Coupon/AllowanceCouponNotify"
	Coupon_AllowanceList_FullMethodName           = "/coupon.Coupon/AllowanceList"
	Coupon_AllowanceInfo_FullMethodName           = "/coupon.Coupon/AllowanceInfo"
	Coupon_ReceiveAllowance_FullMethodName        = "/coupon.Coupon/ReceiveAllowance"
	Coupon_UseNotify_FullMethodName               = "/coupon.Coupon/UseNotify"
	Coupon_UserCoupon_FullMethodName              = "/coupon.Coupon/UserCoupon"
	Coupon_UseCoupon_FullMethodName               = "/coupon.Coupon/UseCoupon"
	Coupon_CouponInfo_FullMethodName              = "/coupon.Coupon/CouponInfo"
	Coupon_CouponPage_FullMethodName              = "/coupon.Coupon/CouponPage"
	Coupon_VideoCouponCount_FullMethodName        = "/coupon.Coupon/VideoCouponCount"
	Coupon_SalaryCoupon_FullMethodName            = "/coupon.Coupon/SalaryCoupon"
	Coupon_SalaryCouponForThird_FullMethodName    = "/coupon.Coupon/SalaryCouponForThird"
	Coupon_BatchInfo_FullMethodName               = "/coupon.Coupon/BatchInfo"
)

// CouponClient is the client API for Coupon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ==================== 服务定义 ====================
type CouponClient interface {
	// ========== 验证码相关 ==========
	// 获取验证码Token
	CaptchaToken(ctx context.Context, in *CaptchaTokenReq, opts ...grpc.CallOption) (*CaptchaTokenResp, error)
	// ========== 兑换码相关 ==========
	// 使用兑换码
	UseCouponCode(ctx context.Context, in *UseCouponCodeReq, opts ...grpc.CallOption) (*UseCouponCodeResp, error)
	// ========== 代金券相关 ==========
	// 获取可用代金券V2
	UsableAllowanceCouponV2(ctx context.Context, in *UsableAllowanceCouponV2Req, opts ...grpc.CallOption) (*UsableAllowanceCouponV2Resp, error)
	// 使用代金券
	UseAllowanceCoupon(ctx context.Context, in *UseAllowanceCouponReq, opts ...grpc.CallOption) (*UseAllowanceCouponResp, error)
	// 取消使用代金券
	CancelAllowanceCoupon(ctx context.Context, in *CancelAllowanceCouponReq, opts ...grpc.CallOption) (*CancelAllowanceCouponResp, error)
	// 代金券使用通知（支付结果回调）
	AllowanceCouponNotify(ctx context.Context, in *AllowanceCouponNotifyReq, opts ...grpc.CallOption) (*AllowanceCouponNotifyResp, error)
	// 代金券列表
	AllowanceList(ctx context.Context, in *AllowanceListReq, opts ...grpc.CallOption) (*AllowanceListResp, error)
	// 代金券详情
	AllowanceInfo(ctx context.Context, in *AllowanceInfoReq, opts ...grpc.CallOption) (*AllowanceInfoResp, error)
	// 领取代金券
	ReceiveAllowance(ctx context.Context, in *ReceiveAllowanceReq, opts ...grpc.CallOption) (*ReceiveAllowanceResp, error)
	// 同步检查代金券是否可用
	UseNotify(ctx context.Context, in *UseNotifyReq, opts ...grpc.CallOption) (*UseNotifyResp, error)
	// ========== 观影券相关 ==========
	// 用户观影券列表
	UserCoupon(ctx context.Context, in *UserCouponReq, opts ...grpc.CallOption) (*UserCouponResp, error)
	// 使用观影券
	UseCoupon(ctx context.Context, in *UseCouponReq, opts ...grpc.CallOption) (*UseCouponResp, error)
	// 观影券详情
	CouponInfo(ctx context.Context, in *CouponInfoReq, opts ...grpc.CallOption) (*CouponInfoResp, error)
	// 观影券分页列表
	CouponPage(ctx context.Context, in *CouponPageReq, opts ...grpc.CallOption) (*CouponPageResp, error)
	// 观影券数量
	VideoCouponCount(ctx context.Context, in *VideoCouponCountReq, opts ...grpc.CallOption) (*VideoCouponCountResp, error)
	// ========== 发放相关 ==========
	// 发放优惠券
	SalaryCoupon(ctx context.Context, in *SalaryCouponReq, opts ...grpc.CallOption) (*SalaryCouponResp, error)
	// 第三方发放优惠券
	SalaryCouponForThird(ctx context.Context, in *SalaryCouponForThirdReq, opts ...grpc.CallOption) (*SalaryCouponForThirdResp, error)
	// ========== 批次相关 ==========
	// 批次信息
	BatchInfo(ctx context.Context, in *BatchInfoReq, opts ...grpc.CallOption) (*BatchInfoResp, error)
}

type couponClient struct {
	cc grpc.ClientConnInterface
}

func NewCouponClient(cc grpc.ClientConnInterface) CouponClient {
	return &couponClient{cc}
}

func (c *couponClient) CaptchaToken(ctx context.Context, in *CaptchaTokenReq, opts ...grpc.CallOption) (*CaptchaTokenResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CaptchaTokenResp)
	err := c.cc.Invoke(ctx, Coupon_CaptchaToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponClient) UseCouponCode(ctx context.Context, in *UseCouponCodeReq, opts ...grpc.CallOption) (*UseCouponCodeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UseCouponCodeResp)
	err := c.cc.Invoke(ctx, Coupon_UseCouponCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponClient) UsableAllowanceCouponV2(ctx context.Context, in *UsableAllowanceCouponV2Req, opts ...grpc.CallOption) (*UsableAllowanceCouponV2Resp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UsableAllowanceCouponV2Resp)
	err := c.cc.Invoke(ctx, Coupon_UsableAllowanceCouponV2_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponClient) UseAllowanceCoupon(ctx context.Context, in *UseAllowanceCouponReq, opts ...grpc.CallOption) (*UseAllowanceCouponResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UseAllowanceCouponResp)
	err := c.cc.Invoke(ctx, Coupon_UseAllowanceCoupon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponClient) CancelAllowanceCoupon(ctx context.Context, in *CancelAllowanceCouponReq, opts ...grpc.CallOption) (*CancelAllowanceCouponResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelAllowanceCouponResp)
	err := c.cc.Invoke(ctx, Coupon_CancelAllowanceCoupon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponClient) AllowanceCouponNotify(ctx context.Context, in *AllowanceCouponNotifyReq, opts ...grpc.CallOption) (*AllowanceCouponNotifyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllowanceCouponNotifyResp)
	err := c.cc.Invoke(ctx, Coupon_AllowanceCouponNotify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponClient) AllowanceList(ctx context.Context, in *AllowanceListReq, opts ...grpc.CallOption) (*AllowanceListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllowanceListResp)
	err := c.cc.Invoke(ctx, Coupon_AllowanceList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponClient) AllowanceInfo(ctx context.Context, in *AllowanceInfoReq, opts ...grpc.CallOption) (*AllowanceInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllowanceInfoResp)
	err := c.cc.Invoke(ctx, Coupon_AllowanceInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponClient) ReceiveAllowance(ctx context.Context, in *ReceiveAllowanceReq, opts ...grpc.CallOption) (*ReceiveAllowanceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReceiveAllowanceResp)
	err := c.cc.Invoke(ctx, Coupon_ReceiveAllowance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponClient) UseNotify(ctx context.Context, in *UseNotifyReq, opts ...grpc.CallOption) (*UseNotifyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UseNotifyResp)
	err := c.cc.Invoke(ctx, Coupon_UseNotify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponClient) UserCoupon(ctx context.Context, in *UserCouponReq, opts ...grpc.CallOption) (*UserCouponResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserCouponResp)
	err := c.cc.Invoke(ctx, Coupon_UserCoupon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponClient) UseCoupon(ctx context.Context, in *UseCouponReq, opts ...grpc.CallOption) (*UseCouponResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UseCouponResp)
	err := c.cc.Invoke(ctx, Coupon_UseCoupon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponClient) CouponInfo(ctx context.Context, in *CouponInfoReq, opts ...grpc.CallOption) (*CouponInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CouponInfoResp)
	err := c.cc.Invoke(ctx, Coupon_CouponInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponClient) CouponPage(ctx context.Context, in *CouponPageReq, opts ...grpc.CallOption) (*CouponPageResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CouponPageResp)
	err := c.cc.Invoke(ctx, Coupon_CouponPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponClient) VideoCouponCount(ctx context.Context, in *VideoCouponCountReq, opts ...grpc.CallOption) (*VideoCouponCountResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VideoCouponCountResp)
	err := c.cc.Invoke(ctx, Coupon_VideoCouponCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponClient) SalaryCoupon(ctx context.Context, in *SalaryCouponReq, opts ...grpc.CallOption) (*SalaryCouponResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SalaryCouponResp)
	err := c.cc.Invoke(ctx, Coupon_SalaryCoupon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponClient) SalaryCouponForThird(ctx context.Context, in *SalaryCouponForThirdReq, opts ...grpc.CallOption) (*SalaryCouponForThirdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SalaryCouponForThirdResp)
	err := c.cc.Invoke(ctx, Coupon_SalaryCouponForThird_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponClient) BatchInfo(ctx context.Context, in *BatchInfoReq, opts ...grpc.CallOption) (*BatchInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchInfoResp)
	err := c.cc.Invoke(ctx, Coupon_BatchInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CouponServer is the server API for Coupon service.
// All implementations must embed UnimplementedCouponServer
// for forward compatibility.
//
// ==================== 服务定义 ====================
type CouponServer interface {
	// ========== 验证码相关 ==========
	// 获取验证码Token
	CaptchaToken(context.Context, *CaptchaTokenReq) (*CaptchaTokenResp, error)
	// ========== 兑换码相关 ==========
	// 使用兑换码
	UseCouponCode(context.Context, *UseCouponCodeReq) (*UseCouponCodeResp, error)
	// ========== 代金券相关 ==========
	// 获取可用代金券V2
	UsableAllowanceCouponV2(context.Context, *UsableAllowanceCouponV2Req) (*UsableAllowanceCouponV2Resp, error)
	// 使用代金券
	UseAllowanceCoupon(context.Context, *UseAllowanceCouponReq) (*UseAllowanceCouponResp, error)
	// 取消使用代金券
	CancelAllowanceCoupon(context.Context, *CancelAllowanceCouponReq) (*CancelAllowanceCouponResp, error)
	// 代金券使用通知（支付结果回调）
	AllowanceCouponNotify(context.Context, *AllowanceCouponNotifyReq) (*AllowanceCouponNotifyResp, error)
	// 代金券列表
	AllowanceList(context.Context, *AllowanceListReq) (*AllowanceListResp, error)
	// 代金券详情
	AllowanceInfo(context.Context, *AllowanceInfoReq) (*AllowanceInfoResp, error)
	// 领取代金券
	ReceiveAllowance(context.Context, *ReceiveAllowanceReq) (*ReceiveAllowanceResp, error)
	// 同步检查代金券是否可用
	UseNotify(context.Context, *UseNotifyReq) (*UseNotifyResp, error)
	// ========== 观影券相关 ==========
	// 用户观影券列表
	UserCoupon(context.Context, *UserCouponReq) (*UserCouponResp, error)
	// 使用观影券
	UseCoupon(context.Context, *UseCouponReq) (*UseCouponResp, error)
	// 观影券详情
	CouponInfo(context.Context, *CouponInfoReq) (*CouponInfoResp, error)
	// 观影券分页列表
	CouponPage(context.Context, *CouponPageReq) (*CouponPageResp, error)
	// 观影券数量
	VideoCouponCount(context.Context, *VideoCouponCountReq) (*VideoCouponCountResp, error)
	// ========== 发放相关 ==========
	// 发放优惠券
	SalaryCoupon(context.Context, *SalaryCouponReq) (*SalaryCouponResp, error)
	// 第三方发放优惠券
	SalaryCouponForThird(context.Context, *SalaryCouponForThirdReq) (*SalaryCouponForThirdResp, error)
	// ========== 批次相关 ==========
	// 批次信息
	BatchInfo(context.Context, *BatchInfoReq) (*BatchInfoResp, error)
	mustEmbedUnimplementedCouponServer()
}

// UnimplementedCouponServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCouponServer struct{}

func (UnimplementedCouponServer) CaptchaToken(context.Context, *CaptchaTokenReq) (*CaptchaTokenResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CaptchaToken not implemented")
}
func (UnimplementedCouponServer) UseCouponCode(context.Context, *UseCouponCodeReq) (*UseCouponCodeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UseCouponCode not implemented")
}
func (UnimplementedCouponServer) UsableAllowanceCouponV2(context.Context, *UsableAllowanceCouponV2Req) (*UsableAllowanceCouponV2Resp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UsableAllowanceCouponV2 not implemented")
}
func (UnimplementedCouponServer) UseAllowanceCoupon(context.Context, *UseAllowanceCouponReq) (*UseAllowanceCouponResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UseAllowanceCoupon not implemented")
}
func (UnimplementedCouponServer) CancelAllowanceCoupon(context.Context, *CancelAllowanceCouponReq) (*CancelAllowanceCouponResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelAllowanceCoupon not implemented")
}
func (UnimplementedCouponServer) AllowanceCouponNotify(context.Context, *AllowanceCouponNotifyReq) (*AllowanceCouponNotifyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllowanceCouponNotify not implemented")
}
func (UnimplementedCouponServer) AllowanceList(context.Context, *AllowanceListReq) (*AllowanceListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllowanceList not implemented")
}
func (UnimplementedCouponServer) AllowanceInfo(context.Context, *AllowanceInfoReq) (*AllowanceInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllowanceInfo not implemented")
}
func (UnimplementedCouponServer) ReceiveAllowance(context.Context, *ReceiveAllowanceReq) (*ReceiveAllowanceResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveAllowance not implemented")
}
func (UnimplementedCouponServer) UseNotify(context.Context, *UseNotifyReq) (*UseNotifyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UseNotify not implemented")
}
func (UnimplementedCouponServer) UserCoupon(context.Context, *UserCouponReq) (*UserCouponResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserCoupon not implemented")
}
func (UnimplementedCouponServer) UseCoupon(context.Context, *UseCouponReq) (*UseCouponResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UseCoupon not implemented")
}
func (UnimplementedCouponServer) CouponInfo(context.Context, *CouponInfoReq) (*CouponInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CouponInfo not implemented")
}
func (UnimplementedCouponServer) CouponPage(context.Context, *CouponPageReq) (*CouponPageResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CouponPage not implemented")
}
func (UnimplementedCouponServer) VideoCouponCount(context.Context, *VideoCouponCountReq) (*VideoCouponCountResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VideoCouponCount not implemented")
}
func (UnimplementedCouponServer) SalaryCoupon(context.Context, *SalaryCouponReq) (*SalaryCouponResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SalaryCoupon not implemented")
}
func (UnimplementedCouponServer) SalaryCouponForThird(context.Context, *SalaryCouponForThirdReq) (*SalaryCouponForThirdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SalaryCouponForThird not implemented")
}
func (UnimplementedCouponServer) BatchInfo(context.Context, *BatchInfoReq) (*BatchInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchInfo not implemented")
}
func (UnimplementedCouponServer) mustEmbedUnimplementedCouponServer() {}
func (UnimplementedCouponServer) testEmbeddedByValue()                {}

// UnsafeCouponServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CouponServer will
// result in compilation errors.
type UnsafeCouponServer interface {
	mustEmbedUnimplementedCouponServer()
}

func RegisterCouponServer(s grpc.ServiceRegistrar, srv CouponServer) {
	// If the following call pancis, it indicates UnimplementedCouponServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Coupon_ServiceDesc, srv)
}

func _Coupon_CaptchaToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaptchaTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServer).CaptchaToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coupon_CaptchaToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServer).CaptchaToken(ctx, req.(*CaptchaTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coupon_UseCouponCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UseCouponCodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServer).UseCouponCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coupon_UseCouponCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServer).UseCouponCode(ctx, req.(*UseCouponCodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coupon_UsableAllowanceCouponV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsableAllowanceCouponV2Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServer).UsableAllowanceCouponV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coupon_UsableAllowanceCouponV2_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServer).UsableAllowanceCouponV2(ctx, req.(*UsableAllowanceCouponV2Req))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coupon_UseAllowanceCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UseAllowanceCouponReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServer).UseAllowanceCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coupon_UseAllowanceCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServer).UseAllowanceCoupon(ctx, req.(*UseAllowanceCouponReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coupon_CancelAllowanceCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelAllowanceCouponReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServer).CancelAllowanceCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coupon_CancelAllowanceCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServer).CancelAllowanceCoupon(ctx, req.(*CancelAllowanceCouponReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coupon_AllowanceCouponNotify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllowanceCouponNotifyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServer).AllowanceCouponNotify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coupon_AllowanceCouponNotify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServer).AllowanceCouponNotify(ctx, req.(*AllowanceCouponNotifyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coupon_AllowanceList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllowanceListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServer).AllowanceList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coupon_AllowanceList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServer).AllowanceList(ctx, req.(*AllowanceListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coupon_AllowanceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllowanceInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServer).AllowanceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coupon_AllowanceInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServer).AllowanceInfo(ctx, req.(*AllowanceInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coupon_ReceiveAllowance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceiveAllowanceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServer).ReceiveAllowance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coupon_ReceiveAllowance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServer).ReceiveAllowance(ctx, req.(*ReceiveAllowanceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coupon_UseNotify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UseNotifyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServer).UseNotify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coupon_UseNotify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServer).UseNotify(ctx, req.(*UseNotifyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coupon_UserCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCouponReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServer).UserCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coupon_UserCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServer).UserCoupon(ctx, req.(*UserCouponReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coupon_UseCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UseCouponReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServer).UseCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coupon_UseCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServer).UseCoupon(ctx, req.(*UseCouponReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coupon_CouponInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CouponInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServer).CouponInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coupon_CouponInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServer).CouponInfo(ctx, req.(*CouponInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coupon_CouponPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CouponPageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServer).CouponPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coupon_CouponPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServer).CouponPage(ctx, req.(*CouponPageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coupon_VideoCouponCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VideoCouponCountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServer).VideoCouponCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coupon_VideoCouponCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServer).VideoCouponCount(ctx, req.(*VideoCouponCountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coupon_SalaryCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SalaryCouponReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServer).SalaryCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coupon_SalaryCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServer).SalaryCoupon(ctx, req.(*SalaryCouponReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coupon_SalaryCouponForThird_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SalaryCouponForThirdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServer).SalaryCouponForThird(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coupon_SalaryCouponForThird_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServer).SalaryCouponForThird(ctx, req.(*SalaryCouponForThirdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coupon_BatchInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServer).BatchInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coupon_BatchInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServer).BatchInfo(ctx, req.(*BatchInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Coupon_ServiceDesc is the grpc.ServiceDesc for Coupon service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Coupon_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coupon.Coupon",
	HandlerType: (*CouponServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CaptchaToken",
			Handler:    _Coupon_CaptchaToken_Handler,
		},
		{
			MethodName: "UseCouponCode",
			Handler:    _Coupon_UseCouponCode_Handler,
		},
		{
			MethodName: "UsableAllowanceCouponV2",
			Handler:    _Coupon_UsableAllowanceCouponV2_Handler,
		},
		{
			MethodName: "UseAllowanceCoupon",
			Handler:    _Coupon_UseAllowanceCoupon_Handler,
		},
		{
			MethodName: "CancelAllowanceCoupon",
			Handler:    _Coupon_CancelAllowanceCoupon_Handler,
		},
		{
			MethodName: "AllowanceCouponNotify",
			Handler:    _Coupon_AllowanceCouponNotify_Handler,
		},
		{
			MethodName: "AllowanceList",
			Handler:    _Coupon_AllowanceList_Handler,
		},
		{
			MethodName: "AllowanceInfo",
			Handler:    _Coupon_AllowanceInfo_Handler,
		},
		{
			MethodName: "ReceiveAllowance",
			Handler:    _Coupon_ReceiveAllowance_Handler,
		},
		{
			MethodName: "UseNotify",
			Handler:    _Coupon_UseNotify_Handler,
		},
		{
			MethodName: "UserCoupon",
			Handler:    _Coupon_UserCoupon_Handler,
		},
		{
			MethodName: "UseCoupon",
			Handler:    _Coupon_UseCoupon_Handler,
		},
		{
			MethodName: "CouponInfo",
			Handler:    _Coupon_CouponInfo_Handler,
		},
		{
			MethodName: "CouponPage",
			Handler:    _Coupon_CouponPage_Handler,
		},
		{
			MethodName: "VideoCouponCount",
			Handler:    _Coupon_VideoCouponCount_Handler,
		},
		{
			MethodName: "SalaryCoupon",
			Handler:    _Coupon_SalaryCoupon_Handler,
		},
		{
			MethodName: "SalaryCouponForThird",
			Handler:    _Coupon_SalaryCouponForThird_Handler,
		},
		{
			MethodName: "BatchInfo",
			Handler:    _Coupon_BatchInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coupon.proto",
}
