// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: video.proto

package video

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ========== 获取视频信息 ==========
type GetVideoInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vid           int64                  `protobuf:"varint,1,opt,name=vid,proto3" json:"vid,omitempty"` // 视频ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoInfoReq) Reset() {
	*x = GetVideoInfoReq{}
	mi := &file_video_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoInfoReq) ProtoMessage() {}

func (x *GetVideoInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoInfoReq.ProtoReflect.Descriptor instead.
func (*GetVideoInfoReq) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{0}
}

func (x *GetVideoInfoReq) GetVid() int64 {
	if x != nil {
		return x.Vid
	}
	return 0
}

type GetVideoInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *VideoInfo             `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoInfoResp) Reset() {
	*x = GetVideoInfoResp{}
	mi := &file_video_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoInfoResp) ProtoMessage() {}

func (x *GetVideoInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoInfoResp.ProtoReflect.Descriptor instead.
func (*GetVideoInfoResp) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{1}
}

func (x *GetVideoInfoResp) GetInfo() *VideoInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// ========== 批量获取视频信息 ==========
type BatchGetVideoInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vids          []int64                `protobuf:"varint,1,rep,packed,name=vids,proto3" json:"vids,omitempty"` // 视频ID列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetVideoInfoReq) Reset() {
	*x = BatchGetVideoInfoReq{}
	mi := &file_video_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetVideoInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetVideoInfoReq) ProtoMessage() {}

func (x *BatchGetVideoInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetVideoInfoReq.ProtoReflect.Descriptor instead.
func (*BatchGetVideoInfoReq) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{2}
}

func (x *BatchGetVideoInfoReq) GetVids() []int64 {
	if x != nil {
		return x.Vids
	}
	return nil
}

type BatchGetVideoInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Infos         map[int64]*VideoInfo   `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // key: vid, value: VideoInfo
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetVideoInfoResp) Reset() {
	*x = BatchGetVideoInfoResp{}
	mi := &file_video_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetVideoInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetVideoInfoResp) ProtoMessage() {}

func (x *BatchGetVideoInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetVideoInfoResp.ProtoReflect.Descriptor instead.
func (*BatchGetVideoInfoResp) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{3}
}

func (x *BatchGetVideoInfoResp) GetInfos() map[int64]*VideoInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

// ========== 获取视频列表（游标分页）==========
type GetVideoListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastVid       int64                  `protobuf:"varint,1,opt,name=last_vid,json=lastVid,proto3" json:"last_vid,omitempty"` // 游标（上一批的最后一个vid）
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                    // 每页数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoListReq) Reset() {
	*x = GetVideoListReq{}
	mi := &file_video_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoListReq) ProtoMessage() {}

func (x *GetVideoListReq) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoListReq.ProtoReflect.Descriptor instead.
func (*GetVideoListReq) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{4}
}

func (x *GetVideoListReq) GetLastVid() int64 {
	if x != nil {
		return x.LastVid
	}
	return 0
}

func (x *GetVideoListReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetVideoListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*VideoData           `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoListResp) Reset() {
	*x = GetVideoListResp{}
	mi := &file_video_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoListResp) ProtoMessage() {}

func (x *GetVideoListResp) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoListResp.ProtoReflect.Descriptor instead.
func (*GetVideoListResp) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{5}
}

func (x *GetVideoListResp) GetList() []*VideoData {
	if x != nil {
		return x.List
	}
	return nil
}

// ========== 获取视频统计数据 ==========
type GetVideoStatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vid           int64                  `protobuf:"varint,1,opt,name=vid,proto3" json:"vid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoStatReq) Reset() {
	*x = GetVideoStatReq{}
	mi := &file_video_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoStatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoStatReq) ProtoMessage() {}

func (x *GetVideoStatReq) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoStatReq.ProtoReflect.Descriptor instead.
func (*GetVideoStatReq) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{6}
}

func (x *GetVideoStatReq) GetVid() int64 {
	if x != nil {
		return x.Vid
	}
	return 0
}

type GetVideoStatResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stat          *VideoStat             `protobuf:"bytes,1,opt,name=stat,proto3" json:"stat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoStatResp) Reset() {
	*x = GetVideoStatResp{}
	mi := &file_video_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoStatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoStatResp) ProtoMessage() {}

func (x *GetVideoStatResp) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoStatResp.ProtoReflect.Descriptor instead.
func (*GetVideoStatResp) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{7}
}

func (x *GetVideoStatResp) GetStat() *VideoStat {
	if x != nil {
		return x.Stat
	}
	return nil
}

// ========== 批量获取视频统计数据 ==========
type BatchGetVideoStatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vids          []int64                `protobuf:"varint,1,rep,packed,name=vids,proto3" json:"vids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetVideoStatReq) Reset() {
	*x = BatchGetVideoStatReq{}
	mi := &file_video_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetVideoStatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetVideoStatReq) ProtoMessage() {}

func (x *BatchGetVideoStatReq) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetVideoStatReq.ProtoReflect.Descriptor instead.
func (*BatchGetVideoStatReq) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{8}
}

func (x *BatchGetVideoStatReq) GetVids() []int64 {
	if x != nil {
		return x.Vids
	}
	return nil
}

type BatchGetVideoStatResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         map[int64]*VideoStat   `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // key: vid, value: VideoStat
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetVideoStatResp) Reset() {
	*x = BatchGetVideoStatResp{}
	mi := &file_video_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetVideoStatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetVideoStatResp) ProtoMessage() {}

func (x *BatchGetVideoStatResp) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetVideoStatResp.ProtoReflect.Descriptor instead.
func (*BatchGetVideoStatResp) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{9}
}

func (x *BatchGetVideoStatResp) GetStats() map[int64]*VideoStat {
	if x != nil {
		return x.Stats
	}
	return nil
}

// 视频信息
type VideoInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vid           int64                  `protobuf:"varint,1,opt,name=vid,proto3" json:"vid,omitempty"`                                // 视频ID
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                             // 标题
	Cover         string                 `protobuf:"bytes,3,opt,name=cover,proto3" json:"cover,omitempty"`                             // 封面
	AuthorId      int64                  `protobuf:"varint,4,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`      // 作者ID
	AuthorName    string                 `protobuf:"bytes,5,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"` // 作者名称
	RegionId      int64                  `protobuf:"varint,6,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`      // 分区ID
	PubTime       int64                  `protobuf:"varint,7,opt,name=pub_time,json=pubTime,proto3" json:"pub_time,omitempty"`         // 发布时间（Unix时间戳）
	Duration      int32                  `protobuf:"varint,8,opt,name=duration,proto3" json:"duration,omitempty"`                      // 时长（秒）
	Desc          string                 `protobuf:"bytes,9,opt,name=desc,proto3" json:"desc,omitempty"`                               // 简介
	State         int32                  `protobuf:"varint,10,opt,name=state,proto3" json:"state,omitempty"`                           // 状态：0-正常，1-删除
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoInfo) Reset() {
	*x = VideoInfo{}
	mi := &file_video_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoInfo) ProtoMessage() {}

func (x *VideoInfo) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoInfo.ProtoReflect.Descriptor instead.
func (*VideoInfo) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{10}
}

func (x *VideoInfo) GetVid() int64 {
	if x != nil {
		return x.Vid
	}
	return 0
}

func (x *VideoInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VideoInfo) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *VideoInfo) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *VideoInfo) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *VideoInfo) GetRegionId() int64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *VideoInfo) GetPubTime() int64 {
	if x != nil {
		return x.PubTime
	}
	return 0
}

func (x *VideoInfo) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *VideoInfo) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *VideoInfo) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

// 视频统计数据
type VideoStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vid           int64                  `protobuf:"varint,1,opt,name=vid,proto3" json:"vid,omitempty"`         // 视频ID
	View          int64                  `protobuf:"varint,2,opt,name=view,proto3" json:"view,omitempty"`       // 播放数
	Like          int64                  `protobuf:"varint,3,opt,name=like,proto3" json:"like,omitempty"`       // 点赞数
	Coin          int64                  `protobuf:"varint,4,opt,name=coin,proto3" json:"coin,omitempty"`       // 硬币数
	Fav           int64                  `protobuf:"varint,5,opt,name=fav,proto3" json:"fav,omitempty"`         // 收藏数
	Share         int64                  `protobuf:"varint,6,opt,name=share,proto3" json:"share,omitempty"`     // 分享数
	Reply         int64                  `protobuf:"varint,7,opt,name=reply,proto3" json:"reply,omitempty"`     // 评论数
	Danmaku       int64                  `protobuf:"varint,8,opt,name=danmaku,proto3" json:"danmaku,omitempty"` // 弹幕数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoStat) Reset() {
	*x = VideoStat{}
	mi := &file_video_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoStat) ProtoMessage() {}

func (x *VideoStat) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoStat.ProtoReflect.Descriptor instead.
func (*VideoStat) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{11}
}

func (x *VideoStat) GetVid() int64 {
	if x != nil {
		return x.Vid
	}
	return 0
}

func (x *VideoStat) GetView() int64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *VideoStat) GetLike() int64 {
	if x != nil {
		return x.Like
	}
	return 0
}

func (x *VideoStat) GetCoin() int64 {
	if x != nil {
		return x.Coin
	}
	return 0
}

func (x *VideoStat) GetFav() int64 {
	if x != nil {
		return x.Fav
	}
	return 0
}

func (x *VideoStat) GetShare() int64 {
	if x != nil {
		return x.Share
	}
	return 0
}

func (x *VideoStat) GetReply() int64 {
	if x != nil {
		return x.Reply
	}
	return 0
}

func (x *VideoStat) GetDanmaku() int64 {
	if x != nil {
		return x.Danmaku
	}
	return 0
}

// 视频完整数据（信息+统计）
type VideoData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *VideoInfo             `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Stat          *VideoStat             `protobuf:"bytes,2,opt,name=stat,proto3" json:"stat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoData) Reset() {
	*x = VideoData{}
	mi := &file_video_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoData) ProtoMessage() {}

func (x *VideoData) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoData.ProtoReflect.Descriptor instead.
func (*VideoData) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{12}
}

func (x *VideoData) GetInfo() *VideoInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *VideoData) GetStat() *VideoStat {
	if x != nil {
		return x.Stat
	}
	return nil
}

var File_video_proto protoreflect.FileDescriptor

const file_video_proto_rawDesc = "" +
	"\n" +
	"\vvideo.proto\x12\x05video\"#\n" +
	"\x0fGetVideoInfoReq\x12\x10\n" +
	"\x03vid\x18\x01 \x01(\x03R\x03vid\"8\n" +
	"\x10GetVideoInfoResp\x12$\n" +
	"\x04info\x18\x01 \x01(\v2\x10.video.VideoInfoR\x04info\"*\n" +
	"\x14BatchGetVideoInfoReq\x12\x12\n" +
	"\x04vids\x18\x01 \x03(\x03R\x04vids\"\xa2\x01\n" +
	"\x15BatchGetVideoInfoResp\x12=\n" +
	"\x05infos\x18\x01 \x03(\v2'.video.BatchGetVideoInfoResp.InfosEntryR\x05infos\x1aJ\n" +
	"\n" +
	"InfosEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.video.VideoInfoR\x05value:\x028\x01\"B\n" +
	"\x0fGetVideoListReq\x12\x19\n" +
	"\blast_vid\x18\x01 \x01(\x03R\alastVid\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"8\n" +
	"\x10GetVideoListResp\x12$\n" +
	"\x04list\x18\x01 \x03(\v2\x10.video.VideoDataR\x04list\"#\n" +
	"\x0fGetVideoStatReq\x12\x10\n" +
	"\x03vid\x18\x01 \x01(\x03R\x03vid\"8\n" +
	"\x10GetVideoStatResp\x12$\n" +
	"\x04stat\x18\x01 \x01(\v2\x10.video.VideoStatR\x04stat\"*\n" +
	"\x14BatchGetVideoStatReq\x12\x12\n" +
	"\x04vids\x18\x01 \x03(\x03R\x04vids\"\xa2\x01\n" +
	"\x15BatchGetVideoStatResp\x12=\n" +
	"\x05stats\x18\x01 \x03(\v2'.video.BatchGetVideoStatResp.StatsEntryR\x05stats\x1aJ\n" +
	"\n" +
	"StatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.video.VideoStatR\x05value:\x028\x01\"\x85\x02\n" +
	"\tVideoInfo\x12\x10\n" +
	"\x03vid\x18\x01 \x01(\x03R\x03vid\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05cover\x18\x03 \x01(\tR\x05cover\x12\x1b\n" +
	"\tauthor_id\x18\x04 \x01(\x03R\bauthorId\x12\x1f\n" +
	"\vauthor_name\x18\x05 \x01(\tR\n" +
	"authorName\x12\x1b\n" +
	"\tregion_id\x18\x06 \x01(\x03R\bregionId\x12\x19\n" +
	"\bpub_time\x18\a \x01(\x03R\apubTime\x12\x1a\n" +
	"\bduration\x18\b \x01(\x05R\bduration\x12\x12\n" +
	"\x04desc\x18\t \x01(\tR\x04desc\x12\x14\n" +
	"\x05state\x18\n" +
	" \x01(\x05R\x05state\"\xb1\x01\n" +
	"\tVideoStat\x12\x10\n" +
	"\x03vid\x18\x01 \x01(\x03R\x03vid\x12\x12\n" +
	"\x04view\x18\x02 \x01(\x03R\x04view\x12\x12\n" +
	"\x04like\x18\x03 \x01(\x03R\x04like\x12\x12\n" +
	"\x04coin\x18\x04 \x01(\x03R\x04coin\x12\x10\n" +
	"\x03fav\x18\x05 \x01(\x03R\x03fav\x12\x14\n" +
	"\x05share\x18\x06 \x01(\x03R\x05share\x12\x14\n" +
	"\x05reply\x18\a \x01(\x03R\x05reply\x12\x18\n" +
	"\adanmaku\x18\b \x01(\x03R\adanmaku\"W\n" +
	"\tVideoData\x12$\n" +
	"\x04info\x18\x01 \x01(\v2\x10.video.VideoInfoR\x04info\x12$\n" +
	"\x04stat\x18\x02 \x01(\v2\x10.video.VideoStatR\x04stat2\xea\x02\n" +
	"\x05Video\x12?\n" +
	"\fGetVideoInfo\x12\x16.video.GetVideoInfoReq\x1a\x17.video.GetVideoInfoResp\x12N\n" +
	"\x11BatchGetVideoInfo\x12\x1b.video.BatchGetVideoInfoReq\x1a\x1c.video.BatchGetVideoInfoResp\x12?\n" +
	"\fGetVideoList\x12\x16.video.GetVideoListReq\x1a\x17.video.GetVideoListResp\x12?\n" +
	"\fGetVideoStat\x12\x16.video.GetVideoStatReq\x1a\x17.video.GetVideoStatResp\x12N\n" +
	"\x11BatchGetVideoStat\x12\x1b.video.BatchGetVideoStatReq\x1a\x1c.video.BatchGetVideoStatRespB\tZ\a./videob\x06proto3"

var (
	file_video_proto_rawDescOnce sync.Once
	file_video_proto_rawDescData []byte
)

func file_video_proto_rawDescGZIP() []byte {
	file_video_proto_rawDescOnce.Do(func() {
		file_video_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_video_proto_rawDesc), len(file_video_proto_rawDesc)))
	})
	return file_video_proto_rawDescData
}

var file_video_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_video_proto_goTypes = []any{
	(*GetVideoInfoReq)(nil),       // 0: video.GetVideoInfoReq
	(*GetVideoInfoResp)(nil),      // 1: video.GetVideoInfoResp
	(*BatchGetVideoInfoReq)(nil),  // 2: video.BatchGetVideoInfoReq
	(*BatchGetVideoInfoResp)(nil), // 3: video.BatchGetVideoInfoResp
	(*GetVideoListReq)(nil),       // 4: video.GetVideoListReq
	(*GetVideoListResp)(nil),      // 5: video.GetVideoListResp
	(*GetVideoStatReq)(nil),       // 6: video.GetVideoStatReq
	(*GetVideoStatResp)(nil),      // 7: video.GetVideoStatResp
	(*BatchGetVideoStatReq)(nil),  // 8: video.BatchGetVideoStatReq
	(*BatchGetVideoStatResp)(nil), // 9: video.BatchGetVideoStatResp
	(*VideoInfo)(nil),             // 10: video.VideoInfo
	(*VideoStat)(nil),             // 11: video.VideoStat
	(*VideoData)(nil),             // 12: video.VideoData
	nil,                           // 13: video.BatchGetVideoInfoResp.InfosEntry
	nil,                           // 14: video.BatchGetVideoStatResp.StatsEntry
}
var file_video_proto_depIdxs = []int32{
	10, // 0: video.GetVideoInfoResp.info:type_name -> video.VideoInfo
	13, // 1: video.BatchGetVideoInfoResp.infos:type_name -> video.BatchGetVideoInfoResp.InfosEntry
	12, // 2: video.GetVideoListResp.list:type_name -> video.VideoData
	11, // 3: video.GetVideoStatResp.stat:type_name -> video.VideoStat
	14, // 4: video.BatchGetVideoStatResp.stats:type_name -> video.BatchGetVideoStatResp.StatsEntry
	10, // 5: video.VideoData.info:type_name -> video.VideoInfo
	11, // 6: video.VideoData.stat:type_name -> video.VideoStat
	10, // 7: video.BatchGetVideoInfoResp.InfosEntry.value:type_name -> video.VideoInfo
	11, // 8: video.BatchGetVideoStatResp.StatsEntry.value:type_name -> video.VideoStat
	0,  // 9: video.Video.GetVideoInfo:input_type -> video.GetVideoInfoReq
	2,  // 10: video.Video.BatchGetVideoInfo:input_type -> video.BatchGetVideoInfoReq
	4,  // 11: video.Video.GetVideoList:input_type -> video.GetVideoListReq
	6,  // 12: video.Video.GetVideoStat:input_type -> video.GetVideoStatReq
	8,  // 13: video.Video.BatchGetVideoStat:input_type -> video.BatchGetVideoStatReq
	1,  // 14: video.Video.GetVideoInfo:output_type -> video.GetVideoInfoResp
	3,  // 15: video.Video.BatchGetVideoInfo:output_type -> video.BatchGetVideoInfoResp
	5,  // 16: video.Video.GetVideoList:output_type -> video.GetVideoListResp
	7,  // 17: video.Video.GetVideoStat:output_type -> video.GetVideoStatResp
	9,  // 18: video.Video.BatchGetVideoStat:output_type -> video.BatchGetVideoStatResp
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_video_proto_init() }
func file_video_proto_init() {
	if File_video_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_video_proto_rawDesc), len(file_video_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_video_proto_goTypes,
		DependencyIndexes: file_video_proto_depIdxs,
		MessageInfos:      file_video_proto_msgTypes,
	}.Build()
	File_video_proto = out.File
	file_video_proto_goTypes = nil
	file_video_proto_depIdxs = nil
}
