// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: video.proto

package video

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Video_GetVideoInfo_FullMethodName      = "/video.Video/GetVideoInfo"
	Video_BatchGetVideoInfo_FullMethodName = "/video.Video/BatchGetVideoInfo"
	Video_GetVideoList_FullMethodName      = "/video.Video/GetVideoList"
	Video_GetVideoStat_FullMethodName      = "/video.Video/GetVideoStat"
	Video_BatchGetVideoStat_FullMethodName = "/video.Video/BatchGetVideoStat"
)

// VideoClient is the client API for Video service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 视频服务
type VideoClient interface {
	// 获取视频信息
	GetVideoInfo(ctx context.Context, in *GetVideoInfoReq, opts ...grpc.CallOption) (*GetVideoInfoResp, error)
	// 批量获取视频信息
	BatchGetVideoInfo(ctx context.Context, in *BatchGetVideoInfoReq, opts ...grpc.CallOption) (*BatchGetVideoInfoResp, error)
	// 获取视频列表（游标分页）
	GetVideoList(ctx context.Context, in *GetVideoListReq, opts ...grpc.CallOption) (*GetVideoListResp, error)
	// 获取视频统计数据
	GetVideoStat(ctx context.Context, in *GetVideoStatReq, opts ...grpc.CallOption) (*GetVideoStatResp, error)
	// 批量获取视频统计数据
	BatchGetVideoStat(ctx context.Context, in *BatchGetVideoStatReq, opts ...grpc.CallOption) (*BatchGetVideoStatResp, error)
}

type videoClient struct {
	cc grpc.ClientConnInterface
}

func NewVideoClient(cc grpc.ClientConnInterface) VideoClient {
	return &videoClient{cc}
}

func (c *videoClient) GetVideoInfo(ctx context.Context, in *GetVideoInfoReq, opts ...grpc.CallOption) (*GetVideoInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVideoInfoResp)
	err := c.cc.Invoke(ctx, Video_GetVideoInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) BatchGetVideoInfo(ctx context.Context, in *BatchGetVideoInfoReq, opts ...grpc.CallOption) (*BatchGetVideoInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetVideoInfoResp)
	err := c.cc.Invoke(ctx, Video_BatchGetVideoInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) GetVideoList(ctx context.Context, in *GetVideoListReq, opts ...grpc.CallOption) (*GetVideoListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVideoListResp)
	err := c.cc.Invoke(ctx, Video_GetVideoList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) GetVideoStat(ctx context.Context, in *GetVideoStatReq, opts ...grpc.CallOption) (*GetVideoStatResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVideoStatResp)
	err := c.cc.Invoke(ctx, Video_GetVideoStat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) BatchGetVideoStat(ctx context.Context, in *BatchGetVideoStatReq, opts ...grpc.CallOption) (*BatchGetVideoStatResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetVideoStatResp)
	err := c.cc.Invoke(ctx, Video_BatchGetVideoStat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VideoServer is the server API for Video service.
// All implementations must embed UnimplementedVideoServer
// for forward compatibility.
//
// 视频服务
type VideoServer interface {
	// 获取视频信息
	GetVideoInfo(context.Context, *GetVideoInfoReq) (*GetVideoInfoResp, error)
	// 批量获取视频信息
	BatchGetVideoInfo(context.Context, *BatchGetVideoInfoReq) (*BatchGetVideoInfoResp, error)
	// 获取视频列表（游标分页）
	GetVideoList(context.Context, *GetVideoListReq) (*GetVideoListResp, error)
	// 获取视频统计数据
	GetVideoStat(context.Context, *GetVideoStatReq) (*GetVideoStatResp, error)
	// 批量获取视频统计数据
	BatchGetVideoStat(context.Context, *BatchGetVideoStatReq) (*BatchGetVideoStatResp, error)
	mustEmbedUnimplementedVideoServer()
}

// UnimplementedVideoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVideoServer struct{}

func (UnimplementedVideoServer) GetVideoInfo(context.Context, *GetVideoInfoReq) (*GetVideoInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVideoInfo not implemented")
}
func (UnimplementedVideoServer) BatchGetVideoInfo(context.Context, *BatchGetVideoInfoReq) (*BatchGetVideoInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchGetVideoInfo not implemented")
}
func (UnimplementedVideoServer) GetVideoList(context.Context, *GetVideoListReq) (*GetVideoListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVideoList not implemented")
}
func (UnimplementedVideoServer) GetVideoStat(context.Context, *GetVideoStatReq) (*GetVideoStatResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVideoStat not implemented")
}
func (UnimplementedVideoServer) BatchGetVideoStat(context.Context, *BatchGetVideoStatReq) (*BatchGetVideoStatResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchGetVideoStat not implemented")
}
func (UnimplementedVideoServer) mustEmbedUnimplementedVideoServer() {}
func (UnimplementedVideoServer) testEmbeddedByValue()               {}

// UnsafeVideoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VideoServer will
// result in compilation errors.
type UnsafeVideoServer interface {
	mustEmbedUnimplementedVideoServer()
}

func RegisterVideoServer(s grpc.ServiceRegistrar, srv VideoServer) {
	// If the following call pancis, it indicates UnimplementedVideoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Video_ServiceDesc, srv)
}

func _Video_GetVideoInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVideoInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).GetVideoInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_GetVideoInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).GetVideoInfo(ctx, req.(*GetVideoInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_BatchGetVideoInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetVideoInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).BatchGetVideoInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_BatchGetVideoInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).BatchGetVideoInfo(ctx, req.(*BatchGetVideoInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_GetVideoList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVideoListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).GetVideoList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_GetVideoList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).GetVideoList(ctx, req.(*GetVideoListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_GetVideoStat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVideoStatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).GetVideoStat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_GetVideoStat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).GetVideoStat(ctx, req.(*GetVideoStatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_BatchGetVideoStat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetVideoStatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).BatchGetVideoStat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_BatchGetVideoStat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).BatchGetVideoStat(ctx, req.(*BatchGetVideoStatReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Video_ServiceDesc is the grpc.ServiceDesc for Video service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Video_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "video.Video",
	HandlerType: (*VideoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVideoInfo",
			Handler:    _Video_GetVideoInfo_Handler,
		},
		{
			MethodName: "BatchGetVideoInfo",
			Handler:    _Video_BatchGetVideoInfo_Handler,
		},
		{
			MethodName: "GetVideoList",
			Handler:    _Video_GetVideoList_Handler,
		},
		{
			MethodName: "GetVideoStat",
			Handler:    _Video_GetVideoStat_Handler,
		},
		{
			MethodName: "BatchGetVideoStat",
			Handler:    _Video_BatchGetVideoStat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "video.proto",
}
