// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: wallet.proto

package wallet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RechargeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`                                         // 用户ID
	CoinType      string                 `protobuf:"bytes,2,opt,name=coin_type,json=coinType,proto3" json:"coin_type,omitempty"`                // 币种：gold/iap_gold
	CoinNum       int64                  `protobuf:"varint,3,opt,name=coin_num,json=coinNum,proto3" json:"coin_num,omitempty"`                  // 充值金额
	TransactionId string                 `protobuf:"bytes,4,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"` // 交易ID（幂等性保证）
	ExtendTid     string                 `protobuf:"bytes,5,opt,name=extend_tid,json=extendTid,proto3" json:"extend_tid,omitempty"`             // 扩展交易ID
	Platform      string                 `protobuf:"bytes,6,opt,name=platform,proto3" json:"platform,omitempty"`                                // 平台：ios/android/pc/h5
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                             // 时间戳
	BizCode       string                 `protobuf:"bytes,8,opt,name=biz_code,json=bizCode,proto3" json:"biz_code,omitempty"`                   // 业务代码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RechargeReq) Reset() {
	*x = RechargeReq{}
	mi := &file_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RechargeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RechargeReq) ProtoMessage() {}

func (x *RechargeReq) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RechargeReq.ProtoReflect.Descriptor instead.
func (*RechargeReq) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *RechargeReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *RechargeReq) GetCoinType() string {
	if x != nil {
		return x.CoinType
	}
	return ""
}

func (x *RechargeReq) GetCoinNum() int64 {
	if x != nil {
		return x.CoinNum
	}
	return 0
}

func (x *RechargeReq) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *RechargeReq) GetExtendTid() string {
	if x != nil {
		return x.ExtendTid
	}
	return ""
}

func (x *RechargeReq) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *RechargeReq) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *RechargeReq) GetBizCode() string {
	if x != nil {
		return x.BizCode
	}
	return ""
}

type RechargeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gold          int64                  `protobuf:"varint,1,opt,name=gold,proto3" json:"gold,omitempty"`                      // 金瓜子余额
	IapGold       int64                  `protobuf:"varint,2,opt,name=iap_gold,json=iapGold,proto3" json:"iap_gold,omitempty"` // IAP金瓜子余额
	Silver        int64                  `protobuf:"varint,3,opt,name=silver,proto3" json:"silver,omitempty"`                  // 银瓜子余额
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RechargeResp) Reset() {
	*x = RechargeResp{}
	mi := &file_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RechargeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RechargeResp) ProtoMessage() {}

func (x *RechargeResp) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RechargeResp.ProtoReflect.Descriptor instead.
func (*RechargeResp) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *RechargeResp) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *RechargeResp) GetIapGold() int64 {
	if x != nil {
		return x.IapGold
	}
	return 0
}

func (x *RechargeResp) GetSilver() int64 {
	if x != nil {
		return x.Silver
	}
	return 0
}

type PayReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`                                         // 用户ID
	CoinType      string                 `protobuf:"bytes,2,opt,name=coin_type,json=coinType,proto3" json:"coin_type,omitempty"`                // 消费币种
	CoinNum       int64                  `protobuf:"varint,3,opt,name=coin_num,json=coinNum,proto3" json:"coin_num,omitempty"`                  // 消费金额
	TransactionId string                 `protobuf:"bytes,4,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"` // 交易ID
	ExtendTid     string                 `protobuf:"bytes,5,opt,name=extend_tid,json=extendTid,proto3" json:"extend_tid,omitempty"`             // 扩展交易ID
	Platform      string                 `protobuf:"bytes,6,opt,name=platform,proto3" json:"platform,omitempty"`                                // 平台
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                             // 时间戳
	BizCode       string                 `protobuf:"bytes,8,opt,name=biz_code,json=bizCode,proto3" json:"biz_code,omitempty"`                   // 业务代码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayReq) Reset() {
	*x = PayReq{}
	mi := &file_wallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayReq) ProtoMessage() {}

func (x *PayReq) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayReq.ProtoReflect.Descriptor instead.
func (*PayReq) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *PayReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PayReq) GetCoinType() string {
	if x != nil {
		return x.CoinType
	}
	return ""
}

func (x *PayReq) GetCoinNum() int64 {
	if x != nil {
		return x.CoinNum
	}
	return 0
}

func (x *PayReq) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *PayReq) GetExtendTid() string {
	if x != nil {
		return x.ExtendTid
	}
	return ""
}

func (x *PayReq) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *PayReq) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PayReq) GetBizCode() string {
	if x != nil {
		return x.BizCode
	}
	return ""
}

type PayResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gold          int64                  `protobuf:"varint,1,opt,name=gold,proto3" json:"gold,omitempty"`                      // 金瓜子余额
	IapGold       int64                  `protobuf:"varint,2,opt,name=iap_gold,json=iapGold,proto3" json:"iap_gold,omitempty"` // IAP金瓜子余额
	Silver        int64                  `protobuf:"varint,3,opt,name=silver,proto3" json:"silver,omitempty"`                  // 银瓜子余额
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayResp) Reset() {
	*x = PayResp{}
	mi := &file_wallet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayResp) ProtoMessage() {}

func (x *PayResp) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayResp.ProtoReflect.Descriptor instead.
func (*PayResp) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{3}
}

func (x *PayResp) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *PayResp) GetIapGold() int64 {
	if x != nil {
		return x.IapGold
	}
	return 0
}

func (x *PayResp) GetSilver() int64 {
	if x != nil {
		return x.Silver
	}
	return 0
}

type ExchangeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`                                         // 用户ID
	SrcCoinType   string                 `protobuf:"bytes,2,opt,name=src_coin_type,json=srcCoinType,proto3" json:"src_coin_type,omitempty"`     // 源币种
	SrcCoinNum    int64                  `protobuf:"varint,3,opt,name=src_coin_num,json=srcCoinNum,proto3" json:"src_coin_num,omitempty"`       // 源币种数量
	DestCoinType  string                 `protobuf:"bytes,4,opt,name=dest_coin_type,json=destCoinType,proto3" json:"dest_coin_type,omitempty"`  // 目标币种
	DestCoinNum   int64                  `protobuf:"varint,5,opt,name=dest_coin_num,json=destCoinNum,proto3" json:"dest_coin_num,omitempty"`    // 目标币种数量
	TransactionId string                 `protobuf:"bytes,6,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"` // 交易ID
	Platform      string                 `protobuf:"bytes,7,opt,name=platform,proto3" json:"platform,omitempty"`                                // 平台
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeReq) Reset() {
	*x = ExchangeReq{}
	mi := &file_wallet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeReq) ProtoMessage() {}

func (x *ExchangeReq) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeReq.ProtoReflect.Descriptor instead.
func (*ExchangeReq) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{4}
}

func (x *ExchangeReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ExchangeReq) GetSrcCoinType() string {
	if x != nil {
		return x.SrcCoinType
	}
	return ""
}

func (x *ExchangeReq) GetSrcCoinNum() int64 {
	if x != nil {
		return x.SrcCoinNum
	}
	return 0
}

func (x *ExchangeReq) GetDestCoinType() string {
	if x != nil {
		return x.DestCoinType
	}
	return ""
}

func (x *ExchangeReq) GetDestCoinNum() int64 {
	if x != nil {
		return x.DestCoinNum
	}
	return 0
}

func (x *ExchangeReq) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *ExchangeReq) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type ExchangeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gold          int64                  `protobuf:"varint,1,opt,name=gold,proto3" json:"gold,omitempty"`                      // 金瓜子余额
	IapGold       int64                  `protobuf:"varint,2,opt,name=iap_gold,json=iapGold,proto3" json:"iap_gold,omitempty"` // IAP金瓜子余额
	Silver        int64                  `protobuf:"varint,3,opt,name=silver,proto3" json:"silver,omitempty"`                  // 银瓜子余额
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeResp) Reset() {
	*x = ExchangeResp{}
	mi := &file_wallet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeResp) ProtoMessage() {}

func (x *ExchangeResp) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeResp.ProtoReflect.Descriptor instead.
func (*ExchangeResp) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{5}
}

func (x *ExchangeResp) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *ExchangeResp) GetIapGold() int64 {
	if x != nil {
		return x.IapGold
	}
	return 0
}

func (x *ExchangeResp) GetSilver() int64 {
	if x != nil {
		return x.Silver
	}
	return 0
}

type GetDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`          // 用户ID
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"` // 平台
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDetailReq) Reset() {
	*x = GetDetailReq{}
	mi := &file_wallet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDetailReq) ProtoMessage() {}

func (x *GetDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDetailReq.ProtoReflect.Descriptor instead.
func (*GetDetailReq) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{6}
}

func (x *GetDetailReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GetDetailReq) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type GetDetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Detail        *WalletDetail          `protobuf:"bytes,1,opt,name=detail,proto3" json:"detail,omitempty"` // 钱包详情
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDetailResp) Reset() {
	*x = GetDetailResp{}
	mi := &file_wallet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDetailResp) ProtoMessage() {}

func (x *GetDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDetailResp.ProtoReflect.Descriptor instead.
func (*GetDetailResp) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{7}
}

func (x *GetDetailResp) GetDetail() *WalletDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

type WalletDetail struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Uid             int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`                                                  // 用户ID
	Gold            int64                  `protobuf:"varint,2,opt,name=gold,proto3" json:"gold,omitempty"`                                                // 金瓜子
	IapGold         int64                  `protobuf:"varint,3,opt,name=iap_gold,json=iapGold,proto3" json:"iap_gold,omitempty"`                           // IAP金瓜子
	Silver          int64                  `protobuf:"varint,4,opt,name=silver,proto3" json:"silver,omitempty"`                                            // 银瓜子
	GoldRechargeCnt int64                  `protobuf:"varint,5,opt,name=gold_recharge_cnt,json=goldRechargeCnt,proto3" json:"gold_recharge_cnt,omitempty"` // 累计充值
	GoldPayCnt      int64                  `protobuf:"varint,6,opt,name=gold_pay_cnt,json=goldPayCnt,proto3" json:"gold_pay_cnt,omitempty"`                // 累计消费
	SilverPayCnt    int64                  `protobuf:"varint,7,opt,name=silver_pay_cnt,json=silverPayCnt,proto3" json:"silver_pay_cnt,omitempty"`          // 银瓜子消费
	CostBase        int64                  `protobuf:"varint,8,opt,name=cost_base,json=costBase,proto3" json:"cost_base,omitempty"`                        // 消费基数
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WalletDetail) Reset() {
	*x = WalletDetail{}
	mi := &file_wallet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletDetail) ProtoMessage() {}

func (x *WalletDetail) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletDetail.ProtoReflect.Descriptor instead.
func (*WalletDetail) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{8}
}

func (x *WalletDetail) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *WalletDetail) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *WalletDetail) GetIapGold() int64 {
	if x != nil {
		return x.IapGold
	}
	return 0
}

func (x *WalletDetail) GetSilver() int64 {
	if x != nil {
		return x.Silver
	}
	return 0
}

func (x *WalletDetail) GetGoldRechargeCnt() int64 {
	if x != nil {
		return x.GoldRechargeCnt
	}
	return 0
}

func (x *WalletDetail) GetGoldPayCnt() int64 {
	if x != nil {
		return x.GoldPayCnt
	}
	return 0
}

func (x *WalletDetail) GetSilverPayCnt() int64 {
	if x != nil {
		return x.SilverPayCnt
	}
	return 0
}

func (x *WalletDetail) GetCostBase() int64 {
	if x != nil {
		return x.CostBase
	}
	return 0
}

type GetStreamListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`       // 用户ID
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"` // 偏移量
	Limit         int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`   // 返回条数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamListReq) Reset() {
	*x = GetStreamListReq{}
	mi := &file_wallet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamListReq) ProtoMessage() {}

func (x *GetStreamListReq) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamListReq.ProtoReflect.Descriptor instead.
func (*GetStreamListReq) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{9}
}

func (x *GetStreamListReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GetStreamListReq) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetStreamListReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetStreamListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*CoinStreamRecord    `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`    // 流水列表
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // 总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamListResp) Reset() {
	*x = GetStreamListResp{}
	mi := &file_wallet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamListResp) ProtoMessage() {}

func (x *GetStreamListResp) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamListResp.ProtoReflect.Descriptor instead.
func (*GetStreamListResp) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{10}
}

func (x *GetStreamListResp) GetList() []*CoinStreamRecord {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetStreamListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CoinStreamRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                           // 流水ID
	Uid           int64                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`                                         // 用户ID
	TransactionId string                 `protobuf:"bytes,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"` // 交易ID
	CoinType      int32                  `protobuf:"varint,4,opt,name=coin_type,json=coinType,proto3" json:"coin_type,omitempty"`               // 币种类型
	DeltaCoinNum  int64                  `protobuf:"varint,5,opt,name=delta_coin_num,json=deltaCoinNum,proto3" json:"delta_coin_num,omitempty"` // 变化金额
	OrgCoinNum    int64                  `protobuf:"varint,6,opt,name=org_coin_num,json=orgCoinNum,proto3" json:"org_coin_num,omitempty"`       // 原始余额
	OpResult      int32                  `protobuf:"varint,7,opt,name=op_result,json=opResult,proto3" json:"op_result,omitempty"`               // 操作结果
	OpReason      int32                  `protobuf:"varint,8,opt,name=op_reason,json=opReason,proto3" json:"op_reason,omitempty"`               // 失败原因
	OpType        int32                  `protobuf:"varint,9,opt,name=op_type,json=opType,proto3" json:"op_type,omitempty"`                     // 操作类型
	OpTime        string                 `protobuf:"bytes,10,opt,name=op_time,json=opTime,proto3" json:"op_time,omitempty"`                     // 操作时间
	BizCode       string                 `protobuf:"bytes,11,opt,name=biz_code,json=bizCode,proto3" json:"biz_code,omitempty"`                  // 业务代码
	Platform      int32                  `protobuf:"varint,12,opt,name=platform,proto3" json:"platform,omitempty"`                              // 平台
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoinStreamRecord) Reset() {
	*x = CoinStreamRecord{}
	mi := &file_wallet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoinStreamRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoinStreamRecord) ProtoMessage() {}

func (x *CoinStreamRecord) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoinStreamRecord.ProtoReflect.Descriptor instead.
func (*CoinStreamRecord) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{11}
}

func (x *CoinStreamRecord) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CoinStreamRecord) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CoinStreamRecord) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *CoinStreamRecord) GetCoinType() int32 {
	if x != nil {
		return x.CoinType
	}
	return 0
}

func (x *CoinStreamRecord) GetDeltaCoinNum() int64 {
	if x != nil {
		return x.DeltaCoinNum
	}
	return 0
}

func (x *CoinStreamRecord) GetOrgCoinNum() int64 {
	if x != nil {
		return x.OrgCoinNum
	}
	return 0
}

func (x *CoinStreamRecord) GetOpResult() int32 {
	if x != nil {
		return x.OpResult
	}
	return 0
}

func (x *CoinStreamRecord) GetOpReason() int32 {
	if x != nil {
		return x.OpReason
	}
	return 0
}

func (x *CoinStreamRecord) GetOpType() int32 {
	if x != nil {
		return x.OpType
	}
	return 0
}

func (x *CoinStreamRecord) GetOpTime() string {
	if x != nil {
		return x.OpTime
	}
	return ""
}

func (x *CoinStreamRecord) GetBizCode() string {
	if x != nil {
		return x.BizCode
	}
	return ""
}

func (x *CoinStreamRecord) GetPlatform() int32 {
	if x != nil {
		return x.Platform
	}
	return 0
}

var File_wallet_proto protoreflect.FileDescriptor

const file_wallet_proto_rawDesc = "" +
	"\n" +
	"\fwallet.proto\x12\x06wallet\"\xf2\x01\n" +
	"\vRechargeReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x1b\n" +
	"\tcoin_type\x18\x02 \x01(\tR\bcoinType\x12\x19\n" +
	"\bcoin_num\x18\x03 \x01(\x03R\acoinNum\x12%\n" +
	"\x0etransaction_id\x18\x04 \x01(\tR\rtransactionId\x12\x1d\n" +
	"\n" +
	"extend_tid\x18\x05 \x01(\tR\textendTid\x12\x1a\n" +
	"\bplatform\x18\x06 \x01(\tR\bplatform\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12\x19\n" +
	"\bbiz_code\x18\b \x01(\tR\abizCode\"U\n" +
	"\fRechargeResp\x12\x12\n" +
	"\x04gold\x18\x01 \x01(\x03R\x04gold\x12\x19\n" +
	"\biap_gold\x18\x02 \x01(\x03R\aiapGold\x12\x16\n" +
	"\x06silver\x18\x03 \x01(\x03R\x06silver\"\xed\x01\n" +
	"\x06PayReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x1b\n" +
	"\tcoin_type\x18\x02 \x01(\tR\bcoinType\x12\x19\n" +
	"\bcoin_num\x18\x03 \x01(\x03R\acoinNum\x12%\n" +
	"\x0etransaction_id\x18\x04 \x01(\tR\rtransactionId\x12\x1d\n" +
	"\n" +
	"extend_tid\x18\x05 \x01(\tR\textendTid\x12\x1a\n" +
	"\bplatform\x18\x06 \x01(\tR\bplatform\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12\x19\n" +
	"\bbiz_code\x18\b \x01(\tR\abizCode\"P\n" +
	"\aPayResp\x12\x12\n" +
	"\x04gold\x18\x01 \x01(\x03R\x04gold\x12\x19\n" +
	"\biap_gold\x18\x02 \x01(\x03R\aiapGold\x12\x16\n" +
	"\x06silver\x18\x03 \x01(\x03R\x06silver\"\xf2\x01\n" +
	"\vExchangeReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\"\n" +
	"\rsrc_coin_type\x18\x02 \x01(\tR\vsrcCoinType\x12 \n" +
	"\fsrc_coin_num\x18\x03 \x01(\x03R\n" +
	"srcCoinNum\x12$\n" +
	"\x0edest_coin_type\x18\x04 \x01(\tR\fdestCoinType\x12\"\n" +
	"\rdest_coin_num\x18\x05 \x01(\x03R\vdestCoinNum\x12%\n" +
	"\x0etransaction_id\x18\x06 \x01(\tR\rtransactionId\x12\x1a\n" +
	"\bplatform\x18\a \x01(\tR\bplatform\"U\n" +
	"\fExchangeResp\x12\x12\n" +
	"\x04gold\x18\x01 \x01(\x03R\x04gold\x12\x19\n" +
	"\biap_gold\x18\x02 \x01(\x03R\aiapGold\x12\x16\n" +
	"\x06silver\x18\x03 \x01(\x03R\x06silver\"<\n" +
	"\fGetDetailReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\"=\n" +
	"\rGetDetailResp\x12,\n" +
	"\x06detail\x18\x01 \x01(\v2\x14.wallet.WalletDetailR\x06detail\"\xf8\x01\n" +
	"\fWalletDetail\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x12\n" +
	"\x04gold\x18\x02 \x01(\x03R\x04gold\x12\x19\n" +
	"\biap_gold\x18\x03 \x01(\x03R\aiapGold\x12\x16\n" +
	"\x06silver\x18\x04 \x01(\x03R\x06silver\x12*\n" +
	"\x11gold_recharge_cnt\x18\x05 \x01(\x03R\x0fgoldRechargeCnt\x12 \n" +
	"\fgold_pay_cnt\x18\x06 \x01(\x03R\n" +
	"goldPayCnt\x12$\n" +
	"\x0esilver_pay_cnt\x18\a \x01(\x03R\fsilverPayCnt\x12\x1b\n" +
	"\tcost_base\x18\b \x01(\x03R\bcostBase\"R\n" +
	"\x10GetStreamListReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\"W\n" +
	"\x11GetStreamListResp\x12,\n" +
	"\x04list\x18\x01 \x03(\v2\x18.wallet.CoinStreamRecordR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xe3\x02\n" +
	"\x10CoinStreamRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x03R\x03uid\x12%\n" +
	"\x0etransaction_id\x18\x03 \x01(\tR\rtransactionId\x12\x1b\n" +
	"\tcoin_type\x18\x04 \x01(\x05R\bcoinType\x12$\n" +
	"\x0edelta_coin_num\x18\x05 \x01(\x03R\fdeltaCoinNum\x12 \n" +
	"\forg_coin_num\x18\x06 \x01(\x03R\n" +
	"orgCoinNum\x12\x1b\n" +
	"\top_result\x18\a \x01(\x05R\bopResult\x12\x1b\n" +
	"\top_reason\x18\b \x01(\x05R\bopReason\x12\x17\n" +
	"\aop_type\x18\t \x01(\x05R\x06opType\x12\x17\n" +
	"\aop_time\x18\n" +
	" \x01(\tR\x06opTime\x12\x19\n" +
	"\bbiz_code\x18\v \x01(\tR\abizCode\x12\x1a\n" +
	"\bplatform\x18\f \x01(\x05R\bplatform2\x9e\x02\n" +
	"\x06Wallet\x125\n" +
	"\bRecharge\x12\x13.wallet.RechargeReq\x1a\x14.wallet.RechargeResp\x12&\n" +
	"\x03Pay\x12\x0e.wallet.PayReq\x1a\x0f.wallet.PayResp\x125\n" +
	"\bExchange\x12\x13.wallet.ExchangeReq\x1a\x14.wallet.ExchangeResp\x128\n" +
	"\tGetDetail\x12\x14.wallet.GetDetailReq\x1a\x15.wallet.GetDetailResp\x12D\n" +
	"\rGetStreamList\x12\x18.wallet.GetStreamListReq\x1a\x19.wallet.GetStreamListRespB\n" +
	"Z\b./walletb\x06proto3"

var (
	file_wallet_proto_rawDescOnce sync.Once
	file_wallet_proto_rawDescData []byte
)

func file_wallet_proto_rawDescGZIP() []byte {
	file_wallet_proto_rawDescOnce.Do(func() {
		file_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wallet_proto_rawDesc), len(file_wallet_proto_rawDesc)))
	})
	return file_wallet_proto_rawDescData
}

var file_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_wallet_proto_goTypes = []any{
	(*RechargeReq)(nil),       // 0: wallet.RechargeReq
	(*RechargeResp)(nil),      // 1: wallet.RechargeResp
	(*PayReq)(nil),            // 2: wallet.PayReq
	(*PayResp)(nil),           // 3: wallet.PayResp
	(*ExchangeReq)(nil),       // 4: wallet.ExchangeReq
	(*ExchangeResp)(nil),      // 5: wallet.ExchangeResp
	(*GetDetailReq)(nil),      // 6: wallet.GetDetailReq
	(*GetDetailResp)(nil),     // 7: wallet.GetDetailResp
	(*WalletDetail)(nil),      // 8: wallet.WalletDetail
	(*GetStreamListReq)(nil),  // 9: wallet.GetStreamListReq
	(*GetStreamListResp)(nil), // 10: wallet.GetStreamListResp
	(*CoinStreamRecord)(nil),  // 11: wallet.CoinStreamRecord
}
var file_wallet_proto_depIdxs = []int32{
	8,  // 0: wallet.GetDetailResp.detail:type_name -> wallet.WalletDetail
	11, // 1: wallet.GetStreamListResp.list:type_name -> wallet.CoinStreamRecord
	0,  // 2: wallet.Wallet.Recharge:input_type -> wallet.RechargeReq
	2,  // 3: wallet.Wallet.Pay:input_type -> wallet.PayReq
	4,  // 4: wallet.Wallet.Exchange:input_type -> wallet.ExchangeReq
	6,  // 5: wallet.Wallet.GetDetail:input_type -> wallet.GetDetailReq
	9,  // 6: wallet.Wallet.GetStreamList:input_type -> wallet.GetStreamListReq
	1,  // 7: wallet.Wallet.Recharge:output_type -> wallet.RechargeResp
	3,  // 8: wallet.Wallet.Pay:output_type -> wallet.PayResp
	5,  // 9: wallet.Wallet.Exchange:output_type -> wallet.ExchangeResp
	7,  // 10: wallet.Wallet.GetDetail:output_type -> wallet.GetDetailResp
	10, // 11: wallet.Wallet.GetStreamList:output_type -> wallet.GetStreamListResp
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_wallet_proto_init() }
func file_wallet_proto_init() {
	if File_wallet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wallet_proto_rawDesc), len(file_wallet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wallet_proto_goTypes,
		DependencyIndexes: file_wallet_proto_depIdxs,
		MessageInfos:      file_wallet_proto_msgTypes,
	}.Build()
	File_wallet_proto = out.File
	file_wallet_proto_goTypes = nil
	file_wallet_proto_depIdxs = nil
}
