// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	wallet "mybilibili/app/wallet/cmd/api/internal/handler/wallet"
	"mybilibili/app/wallet/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 查询余额
				Method:  http.MethodGet,
				Path:    "/detail",
				Handler: wallet.GetDetailHandler(serverCtx),
			},
			{
				// 兑换
				Method:  http.MethodPost,
				Path:    "/exchange",
				Handler: wallet.ExchangeHandler(serverCtx),
			},
			{
				// 消费
				Method:  http.MethodPost,
				Path:    "/pay",
				Handler: wallet.PayHandler(serverCtx),
			},
			{
				// 充值
				Method:  http.MethodPost,
				Path:    "/recharge",
				Handler: wallet.RechargeHandler(serverCtx),
			},
			{
				// 查询流水
				Method:  http.MethodGet,
				Path:    "/stream",
				Handler: wallet.GetStreamListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/wallet/v1"),
	)
}
