// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: wallet.proto

package wallet_client

import (
	"context"

	"mybilibili/app/wallet/cmd/rpc/wallet"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CoinStreamRecord  = wallet.CoinStreamRecord
	ExchangeReq       = wallet.ExchangeReq
	ExchangeResp      = wallet.ExchangeResp
	GetDetailReq      = wallet.GetDetailReq
	GetDetailResp     = wallet.GetDetailResp
	GetStreamListReq  = wallet.GetStreamListReq
	GetStreamListResp = wallet.GetStreamListResp
	PayReq            = wallet.PayReq
	PayResp           = wallet.PayResp
	RechargeReq       = wallet.RechargeReq
	RechargeResp      = wallet.RechargeResp
	WalletDetail      = wallet.WalletDetail

	Wallet interface {
		// 充值
		Recharge(ctx context.Context, in *RechargeReq, opts ...grpc.CallOption) (*RechargeResp, error)
		// 消费
		Pay(ctx context.Context, in *PayReq, opts ...grpc.CallOption) (*PayResp, error)
		// 兑换
		Exchange(ctx context.Context, in *ExchangeReq, opts ...grpc.CallOption) (*ExchangeResp, error)
		// 查询余额详情
		GetDetail(ctx context.Context, in *GetDetailReq, opts ...grpc.CallOption) (*GetDetailResp, error)
		// 查询流水列表
		GetStreamList(ctx context.Context, in *GetStreamListReq, opts ...grpc.CallOption) (*GetStreamListResp, error)
	}

	defaultWallet struct {
		cli zrpc.Client
	}
)

func NewWallet(cli zrpc.Client) Wallet {
	return &defaultWallet{
		cli: cli,
	}
}

// 充值
func (m *defaultWallet) Recharge(ctx context.Context, in *RechargeReq, opts ...grpc.CallOption) (*RechargeResp, error) {
	client := wallet.NewWalletClient(m.cli.Conn())
	return client.Recharge(ctx, in, opts...)
}

// 消费
func (m *defaultWallet) Pay(ctx context.Context, in *PayReq, opts ...grpc.CallOption) (*PayResp, error) {
	client := wallet.NewWalletClient(m.cli.Conn())
	return client.Pay(ctx, in, opts...)
}

// 兑换
func (m *defaultWallet) Exchange(ctx context.Context, in *ExchangeReq, opts ...grpc.CallOption) (*ExchangeResp, error) {
	client := wallet.NewWalletClient(m.cli.Conn())
	return client.Exchange(ctx, in, opts...)
}

// 查询余额详情
func (m *defaultWallet) GetDetail(ctx context.Context, in *GetDetailReq, opts ...grpc.CallOption) (*GetDetailResp, error) {
	client := wallet.NewWalletClient(m.cli.Conn())
	return client.GetDetail(ctx, in, opts...)
}

// 查询流水列表
func (m *defaultWallet) GetStreamList(ctx context.Context, in *GetStreamListReq, opts ...grpc.CallOption) (*GetStreamListResp, error) {
	client := wallet.NewWalletClient(m.cli.Conn())
	return client.GetStreamList(ctx, in, opts...)
}
