// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type GetHotRankListReq struct {
	Offset int64 `form:"offset,optional,default=0"` // 偏移量
	Limit  int64 `form:"limit,optional,default=50"` // 返回条数
}

type GetHotRankListResp struct {
	List  []HotRankItem `json:"list"`  // 排行榜列表
	Total int64         `json:"total"` // 总数
}

type GetRegionHotRankListReq struct {
	RegionId int64 `form:"region_id"`                 // 分区ID
	Offset   int64 `form:"offset,optional,default=0"` // 偏移量
	Limit    int64 `form:"limit,optional,default=50"` // 返回条数
}

type GetRegionHotRankListResp struct {
	List  []HotRankItem `json:"list"`  // 排行榜列表
	Total int64         `json:"total"` // 总数
}

type GetVideoDetailReq struct {
	Vid int64 `path:"vid"` // 视频ID
}

type GetVideoDetailResp struct {
	Video VideoDetail `json:"video"` // 视频详情
}

type HotRankItem struct {
	Oid    int64  `json:"oid"`    // 视频ID
	Hot    int64  `json:"hot"`    // 热度值
	Rank   int64  `json:"rank"`   // 排名
	Title  string `json:"title"`  // 视频标题
	Cover  string `json:"cover"`  // 封面
	Author string `json:"author"` // 作者
	View   int64  `json:"view"`   // 播放量
	Like   int64  `json:"like"`   // 点赞数
}

type VideoDetail struct {
	Vid        int64  `json:"vid"`         // 视频ID
	Title      string `json:"title"`       // 标题
	Cover      string `json:"cover"`       // 封面
	AuthorId   int64  `json:"author_id"`   // 作者ID
	AuthorName string `json:"author_name"` // 作者名称
	RegionId   int64  `json:"region_id"`   // 分区ID
	PubTime    int64  `json:"pub_time"`    // 发布时间
	Duration   int32  `json:"duration"`    // 时长（秒）
	Desc       string `json:"desc"`        // 简介
	View       int64  `json:"view"`        // 播放量
	Like       int64  `json:"like"`        // 点赞数
	Coin       int64  `json:"coin"`        // 投币数
	Fav        int64  `json:"fav"`         // 收藏数
	Share      int64  `json:"share"`       // 分享数
	Reply      int64  `json:"reply"`       // 评论数
	Danmaku    int64  `json:"danmaku"`     // 弹幕数
	Hot        int64  `json:"hot"`         // 热度值
}
